Repository HabitRPG/habitica, pull requests merged in 2018-10, with the labels that each got.

#10029 raise coverage for tasks api calls
  config.json.example
  test/api/unit/libs/taskManager.js
  test/api/v3/integration/tasks/groups/PUT-group_task_id.test.js
  test/client/unit/specs/store/getters/tasks/canDelete.js
  test/client/unit/specs/store/getters/tasks/getTaskClasses.js
  website/server/models/task.js
Labels: status: pr: with author: needs work

#10620 Social user username
  migrations/users/generate-usernames.js
  package-lock.json
  package.json
  test/api/v3/integration/user/auth/POST-user_auth_social.test.js
  website/server/controllers/api-v3/auth.js
  website/server/libs/auth/index.js
  website/server/libs/auth/social.js
  website/server/libs/auth/utils.js
Labels: status: pr: with author: needs work

#10487 Inbox: cleanup
  test/api/v3/integration/user/DELETE-user_messages.test.js
  test/api/v4/user/GET-user.test.js
  website/server/libs/inbox/index.js
  website/server/models/user/schema.js
Labels: status: pr: ready for review

#10735 Remove items with a class that have been lost from Class:None in shop
  website/common/script/libs/shops.js
Labels: status: pr: ready for review

#10724 Add errors for any param validation failures (not just authentication) to the snackbar
  website/client/app.vue
Labels: status: pr: ready for review

#10713 Decrease mana when removing stat points from int
  website/client/components/userMenu/profileStats.vue
Labels: status: pr: ready for review

#10672 Css font home page update
  website/client/components/static/header.vue
  website/client/components/static/home.vue
Labels: status: pr: ready for review

#10665 Don't show "no guilds" texts while loading
  website/client/components/challenges/myChallenges.vue
  website/client/components/groups/myGuilds.vue
Labels: status: pr: tested and approved; merge pending

#10639 Issue 10414 - Remove Member Option from View Party link.
  website/client/components/header/index.vue
Labels: status: pr: merged in develop; deploy pending

#10663 Guild textarea at list positioning
  website/client/components/chat/autoComplete.vue
  website/client/components/groups/chat.vue
Labels: status: pr: ready for review

#10754 Analytics: clean up old A/B test code & add username verify flag
  test/api/v3/integration/user/auth/POST-register_local.test.js
  test/api/v3/integration/user/auth/POST-user_auth_social.test.js
  website/server/controllers/api-v3/groups.js
  website/server/controllers/api-v3/tasks.js
  website/server/libs/analyticsService.js
  website/server/libs/cron.js
  website/server/models/user/hooks.js
Labels: status: pr: ready for review

#10749 api: Fix a few API documentation typos
  website/server/controllers/api-v3/members.js
  website/server/controllers/api-v3/user.js
  website/server/controllers/api-v3/webhook.js
  website/server/controllers/api-v4/user.js
Labels: status: pr: ready for review

#10745 (#10743) Pinned gala gear showing as pinned in the market
  website/common/script/libs/getItemInfo.js
Labels: status: pr: tested and approved; merge pending

#10704 Group Management Menu Fixes
  website/client/components/groups/membersModal.vue
  website/common/locales/en/groups.json
Labels: status: pr: merged in develop; deploy pending

#10744 No matching Guilds/Challenges message
  website/client/components/challenges/findChallenges.vue
  website/client/components/challenges/myChallenges.vue
  website/client/components/groups/discovery.vue
  website/client/components/groups/myGuilds.vue
  website/client/components/groups/sidebar.vue
  website/common/locales/en/challenge.json
  website/common/locales/en/groups.json
Labels: status: pr: ready for review

#10760 check every armoire gear 'canOwn' method
  test/common/ops/armoireCanOwn.js
  website/common/script/content/gear/sets/armoire.js
Labels: status: pr: ready for review

#10734 Issue 10728: sort equipment by stat descending on Market page
  website/client/components/shops/market/equipmentSection.vue
Labels: status: pr: ready for review

#10769 Custom reward action background and font-color updates
  website/client/assets/scss/task.scss
  website/client/components/tasks/task.vue
Labels: status: pr: merged in develop; deploy pending

#10759 fix for #10496: Newly subscribed accounts receive erroneous notification that they have Mystery Items
  test/api/unit/libs/payments/payments.test.js
  website/server/libs/payments/subscriptions.js
Labels: status: pr: ready for review

#10772 Corrects the white bar above the header and updates the text styling
  website/client/components/groups/groupPlan.vue
Labels: status: pr: ready for review

#10765 Veteran Pet ladder award for users affected by username changes
  migrations/archive/2018/20181002_username_email.js
  migrations/users/20181023_veteran_pet_ladder.js
  website/client/libs/staffList.js
  website/common/locales/en/pets.json
  website/common/script/content/stable.js
  website/raw_sprites/spritesmith/npcs/npc_apollo.png
  website/raw_sprites/spritesmith/npcs/npc_piyo.png
  website/raw_sprites/spritesmith/npcs/npc_sabe.png
  website/raw_sprites/spritesmith/stable/pets/Pet-Fox-Veteran.png
  website/raw_sprites/spritesmith_large/promo_veteran_pets.png
  website/server/controllers/api-v3/news.js
  website/server/controllers/api-v4/auth.js
  website/server/models/user/hooks.js
Labels: status: pr: ready for review

#10782 Added explanatory webhook text to UI.
  website/client/components/settings/api.vue
  website/common/locales/en/settings.json
Labels: status: pr: ready for review

#10792 Fix filter checkboxes in seasonal shop
  website/client/components/shops/seasonal/index.vue
Labels: status: pr: ready for review
