Repository HabitRPG/habitica, pull requests merged in 2018-11, with the labels that each got.

#10783 If user's cron will happen later today, start the task yesterday.
  test/common/libs/taskDefaults.test.js
  test/common/shouldDo.test.js
  website/client/components/challenges/challengeDetail.vue
  website/client/components/chat/copyAsTodoModal.vue
  website/client/components/group-plans/taskInformation.vue
  website/client/components/tasks/column.vue
  website/client/components/tasks/user.vue
  website/common/script/libs/taskDefaults.js
  website/common/script/ops/addTask.js
Labels: status: pr: merged in develop; deploy pending

#10797 Check pet can be hatched before highlighting
  website/client/components/inventory/items/index.vue
Labels: status: pr: ready for review

#10808 fix: special are not "AllowedToFeed"
  website/client/libs/createAnimal.js
Labels: status: pr: ready for review

#10818 prevent buying market gear if class doesn't match
  test/api/v3/integration/user/buy/POST-user_buy_gear.test.js
  website/common/script/ops/buy/buyMarketGear.js
Labels: status: pr: ready for review

#10836 Update Username Route: Move to v3
  test/api/v3/integration/user/auth/PUT-user_update_username.test.js
  test/api/v4/user/auth/PUT-user_update_username.test.js
  website/server/controllers/api-v3/auth.js
  website/server/controllers/api-v4/auth.js
  website/server/middlewares/appRoutes.js
Labels: status: pr: ready for review

#10802 groupChatReceived webhook fix
  test/api/unit/models/group.test.js
  website/server/controllers/api-v3/chat.js
  website/server/models/group.js
Labels: status: pr: ready for review

#10840 Fix text overflow issue on task checklists
  website/client/components/tasks/task.vue
Labels: status: pr: ready for review

#10812 "Very large Guild member counts overflow the badge" partial fix for #10753
  website/client/mixins/groupsUtilities.js
Labels: status: pr: ready for review

#10859 additional checks on gear purchase
  test/common/ops/buy/buyMarketGear.js
  website/common/script/ops/buy/buyMarketGear.js
Labels: status: pr: ready for review

#10862 Footer: always show expanded footer
  website/client/components/appFooter.vue
Labels: status: pr: ready for review

#10861 Fixes issue #10857 ("Tags have extra space at the bottom when they should be centered")
  website/client/components/tasks/task.vue
  website/client/components/tasks/taskModal.vue
Labels: status: pr: ready for review

#10845 Attach client to chat messages
  website/client/components/chat/chatCard.vue
  website/server/controllers/api-v3/chat.js
  website/server/models/group.js
  website/server/models/message.js
Labels: status: pr: ready for review, type: notify helpers
