Repository HabitRPG/habitica, pull requests merged in 2018-05, with the labels that each got.

#10301 Remove inbox from some user routes
  website/server/controllers/api-v3/user.js
Labels: status: pr: tested and approved; merge pending

#10302 Remove inbox from tasks routes
  website/server/controllers/api-v3/tasks.js
  website/server/controllers/api-v3/tasks/groups.js
Labels: status: pr: tested and approved; merge pending

#10307 #10256 - The placeholder and the message row are fixed
  website/client/components/userMenu/inbox.vue
  website/common/locales/en/groups.json
Labels: status: pr: tested and approved; merge pending

#10309 Mount raising modal header stuck naming fixed
  website/client/components/inventory/stable/mountRaisedModal.vue
Labels: status: pr: tested and approved; merge pending

#10311 Add responsive margins to pets and mounts.
  website/client/assets/scss/item.scss
Labels: status: pr: tested and approved; merge pending

#10314 Fixed learn more in user dropdown.
  website/client/components/header/userDropdown.vue
Labels: status: pr: tested and approved; merge pending

#10315 Fixed columns when translation is too long.
  website/client/components/tasks/column.vue
Labels: status: pr: tested and approved; merge pending

#10342 Fixed tavern chat buttons.
  website/client/components/groups/tavern.vue
Labels: status: pr: tested and approved; merge pending

#10226 Prevent accidental submission of Tavern/Guild posts after pasting
  website/client/components/groups/group.vue
  website/client/components/groups/tavern.vue
Labels: status: pr: tested and approved; merge pending

#10338 Beard and mustache facial hairs now can be bought as a full set for 5 gems
  website/client/components/creatorIntro.vue
  website/client/components/header/menu.vue
  website/client/components/snackbars/notifications.vue
Labels: status: pr: merged in develop; deploy pending

#10346 Fixed Lunar Battle quest scrolls showing wrong unlock conditions (Issue #10294 )
  website/client/components/shops/quests/index.vue
Labels: status: pr: ready for review

#10357 disabling checking off a subtask if not assigned to a user
  website/client/components/tasks/task.vue
Labels: status: pr: merged in develop; deploy pending

#10349 groups: Fix Markdown for claimed task messages
  website/common/locales/en/groups.json
Labels: status: pr: merged in develop; deploy pending

#10364 Avoid using media element with empty src attribute
  website/client/app.vue
Labels: status: pr: tested and approved; merge pending

#10367 tests: Increase timeouts instead of disabling them
  test/api/v3/integration/challenges/GET-challenges_challengeId_members.test.js
  test/api/v3/integration/groups/GET-groups_groupId_members.test.js
Labels: status: pr: tested and approved; merge pending

#10350 redirects: Fix parsing BASE_URL with port number
  website/server/middlewares/redirects.js
Labels: status: pr: tested and approved; merge pending

#10370 added try catch, added snackbar notification for errors returned
  website/client/components/inventory/stable/index.vue
Labels: status: pr: merged in develop; deploy pending

#10360 Fix drawer text overlapping at smaller screen resolutions
  website/client/components/ui/drawerHeaderTabs.vue
Labels: status: pr: tested and approved; merge pending

#10368 Remove Ethereal Surge notification
  website/client/mixins/spells.js
  website/common/locales/en/spells.json
Labels: status: pr: tested and approved; merge pending

#10358 Change reward popunder
  website/client/components/tasks/column.vue
  website/common/locales/en/tasks.json
Labels: status: pr: tested and approved; merge pending

#10138 Make nav drop-down cleaner/scrollable
  package-lock.json
  website/client/components/header/index.vue
  website/client/components/header/menu.vue
Labels: status: pr: tested and approved; merge pending

#10383 Fix 9248: challenge creator should not automatically join their own challenge
  test/api/v3/integration/challenges/DELETE-challenges_challengeId.test.js
  test/api/v3/integration/challenges/GET-challenges_challengeId.test.js
  test/api/v3/integration/challenges/GET-challenges_challengeId_export_csv.test.js
  test/api/v3/integration/challenges/GET-challenges_challengeId_members.test.js
  test/api/v3/integration/challenges/GET-challenges_challengeId_members_memberId.test.js
  test/api/v3/integration/challenges/GET-challenges_group_groupid.test.js
  test/api/v3/integration/challenges/GET-challenges_user.test.js
  test/api/v3/integration/challenges/POST-challenges.test.js
  test/api/v3/integration/challenges/POST-challenges_challengeId_join.test.js
  test/api/v3/integration/challenges/POST-challenges_challengeId_leave.test.js
  test/api/v3/integration/challenges/POST-challenges_challengeId_winner_winnerId.test.js
  test/api/v3/integration/challenges/PUT-challenges_challengeId.test.js
  test/api/v3/integration/groups/POST-groups_groupId_leave.js
  test/api/v3/integration/tasks/DELETE-tasks_id.test.js
  test/api/v3/integration/tasks/GET-tasks_challenge_challengeId.test.js
  test/api/v3/integration/tasks/POST-tasks_clearCompletedTodos.test.js
  test/api/v3/integration/tasks/POST-tasks_unlink-all_challengeId.test.js
  test/api/v3/integration/tasks/POST-tasks_unlink-one_taskId.test.js
  test/api/v3/integration/tasks/PUT-tasks_id.test.js
  test/api/v3/integration/tasks/challenges/DELETE-tasks_challenge_challengeId_checklist_itemId.test.js
  test/api/v3/integration/tasks/challenges/DELETE-tasks_id_challenge_challengeId.test.js
  test/api/v3/integration/tasks/challenges/GET_tasks_challenge.id.test.js
  test/api/v3/integration/tasks/challenges/POST-tasks_challenge_challengeId_taskId_checklist.test.js
  test/api/v3/integration/tasks/challenges/POST-tasks_challenge_id.test.js
  test/api/v3/integration/tasks/challenges/POST-tasks_challenges_challengeId_tasks_id_score_direction.test.js
  test/api/v3/integration/tasks/challenges/PUT-tasks_challenge_challengeId.test.js
  test/api/v3/integration/tasks/challenges/PUT-tasks_challenge_challengeId_tasksId_checklist_itemId.test.js
  test/api/v3/integration/user/DELETE-user.test.js
  test/api/v3/integration/user/POST-user_class_cast_spellId.test.js
  test/api/v3/integration/user/POST-user_reset.test.js
  website/client/store/actions/challenges.js
  website/server/libs/challenges/index.js
  website/server/models/challenge.js
Labels: status: pr: tested and approved; merge pending

#10393 Send quest invitations to google users
  website/server/controllers/api-v3/quests.js
Labels: status: pr: merged in develop; deploy pending

#10376 client: Fix display of class bonus for other users
  website/client/components/inventory/equipment/attributesGrid.vue
  website/client/components/inventory/equipment/attributesPopover.vue
  website/client/components/inventory/equipment/equipGearModal.vue
  website/client/components/shops/buyModal.vue
  website/client/components/userMenu/profileStats.vue
Labels: status: pr: merged in develop; deploy pending

#10395 only store necessary data for social login (continuation of 10352)
  migrations/users/remove-social-users-extra-data.js
  test/api/v3/unit/libs/email.test.js
  website/server/controllers/api-v3/auth.js
  website/server/libs/email.js
  website/server/models/user/hooks.js
Labels: status: pr: ready for review

#10387 Api quest restrictions - no purchase/start without fulfilling eligibility requirements
  test/api/v3/integration/user/buy/POST-user_buy_quest.test.js
  test/common/ops/buy/buyQuest.js
  test/helpers/api-integration/v3/object-generators.js
  website/common/locales/en/quests.json
  website/common/script/ops/buy/buy.js
  website/common/script/ops/buy/buyQuest.js
  website/server/controllers/api-v3/user.js
  website/server/libs/password.js
  website/server/server.js
Labels: status: pr: tested and approved; merge pending
