Repository HabitRPG/habitica, pull requests merged in 2018-07, with the labels that each got.

#10499 Small Group Plan fixes
  website/client/components/tasks/taskModal.vue
Labels: status: pr: ready for review

#10492 Fixed Inn banner and nav bar behave oddly when scrolling
  website/client/app.vue
Labels: status: pr: tested and approved; merge pending

#10490 Fixed the unnecessary whitespace to the right of landing page (#10435)
  website/client/components/static/home.vue
Labels: status: pr: tested and approved; merge pending

#10497 Ensured redirect is using base
  website/client/components/auth/authForm.vue
  website/client/components/auth/registerLoginReset.vue
  website/client/components/static/home.vue
Labels: status: pr: ready for review

#10022 Logout Changes #9915
  webpack/config/index.js
  website/client/components/auth/logout.vue
  website/client/router.js
  website/client/store/actions/auth.js
  website/server/controllers/top-level/auth.js
Labels: status: pr: tested and approved; merge pending

#10260 Adding hand cursor to FAQ headings, and ability to address answers via URL hash
  website/client/components/static/faq.vue
Labels: status: pr: tested and approved; merge pending, type: notify helpers

#10495 Fixes Text overflow on task checklists
  website/client/components/tasks/column.vue
Labels: status: pr: tested and approved; merge pending

#10504 member-details: Only add 1px margin when condensed
  website/client/components/memberDetails.vue
Labels: status: pr: tested and approved; merge pending

#10494 Max 3000 Character Limit on Chat-Messages
  test/api/v3/integration/chat/POST-chat.test.js
  website/client/components/groups/chat.vue
  website/server/models/group.js
Labels: status: pr: ready for review

#10505 fix xml export
  test/api/v3/integration/dataexport/GET-export_userdata.xml.test.js
  webpack/config/index.js
  website/server/controllers/top-level/dataexport.js
Labels: status: pr: ready for review

#10507 Flag-Modal: Reset comment
  website/client/components/chat/reportFlagModal.vue
Labels: status: pr: merged in develop; deploy pending

#10506 Free Class-Change not showing gem cost for analytics call
  website/common/script/ops/changeClass.js
Labels: status: pr: ready for review

#10525 FIX: Challenge Creation without Group not found error
  website/client/components/challenges/challengeModal.vue
Labels: status: pr: ready for review

#10515 Group Tasks Shared Completion
  test/api/v3/integration/tasks/groups/POST-group_tasks_id_approve_userId.test.js
  test/api/v3/integration/tasks/groups/POST-group_tasks_id_score_direction.test.js
  website/client/components/group-plans/taskInformation.vue
  website/client/components/tasks/column.vue
  website/client/components/tasks/taskModal.vue
  website/client/store/actions/tasks.js
  website/common/locales/en/groups.json
  website/server/controllers/api-v3/tasks.js
  website/server/controllers/api-v3/tasks/groups.js
  website/server/libs/groupTasks.js
  website/server/libs/taskManager.js
  website/server/models/group.js
  website/server/models/task.js
Labels: status: pr: ready for review

#10526 Show snackbar on client-side purchase-checks
  website/client/mixins/buy.js
Labels: status: pr: merged in develop; deploy pending

#10493 Fix Modal Stack - reopening modals
  website/client/app.vue
  website/client/components/notifications.vue
  website/client/components/snackbars/notification.vue
  website/client/mixins/notifications.js
  website/common/locales/en/achievements.json
Labels: status: pr: ready for review

#10530 Adjust CSS margin of Markdown headers and paragraphs
  website/client/assets/scss/markdown.scss
Labels: status: pr: tested and approved; merge pending

#10543 Update stat point title
  website/client/components/userMenu/profileStats.vue
  website/common/locales/en/character.json
Labels: status: pr: ready for review

#10541 fixed new message count alignment
  website/client/components/header/userDropdown.vue
Labels: status: pr: ready for review

#10537 Fixed guild badge color text
  website/client/components/groups/publicGuildItem.vue
Labels: status: pr: ready for review

#10536 Display exact date on hover
  website/client/components/chat/chatCard.vue
Labels: status: pr: ready for review

#10535 Allow for stat edits on mobile
  website/client/components/userMenu/profileStats.vue
Labels: status: pr: ready for review

#10540 Reset gift message
  website/client/components/payments/sendGemsModal.vue
Labels: status: pr: ready for review

#10539 Added copy to detail blocks wont work on mods
  website/client/components/userMenu/profile.vue
  website/common/locales/en/groups.json
Labels: status: pr: ready for review

#10534 Change streak achievement snack to text type
  website/client/components/notifications.vue
Labels: status: pr: ready for review

#10538 Removed extra options and fixed copy userID
  website/client/components/groups/createPartyModal.vue
Labels: status: pr: ready for review

#10542 Removed duplicate code and added member modal event
  website/client/components/challenges/challengeDetail.vue
  website/client/components/groups/group.vue
  website/client/components/groups/membersModal.vue
  website/client/components/header/index.vue
Labels: status: pr: with author: needs work

#10545 Separated out modal components
  website/client/components/inventory/stable/hatchingModal.vue
  website/client/components/inventory/stable/index.vue
  website/client/components/inventory/stable/welcomeModal.vue
  website/client/mixins/petMixin.js
Labels: status: pr: with author: needs work

#10561 Fix advanced settings from always starting collapsed
  website/client/components/tasks/taskModal.vue
Labels: status: pr: tested and approved; merge pending

#10559 Fix user receiving Joined Challenged achievement when creating a challenge
  test/api/v3/integration/challenges/POST-challenges.test.js
  website/server/libs/challenges/index.js
Labels: status: pr: merged in develop; deploy pending

#10552 Fix drag scrolling tasks when character has abilities
  .gitignore
  website/client/components/tasks/column.vue
Labels: status: pr: tested and approved; merge pending

#10532 Re-enable start quest button
  website/client/components/groups/group.vue
  website/client/components/groups/startQuestModal.vue
Labels: status: pr: tested and approved; merge pending

#10531 View participant list of active quest
  website/client/components/groups/group.vue
  website/client/components/groups/participantListModal.vue
  website/client/components/groups/questSidebarSection.vue
Labels: status: pr: tested and approved; merge pending

#10547 Esc only closes active tags box, not entire task
  website/client/components/tasks/taskModal.vue
Labels: status: pr: tested and approved; merge pending

#10560 Mana bar no longer shown on profile if user has opted out of class system
  test/api/v3/integration/groups/GET-groups_groupId_members.test.js
  test/api/v3/integration/members/GET-members_id.test.js
  website/server/models/user/index.js
Labels: status: pr: tested and approved; merge pending

#10550 Clicking out only closes active tags box, not entire task
  website/client/components/tasks/taskModal.vue
Labels: status: pr: tested and approved; merge pending

#10524 prevent multiple notifications
  test/api/v3/integration/notifications/prevent-multiple-notification.js
  website/server/models/user/methods.js
  website/server/models/userNotification.js
Labels: status: pr: ready for review
