Repository HabitRPG/habitica, pull requests merged in 2018-12, with the labels that each got.

#10863 Paypal and Amazon: Improve checkout experience
  website/client/app.vue
  website/client/components/page.vue
  website/client/components/payments/amazonModal.vue
  website/client/components/payments/buyGemsModal.vue
  website/client/components/payments/successModal.vue
  website/client/components/settings/subscription.vue
  website/client/libs/userlocalManager.js
  website/client/main.js
  website/client/mixins/payments.js
  website/client/router/handleRedirect.js
  website/client/router/index.js
  website/common/locales/en/npc.json
  website/server/controllers/top-level/payments/paypal.js
Labels: status: pr: with author: needs work

#10886 Accoount Deletion Feedback:update email #10880
  website/server/controllers/api-v3/user.js
Labels: status: pr: ready for review

#10896 Fixed typo in folder path
  gulp/gulp-tests.js
Labels: status: pr: ready for review

#10903 Payments: Success Messages
  website/client/app.vue
  website/client/components/achievements/questCompleted.vue
  website/client/components/group-plans/createGroupModalPages.vue
  website/client/components/groups/groupPlan.vue
  website/client/components/payments/amazonModal.vue
  website/client/components/payments/buyGemsModal.vue
  website/client/components/payments/sendGemsModal.vue
  website/client/components/payments/successModal.vue
  website/client/components/settings/subscription.vue
  website/client/mixins/payments.js
  website/client/store/actions/auth.js
  website/common/locales/en/groups.json
  website/common/locales/en/npc.json
  website/common/locales/en/settings.json
  website/common/locales/en/subscriber.json
Labels: status: pr: merged in develop; deploy pending

#10898 Usernames Misc: Bulk Email and New Party Modal
  migrations/archive/2018/20180724_summer_splash_orcas.js
  migrations/archive/2018/20180731_naming_day.js
  migrations/archive/2018/20181001_generate_usernames.js
  migrations/archive/2018/20181023_veteran_pet_ladder.js
  migrations/archive/2018/20181030_habitoween_ladder.js
  migrations/archive/2018/20181122_turkey_day.js
  migrations/users/bulk-email.js
  website/client/assets/images/basilist.png
  website/client/assets/images/basilist@2x.png
  website/client/assets/images/basilist@3x.png
  website/client/assets/images/group@3x.png
  website/client/assets/images/party@2x.png
  website/client/assets/images/party@3x.png
  website/client/components/groups/createPartyModal.vue
  website/common/locales/en/groups.json
Labels: status: pr: ready for review

#10892 Allow gems and subs to be gifted through in-app-purchases
  test/api/unit/libs/payments/apple.test.js
  test/api/unit/libs/payments/google.test.js
  test/api/v3/integration/payments/apple/POST-payments_apple_norenewsubscribe.test.js
  test/api/v3/integration/payments/apple/POST-payments_apple_subscribe.test.js
  test/api/v3/integration/payments/apple/POST-payments_apple_verifyiap.js
  test/api/v3/integration/payments/google/POST-payments_google_norenewsubscribe.test.js
  test/api/v3/integration/payments/google/POST-payments_google_verifyiap.js
  test/helpers/mongoose.helper.js
  website/server/controllers/top-level/payments/iap.js
  website/server/libs/payments/apple.js
  website/server/libs/payments/google.js
  website/server/libs/payments/subscriptions.js
Labels: status: pr: ready for review

#10913 Streak-Achievement notification/modal timeout
  website/client/components/notifications.vue
Labels: status: pr: ready for review

#10911 drag tags to reorder
  website/client/assets/svg/drag_indicator.svg
  website/client/components/tasks/user.vue
  website/client/store/actions/tags.js
  website/server/controllers/api-v3/tags.js
Labels: status: pr: ready for review

#10894 Unit Tests; 1 fix to appFooter debug menu
  test/client/unit/specs/components/avatar.vue.test.js
  test/client/unit/specs/store/getters/user/user.test.js
  test/client/unit/specs/store/getters/user/userGems.js
  test/content/translator.js
  website/client/components/appFooter.vue
Labels: status: pr: ready for review

#10909 extract site urls from translations
  website/client/components/inventory/stable/hatchedPetDialog.vue
  website/client/components/static/overview.vue
  website/common/locales/en/overview.json
  website/common/locales/en/pets.json
Labels: status: pr: ready for review

#10870 Prevent progress being cleared when quest ends
  test/api/unit/models/group.test.js
  website/server/controllers/api-v3/quests.js
  website/server/models/group.js
Labels: status: pr: ready for review, type: notify helpers
