Repository HabitRPG/habitica, pull requests merged in 2018-02, with the labels that each got.

#9323 Triumph Theme by anastasiagaskamp
  website/common/locales/en/generic.json
  website/common/script/content/index.js
  website/static/audio/triumphTheme/Achievement_Unlocked.mp3
  website/static/audio/triumphTheme/Achievement_Unlocked.ogg
  website/static/audio/triumphTheme/Chat.mp3
  website/static/audio/triumphTheme/Chat.ogg
  website/static/audio/triumphTheme/Daily.mp3
  website/static/audio/triumphTheme/Daily.ogg
  website/static/audio/triumphTheme/Death.mp3
  website/static/audio/triumphTheme/Death.ogg
  website/static/audio/triumphTheme/Item_Drop.mp3
  website/static/audio/triumphTheme/Item_Drop.ogg
  website/static/audio/triumphTheme/Level_Up.mp3
  website/static/audio/triumphTheme/Level_Up.ogg
  website/static/audio/triumphTheme/Minus_Habit.mp3
  website/static/audio/triumphTheme/Minus_Habit.ogg
  website/static/audio/triumphTheme/Plus_Habit.mp3
  website/static/audio/triumphTheme/Plus_Habit.ogg
  website/static/audio/triumphTheme/Reward.mp3
  website/static/audio/triumphTheme/Reward.ogg
  website/static/audio/triumphTheme/ToDo.mp3
  website/static/audio/triumphTheme/ToDo.ogg
Labels: status: pr: tested and approved; merge pending

#9931 Make images responsive on features page
  website/client/components/static/features.vue
Labels: status: pr: tested and approved; merge pending

#9954 replaced an outdated link //habitrpg.wikia.com
  website/common/locales/en/faq.json
Labels: status: pr: tested and approved; merge pending

#9924 Styles inputs in group modal to be consistent with rest of app #9897
  website/client/components/groups/groupPlan.vue
Labels: status: pr: tested and approved; merge pending

#9887 Attributes UI Refactoring
  website/client/assets/scss/colors.scss
  website/client/assets/scss/icon.scss
  website/client/assets/scss/popover.scss
  website/client/assets/scss/typography.scss
  website/client/components/inventory/equipment/attributesGrid.vue
  website/client/components/inventory/equipment/attributesPopover.vue
  website/client/components/inventory/equipment/equipGearModal.vue
  website/client/components/inventory/equipment/index.vue
  website/client/components/shops/buyModal.vue
  website/client/components/shops/market/equipmentAttributesGrid.vue
  website/client/components/shops/market/index.vue
  website/client/components/shops/market/sellModal.vue
  website/client/components/shops/quests/buyQuestModal.vue
  website/client/components/shops/quests/index.vue
  website/client/components/shops/seasonal/index.vue
  website/client/components/shops/timeTravelers/index.vue
  website/client/components/userMenu/profile.vue
  website/client/mixins/stats.js
  website/common/locales/en/character.json
Labels: status: pr: tested and approved; merge pending

#9775 fix dragging / modal margins
  website/client/components/inventory/items/index.vue
  website/client/components/inventory/stable/index.vue
Labels: status: pr: tested and approved; merge pending

#9824 fix user avatar transformation - change number of buffs owned when you use them - fixes #9795
  website/client/app.vue
  website/client/components/inventory/equipment/index.vue
  website/client/components/shops/buyModal.vue
  website/client/mixins/spells.js
  website/client/store/actions/user.js
  website/common/script/libs/getItemInfo.js
Labels: status: pr: tested and approved; merge pending

#9714 Refactor Purchase API - Part 1
  test/api/v3/integration/user/buy/POST-user_buy_special_spell.test.js
  test/common/ops/buy/buy.js
  test/common/ops/buy/buyArmoire.js
  test/common/ops/buy/buyGear.js
  test/common/ops/buy/buyHealthPotion.js
  test/common/ops/buy/buyMysterySet.js
  test/common/ops/buy/buyQuest.js
  test/common/ops/buy/buySpecialSpell.js
  test/common/ops/buy/hourglassPurchase.js
  test/common/ops/buy/purchase.js
  website/client/store/actions/shops.js
  website/common/script/index.js
  website/common/script/libs/getItemInfo.js
  website/common/script/ops/buy/buy.js
  website/common/script/ops/buy/buyArmoire.js
  website/common/script/ops/buy/buyGear.js
  website/common/script/ops/buy/buyHealthPotion.js
  website/common/script/ops/buy/buyMysterySet.js
  website/common/script/ops/buy/buyQuest.js
  website/common/script/ops/buy/buySpecialSpell.js
  website/common/script/ops/buy/hourglassPurchase.js
  website/common/script/ops/buy/purchase.js
  website/common/script/ops/buy/purchaseWithSpell.js
  website/common/script/ops/buySpecialSpell.js
  website/common/script/ops/index.js
  website/common/script/ops/purchaseWithSpell.js
  website/server/controllers/api-v3/user.js
Labels: status: pr: merged in develop; deploy pending

#9856 Added message when there will be no notification for group
  website/client/assets/scss/colors.scss
  website/client/components/groups/group.vue
  website/common/locales/en/groups.json
Labels: status: pr: with author: needs work

#9907 Refactored group chat flagging
  website/server/controllers/api-v3/chat.js
  website/server/libs/chat.js
  website/server/libs/chatReporting/chatReporter.js
  website/server/libs/chatReporting/chatReporterFactory.js
  website/server/libs/chatReporting/groupChatReporter.js
Labels: status: pr: with author: needs work

#9908 Refactored spell code to functions
  website/server/controllers/api-v3/user.js
Labels: status: pr: with author: needs work

#9993 Prevented of closing bailey without clicking bottom buttons
  website/client/components/achievements/newStuff.vue
Labels: status: pr: tested and approved; merge pending

#10002 Prevent closing death modal by pressing esc or clicking on backdrop
  website/client/components/achievements/death.vue
Labels: status: pr: tested and approved; merge pending

#9992 HOTFIX: purchase marketGear
  test/client/unit/specs/store/actions/shops.js
  website/client/store/actions/shops.js
Labels: status: pr: tested and approved; merge pending

#9990 Upgrade client deps
  package-lock.json
  package.json
  website/client/app.vue
Labels: status: pr: tested and approved; merge pending

#9964 Challenge small refactor
  website/server/controllers/api-v3/challenges.js
  website/server/libs/challenges/index.js
Labels: status: pr: with author: needs work

#9988 If message uuid is set as system append as user 'system message' #9985
  website/client/components/chat/copyAsTodoModal.vue
Labels: status: pr: tested and approved; merge pending

#9984 User status model: fix attributes box size being too small on Japanese
  website/client/components/userMenu/profile.vue
Labels: status: pr: tested and approved; merge pending

#9982 New PR for margins in stable - fixes #9651
  website/client/assets/scss/item.scss
  website/client/components/inventory/stable/mountItem.vue
  website/client/components/inventory/stable/petItem.vue
Labels: status: pr: tested and approved; merge pending

#9972 Replace PhantomJS with ChromeHeadless for unit test support
  .travis.yml
  package-lock.json
  package.json
  test/client/unit/karma.conf.js
  test/client/unit/specs/components/groups/membersModal.js
Labels: status: pr: tested and approved; merge pending

#9939 Partial Fix for #8735 ("Failed party invitations do not indicate which invitations failed")
  test/api/v3/integration/groups/POST-groups_invite.test.js
  website/client/app.vue
  website/common/locales/en/groups.json
  website/server/controllers/api-v3/groups.js
Labels: status: pr: merged in develop; deploy pending

#9898 Task page : task filters
  test/client/unit/specs/components/tasks/column.js
  test/client/unit/specs/libs/store/helpers/filterTasks.js
  test/client/unit/specs/libs/store/helpers/orderTasks.js
  test/client/unit/specs/store/getters/tasks/getTaskList.js
  website/client/components/tasks/column.vue
  website/client/libs/store/helpers/filterTasks.js
  website/client/libs/store/helpers/orderTasks.js
  website/client/store/getters/tasks.js
  website/client/store/getters/user.js
Labels: status: pr: merged in develop; deploy pending

#10017 Upgrade server deps
  package-lock.json
  package.json
  test/api/v3/integration/chat/POST-chat.test.js
  test/api/v3/integration/tasks/GET-tasks_user.test.js
  test/api/v3/integration/tasks/POST-tasks_clearCompletedTodos.test.js
  test/api/v3/integration/webhook/PUT-user_update_webhook.test.js
  test/api/v3/unit/libs/email.test.js
  test/api/v3/unit/libs/webhooks.test.js
  test/helpers/api-unit.helper.js
  website/client/store/actions/user.js
  website/server/controllers/api-v3/auth.js
  website/server/controllers/top-level/dataexport.js
  website/server/libs/applePayments.js
  website/server/libs/email.js
  website/server/libs/pushNotifications.js
  website/server/libs/webhook.js
  website/server/models/task.js
  website/server/models/webhook.js
Labels: status: pr: with author: needs work

#10007 Bulk spell casting
  test/api/v3/integration/user/POST-user_class_cast_spellId.test.js
  website/server/controllers/api-v3/user.js
  website/server/controllers/api-v3/user/spells.js
  website/server/libs/spells.js
Labels: status: pr: with author: needs work

#9983 task types: add new error messages for invalid task types
  website/common/locales/en/tasks.json
  website/server/controllers/api-v3/tasks.js
  website/server/controllers/api-v3/tasks/groups.js
Labels: status: pr: tested and approved; merge pending

#10039 Fixed sorting and model creation for inboxes
  website/client/components/userMenu/inbox.vue
Labels: status: pr: with author: needs work

#10043 Marked new stuff complete when clicking later
  website/client/store/actions/user.js
Labels: status: pr: with author: needs work

#10006 Updated membercount checks
  test/api/v3/unit/libs/payments/amazon/subscribe.test.js
  test/api/v3/unit/libs/payments/stripe/checkout-subscription.test.js
  website/server/libs/amazonPayments.js
  website/server/libs/stripePayments.js
  website/server/models/group.js
Labels: status: pr: with author: needs work

#10036 Added kafka queue and initial messages for delete account
  config.json.example
  package-lock.json
  package.json
  website/server/controllers/api-v3/user.js
  website/server/libs/queue/index.js
Labels: status: pr: with author: needs work
