Repository HabitRPG/habitica, pull requests merged in 2018-09, with the labels that each got.

#10640 Press kit pointer cursor
  website/client/components/static/pressKit.vue
Labels: status: pr: ready for review

#10652 fix open flag modal
  website/client/components/chat/reportFlagModal.vue
Labels: status: pr: ready for review

#10606 allow challenge leader/owner to view/join/modify challenge in private group they've left - fixes #9753
  test/api/v3/integration/challenges/GET-challenges_challengeId.test.js
  test/api/v3/integration/challenges/GET-challenges_challengeId_members.test.js
  test/api/v3/integration/challenges/POST-challenges.test.js
  test/api/v3/integration/challenges/POST-challenges_challengeId_join.test.js
  website/server/controllers/api-v3/challenges.js
  website/server/models/challenge.js
Labels: status: pr: ready for review

#10667 Correct Challenges tooltip in Guild view
  website/client/components/groups/group.vue
Labels: status: pr: tested and approved; merge pending

#10648 Fix new party member cannot join pending quest
  website/client/store/actions/quests.js
Labels: status: pr: tested and approved; merge pending

#10655 Saved sort selection into local storage for later use - fixes #10432
  website/client/components/inventory/stable/index.vue
  website/client/libs/userlocalManager.js
Labels: status: pr: tested and approved; merge pending

#10661 Fix initial position item info when selecting one item after another (fixes #10077)
  website/client/components/inventory/items/index.vue
  website/client/components/inventory/stable/index.vue
Labels: status: pr: tested and approved; merge pending

#10601 Refactor/market vue
  website/client/app.vue
  website/client/components/inventory/stable/foodItem.vue
  website/client/components/inventory/stable/index.vue
  website/client/components/shared/inventoryDrawer.vue
  website/client/components/shops/featuredItemsHeader.vue
  website/client/components/shops/index.vue
  website/client/components/shops/market/categoryItem.vue
  website/client/components/shops/market/categoryRow.vue
  website/client/components/shops/market/equipmentSection.vue
  website/client/components/shops/market/filter.vue
  website/client/components/shops/market/index.vue
  website/client/components/shops/market/sellModal.vue
  website/client/components/shops/quests/index.vue
  website/client/components/shops/seasonal/index.vue
  website/client/components/shops/timeTravelers/index.vue
  website/client/components/ui/checkbox.vue
  website/client/components/ui/countBadge.vue
  website/client/components/ui/filterDropdown.vue
  website/client/components/ui/layoutSection.vue
  website/client/components/ui/pageLayout.vue
  website/client/mixins/inventoryUtils.js
  website/client/mixins/pinUtils.js
  website/common/script/libs/shops.js
Labels: status: pr: ready for review, type: notify helpers

#10683 hotfix pinning gear
  website/client/components/shops/market/equipmentSection.vue
Labels: status: pr: tested and approved; merge pending

#10680 Fix API early Stat Point allocation
  test/api/v3/integration/user/stats/POST-user_allocate.test.js
  test/api/v3/integration/user/stats/POST-user_allocate_bulk.test.js
  test/common/libs/hasClass.test.js
  test/common/ops/stats/allocate.js
  test/common/ops/stats/allocateBulk.js
  website/client/store/getters/members.js
  website/common/locales/en/character.json
  website/common/script/index.js
  website/common/script/libs/hasClass.js
  website/common/script/ops/stats/allocate.js
  website/common/script/ops/stats/allocateBulk.js
Labels: status: pr: tested and approved; merge pending

#10709 Point links in achievement modal share buttons to home page - fixes #10675
  website/client/components/achievements/achievementFooter.vue
Labels: status: pr: tested and approved; merge pending

#10691 Animal ears after death
  website/client/components/creatorIntro.vue
  website/common/script/ops/unlock.js
Labels: status: pr: tested and approved; merge pending

#10684 Reduce margin-bottom of checklist-item from 10px to -3px (fixes #10569)
  website/client/components/tasks/task.vue
Labels: status: pr: tested and approved; merge pending
