Repository HabitRPG/habitica, pull requests merged in 2018-04, with the labels that each got.

#9868 Added initial account banned modal
  website/client/app.vue
  website/client/components/bannedAccountModal.vue
  website/common/locales/en/front.json
Labels: status: pr: ready for review

#10156 Add tooltip to character buff icon
  website/client/components/memberDetails.vue
  website/client/components/tasks/task.vue
Labels: status: pr: tested and approved; merge pending

#10221 Wrap creator icon + text in @click event
  website/client/components/creatorIntro.vue
Labels: status: pr: tested and approved; merge pending

#10227 enable hair style edit during intro
  website/client/components/creatorIntro.vue
Labels: status: pr: ready for review

#10147 increase Hourglasses and gemCapExtra promptly when multi-month subscription renews - fixes #4819
  test/api/v3/unit/libs/cron.test.js
  website/server/libs/cron.js
Labels: status: pr: ready for review, type: notify helpers

#10211 improve code and tests for banned words and slurs
  test/api/v3/integration/chat/POST-chat.test.js
  website/common/locales/en/groups.json
  website/server/controllers/api-v3/chat.js
  website/server/libs/stringUtils.js
Labels: status: pr: ready for review

#10236 adding name attribute to radio inputs
  website/client/components/tasks/taskModal.vue
Labels: priority: important, status: pr: ready for review

#10193 Added meta image for social media sharing
  website/client/index.html
  website/static/emails/images/meta-image.png
Labels: status: pr: ready for review

#10243 fix odd pet feeding behavior
  website/client/components/inventory/stable/index.vue
Labels: status: pr: merged in develop; deploy pending

#10244 Purchase API Refactoring: Quest [Gold]
  test/common/ops/buy/buyQuest.js
  website/common/script/ops/buy/abstractBuyOperation.js
  website/common/script/ops/buy/buy.js
  website/common/script/ops/buy/buyQuest.js
Labels: status: pr: merged in develop; deploy pending

#10207 Fix #10202 - Fix URL for detaching social auths
  website/client/components/settings/site.vue
Labels: status: pr: merged in develop; deploy pending

#10248 Apple pay tests
  test/api/v3/unit/libs/payments/apple.test.js
  website/server/libs/payments/apple.js
Labels: status: pr: with author: needs work

#10251 always check for the quantity
  website/common/script/ops/buy/abstractBuyOperation.js
Labels: status: pr: ready for review

#10188 moving developer-only strings to api messages
  test/api/v3/integration/payments/paypal/GET-payments_paypal_checkout_success.test.js
  test/api/v3/integration/payments/paypal/GET-payments_paypal_subscribe.test.js
  test/api/v3/integration/payments/paypal/GET-payments_paypal_subscribe_success.test.js
  test/api/v3/integration/quests/POST-groups_groupId_quests_invite.test.js
  test/api/v3/integration/user/POST-user_class_cast_spellId.test.js
  test/api/v3/integration/user/buy/POST-user_buy.test.js
  test/api/v3/integration/user/buy/POST-user_buy_gear.test.js
  test/api/v3/integration/user/buy/POST-user_buy_quest.test.js
  test/api/v3/integration/user/buy/POST-user_buy_special_spell.test.js
  test/api/v3/integration/user/stats/POST-user_allocate.test.js
  test/api/v3/integration/webhook/POST-user_add_webhook.test.js
  test/api/v3/integration/webhook/PUT-user_update_webhook.test.js
  test/api/v3/unit/models/webhook.test.js
  test/common/ops/buy/buy.js
  test/common/ops/buy/buyMarketGear.js
  test/common/ops/buy/buyMysterySet.js
  test/common/ops/buy/buyQuest.js
  test/common/ops/buy/buySpecialSpell.js
  test/common/ops/buy/hourglassPurchase.js
  test/common/ops/feed.js
  test/common/ops/hatch.js
  test/common/ops/stats/allocate.js
  test/common/ops/stats/allocateBulk.js
  website/common/locales/en/character.json
  website/common/locales/en/contrib.json
  website/common/locales/en/groups.json
  website/common/locales/en/npc.json
  website/common/locales/en/quests.json
  website/common/locales/en/spells.json
  website/common/locales/en/subscriber.json
  website/common/locales/en/tasks.json
  website/common/script/ops/buy/buy.js
  website/common/script/ops/buy/buyMarketGear.js
  website/common/script/ops/buy/buyMysterySet.js
  website/common/script/ops/buy/buyQuest.js
  website/common/script/ops/buy/buySpecialSpell.js
  website/common/script/ops/buy/hourglassPurchase.js
  website/common/script/ops/equip.js
  website/common/script/ops/feed.js
  website/common/script/ops/hatch.js
  website/common/script/ops/stats/allocate.js
  website/common/script/ops/stats/allocateBulk.js
  website/server/controllers/api-v3/challenges.js
  website/server/controllers/api-v3/chat.js
  website/server/controllers/api-v3/coupon.js
  website/server/controllers/api-v3/groups.js
  website/server/controllers/api-v3/hall.js
  website/server/controllers/api-v3/quests.js
  website/server/controllers/api-v3/tasks.js
  website/server/controllers/api-v3/tasks/groups.js
  website/server/controllers/api-v3/user/spells.js
  website/server/controllers/top-level/payments/paypal.js
  website/server/libs/apiMessages.js
  website/server/libs/chatReporting/groupChatReporter.js
  website/server/models/webhook.js
Labels: status: pr: ready for review

#10186 round priority on update too
  test/api/v3/integration/tasks/PUT-tasks_id.test.js
  website/server/controllers/api-v3/tasks.js
  website/server/libs/taskManager.js
  website/server/models/task.js
Labels: status: pr: ready for review

#10259 Stop loading user.inbox from some routes
  website/server/controllers/api-v3/hall.js
  website/server/controllers/api-v3/notifications.js
  website/server/controllers/api-v3/pushNotifications.js
  website/server/controllers/api-v3/shops.js
  website/server/controllers/api-v3/tags.js
  website/server/controllers/api-v3/webhook.js
Labels: status: pr: with author: needs work

#10192 Fix Hippo-Crite Scroll Image (Fixes #10105)
  website/client/assets/css/sprites/spritesmith-main-11.css
  website/client/assets/images/sprites/spritesmith-main-11.png
  website/raw_sprites/spritesmith/quests/scrolls/inventory_quest_scroll_hippo.png
Labels: status: pr: tested and approved; merge pending

#9703 Move Chat to Model
  migrations/groups/migrate-chat.js
  migrations/migration-runner.js
  package-lock.json
  package.json
  test/api/v3/integration/chat/DELETE-chat_id.test.js
  test/api/v3/integration/chat/GET-chat.test.js
  test/api/v3/integration/chat/POST-chat.test.js
  test/api/v3/integration/quests/POST-groups_groupId_quests_accept.test.js
  test/api/v3/integration/quests/POST-groups_groupId_quests_force-start.test.js
  test/api/v3/integration/quests/POST-groups_groupId_quests_invite.test.js
  test/api/v3/integration/quests/POST-groups_groupid_quests_abort.test.js
  test/api/v3/integration/quests/POST-groups_groupid_quests_reject.test.js
  test/api/v3/integration/user/POST-user_class_cast_spellId.test.js
  test/api/v3/unit/models/group.test.js
  website/server/controllers/api-v3/chat.js
  website/server/controllers/api-v3/groups.js
  website/server/controllers/api-v3/quests.js
  website/server/controllers/api-v3/tasks/groups.js
  website/server/controllers/api-v3/user/spells.js
  website/server/libs/chat/group-chat.js
  website/server/libs/chatReporting/groupChatReporter.js
  website/server/models/chat.js
  website/server/models/group.js
Labels: status: pr: with author: needs work, type: notify helpers

#10241 Added bulk spell queue
  website/client/libs/spellQueue.js
  website/client/mixins/spells.js
  website/client/store/actions/user.js
Labels: status: pr: with author: needs work

#10257 increase user count on home page from 2.5 to 3 million
  website/client/components/static/home.vue
  website/common/locales/en/front.json
Labels: status: pr: tested and approved; merge pending

#10212 Fix locked class-specific gear after death fixes #10025
  test/common/libs/shops.js
  website/common/script/libs/shops.js
Labels: status: pr: tested and approved; merge pending

#10263 Fix markdown
  website/client/README.md
Labels: status: pr: tested and approved; merge pending

#10266 Fix API challenges export CSV bug (Fixes #8350)
  test/api/v3/integration/challenges/GET-challenges_challengeId_export_csv.test.js
  website/server/controllers/api-v3/challenges.js
Labels: status: pr: tested and approved; merge pending

#10270 pinning mongodb container to recommended, supported version
  docker-compose.yml
Labels: status: pr: tested and approved; merge pending

#10285 Remove Incorrect Experience Notification When Leveling Up (fixes #9339)
  website/client/mixins/notifications.js
Labels: status: pr: tested and approved; merge pending

#10284 Hiding popunder if challenge data is incomplete
  test/client/README.md
  test/common/shouldDo.test.js
  test/helpers/start-server.js
  website/client/components/tasks/column.vue
  website/client/components/tasks/task.vue
  website/server/controllers/api-v3/challenges.js
  website/server/libs/taskManager.js
Labels: status: pr: merged in develop; deploy pending

#10208 Use consistent elements in footer links (fix add-on/forum link colors)
  website/client/components/appFooter.vue
Labels: status: pr: merged in develop; deploy pending

#10268 Changed Member List number in Guilds
  README.md
  website/client/components/groups/publicGuildItem.vue
Labels: status: pr: ready for review

#10265 Webhooks v2 (WIP)
  test/api/v3/integration/tasks/POST-tasks_id_score_direction.test.js
  test/api/v3/integration/tasks/checklists/POST-tasks_taskId_checklist_itemId_score.test.js
  test/api/v3/integration/user/POST-user_feed_pet_food.test.js
  test/api/v3/integration/user/POST-user_hatch_egg_hatchingPotion.test.js
  test/api/v3/integration/webhook/POST-user_add_webhook.test.js
  test/api/v3/integration/webhook/PUT-user_update_webhook.test.js
  test/api/v3/unit/libs/webhooks.test.js
  test/api/v3/unit/models/group.test.js
  test/api/v3/unit/models/webhook.test.js
  test/common/fns/updateStats.test.js
  website/common/script/fns/updateStats.js
  website/server/controllers/api-v3/tasks.js
  website/server/controllers/api-v3/user.js
  website/server/controllers/api-v3/webhook.js
  website/server/libs/webhook.js
  website/server/models/group.js
  website/server/models/user/hooks.js
  website/server/models/userNotification.js
  website/server/models/webhook.js
Labels: status: pr: with author: needs work
