Repository HabitRPG/habitica, pull requests merged in 2018-06, with the labels that each got.

#10408 fix landing page contribute and social media buttons misalignment in IE (#10373)
  website/client/components/appFooter.vue
Labels: status: pr: tested and approved; merge pending

#10412 fix size of help menu items - Fixes #10402
  website/client/components/header/menu.vue
Labels: status: pr: merged in develop; deploy pending

#10354 Modal width responsiveness (partial fix for #10267)
  website/client/app.vue
  website/client/assets/scss/modal.scss
  website/client/components/shops/quests/buyQuestModal.vue
Labels: status: pr: tested and approved; merge pending

#10438 'cloning' flag bleeding between challenge modals. Fixes issue related to #10419
  website/client/components/challenges/challengeDetail.vue
  website/client/components/challenges/challengeModal.vue
Labels: status: pr: tested and approved; merge pending

#10417 fixes #10411
  website/client/components/appFooter.vue
Labels: status: pr: tested and approved; merge pending

#10400 Match tavern sidebar UI to party and guild page changes
  website/client/components/groups/group.vue
Labels: status: pr: merged in develop; deploy pending

#10439 Report: Subscriber Task Histories
  database_reports/20180607_subscriber_histories.js
Labels: status: pr: with author: needs work

#10142 Fixes asynchronous cron bug that allows cron to run twice for a user within seconds.
  test/api/v3/unit/middlewares/cronMiddleware.js
  website/server/middlewares/cron.js
Labels: status: needs reply, status: pr: ready for review

#10377 removing the 24px top margin on .modal-dialog .title
  website/client/components/header/notifications/questInvitation.vue
  website/client/components/shops/quests/questInfo.vue
Labels: status: pr: tested and approved; merge pending

#10430 Open correct group modal from header
  website/README.md
  website/client/components/groups/group.vue
  website/client/components/header/index.vue
Labels: status: pr: merged in develop; deploy pending

#10443 Add timestamp to moderator Slack messages (fixes #10441)
  test/api/v3/unit/libs/slack.js
  website/server/libs/slack.js
Labels: status: pr: merged in develop; deploy pending

#10455 Get inbox messages route (for v4)
  test/api/v4/inbox/GET-inbox_messages.test.js
  test/api/v4/status/GET-status.test.js
  website/server/controllers/api-v4/inbox.js
  website/server/controllers/api-v4/status.js
  website/server/middlewares/appRoutes.js
Labels: status: pr: ready for review

#10442 Habits: store one history entry per day
  migrations/migration-runner.js
  migrations/tasks/habits-one-history-entry-per-day-challenges.js
  migrations/tasks/habits-one-history-entry-per-day-users.js
  test/api/v3/integration/tasks/POST-tasks_id_score_direction.test.js
  test/common/ops/scoreTask.test.js
  website/common/locales/en/tasks.json
  website/common/script/ops/scoreTask.js
  website/server/controllers/api-v3/tasks.js
  website/server/libs/preening.js
  website/server/models/task.js
  website/server/models/user/schema.js
Labels: status: pr: ready for review

#10457 Client: use api v4
  test/client/unit/specs/libs/asyncResource.js
  test/client/unit/specs/store/actions/shops.js
  test/client/unit/specs/store/actions/tasks.js
  test/client/unit/specs/store/actions/user.js
  webpack/config/index.js
  website/client/app.vue
  website/client/components/achievements/death.vue
  website/client/components/achievements/newStuff.vue
  website/client/components/appFooter.vue
  website/client/components/auth/registerLoginReset.vue
  website/client/components/challenges/challengeDetail.vue
  website/client/components/challenges/challengeMemberProgressModal.vue
  website/client/components/chat/chatCard.vue
  website/client/components/chat/chatMessages.vue
  website/client/components/creatorIntro.vue
  website/client/components/header/userDropdown.vue
  website/client/components/inventory/items/cards-modal.vue
  website/client/components/modifyInventory.vue
  website/client/components/notifications.vue
  website/client/components/payments/amazonModal.vue
  website/client/components/settings/deleteModal.vue
  website/client/components/settings/promoCode.vue
  website/client/components/settings/resetModal.vue
  website/client/components/settings/site.vue
  website/client/components/settings/subscription.vue
  website/client/components/static/newStuff.vue
  website/client/components/tasks/task.vue
  website/client/components/userMenu/profile.vue
  website/client/components/userMenu/profileStats.vue
  website/client/index.html
  website/client/mixins/payments.js
  website/client/store/actions/auth.js
  website/client/store/actions/challenges.js
  website/client/store/actions/chat.js
  website/client/store/actions/common.js
  website/client/store/actions/guilds.js
  website/client/store/actions/hall.js
  website/client/store/actions/members.js
  website/client/store/actions/notifications.js
  website/client/store/actions/party.js
  website/client/store/actions/quests.js
  website/client/store/actions/shops.js
  website/client/store/actions/tags.js
  website/client/store/actions/tasks.js
  website/client/store/actions/user.js
  website/client/store/actions/world-state.js
Labels: status: pr: ready for review

#10407 WIP Fix flicker when user mouses over the very leftmost edge of party member avatar
  test/client/unit/specs/components/memberDetails.js
  website/client/components/memberDetails.vue
Labels: status: pr: tested and approved; merge pending

#10436 added ctrl+enter to private messages #10413
  website/client/components/userMenu/inbox.vue
Labels: status: pr: tested and approved; merge pending

#10454 10282: Added code for blocking party and guild invitations from block…
  test/api/v3/integration/groups/POST-groups_invite.test.js
  website/server/controllers/api-v3/groups.js
  website/server/models/user/methods.js
Labels: status: pr: tested and approved; merge pending

#10458 Remember equipment drawer tab
  website/client/components/inventory/equipment/index.vue
  website/client/components/tasks/spells.vue
  website/client/libs/userlocalManager.js
Labels: status: pr: tested and approved; merge pending

#10459 Remove "add multiple" tip once a task has been added (fixes #10440)
  website/client/components/tasks/column.vue
Labels: status: pr: tested and approved; merge pending

#10467 Show deletion feedback for social accounts
  website/client/components/settings/deleteModal.vue
Labels: status: pr: tested and approved; merge pending

#10468 Don't timeshift Time Travelers background without Hourglass
  website/client/components/shops/timeTravelers/index.vue
Labels: status: pr: tested and approved; merge pending

#10469 Remove spurious click tracking
  website/client/components/achievements/lowHealth.vue
  website/client/components/groups/createPartyModal.vue
  website/client/components/groups/groupFormModal.vue
  website/client/components/groups/inviteModal.vue
  website/client/components/notifications.vue
Labels: status: pr: tested and approved; merge pending

#10470 Clarify Private Messages opt-in/opt-out wording
  website/client/components/userMenu/inbox.vue
  website/common/locales/en/groups.json
Labels: status: pr: tested and approved; merge pending

#10480 Ensured leader doesn't change with group plans
  website/server/controllers/api-v3/groups.js
Labels: status: pr: with author: needs work

#10476 Purchase API Refactoring: Quest [Gem]
  test/common/ops/buy/buyQuestGems.js
  test/common/ops/buy/purchase.js
  website/common/locales/en/quests.json
  website/common/script/ops/buy/abstractBuyOperation.js
  website/common/script/ops/buy/buy.js
  website/common/script/ops/buy/buyQuestGem.js
  website/common/script/ops/buy/purchase.js
Labels: status: pr: ready for review
