Repository HabitRPG/habitica, pull requests merged in 2018-08, with the labels that each got.

#10568 add participant list to collection quests
  website/client/components/groups/questSidebarSection.vue
Labels: status: pr: ready for review

#10570 Fix path to detect when group is the tavern or the user's party and set paths appropriately
  docker-compose.dev.yml
  website/client/components/chat/chatMessages.vue
  website/client/components/chat/copyAsTodoModal.vue
  website/client/components/groups/chat.vue
Labels: status: pr: merged in develop; deploy pending

#10555 Localize time for due dates and chat messages
  website/server/controllers/api-v3/i18n.js
  website/server/libs/i18n.js
Labels: status: pr: merged in develop; deploy pending

#10567 limit chat message flagging ability for new players - fixes #10069
  test/api/unit/libs/slack.js
  test/api/v3/integration/chat/POST-chat.flag.test.js
  test/api/v3/integration/chat/POST-chat.test.js
  test/api/v3/integration/chat/POST-groups_id_chat_id_clear_flags.test.js
  website/server/libs/chatReporting/groupChatReporter.js
  website/server/libs/slack.js
Labels: status: pr: ready for review

#10576 allow notification screen text to be translated
  website/client/components/header/notificationsDropdown.vue
  website/common/locales/en/generic.json
Labels: status: pr: merged in develop; deploy pending

#10565 Added context message to streak
  website/client/components/notifications.vue
Labels: status: pr: with author: needs work

#10579 Make private message character limit obvious on client
  website/client/components/userMenu/inbox.vue
Labels: status: pr: tested and approved; merge pending

#10590 Show accurate XP gain in notification on level up
  website/client/components/notifications.vue
  website/client/libs/notifications.js
Labels: status: pr: tested and approved; merge pending

#10592 improve apidocs related to allocating Stat Points and user/unlock - fixes #10557
  website/common/errors/commonErrorMessages.js
  website/server/controllers/api-v3/user.js
  website/server/controllers/api-v3/user/stats.js
Labels: status: pr: ready for review

#10566 Added mute end date
  test/api/v3/integration/chat/POST-chat.test.js
  website/client/components/hall/heroes.vue
  website/server/controllers/api-v3/chat.js
  website/server/controllers/api-v3/hall.js
  website/server/libs/chat/mute.js
  website/server/models/user/schema.js
Labels: status: pr: with author: needs work

#10602 Revert mute date
  test/api/v3/integration/chat/POST-chat.test.js
  website/client/components/hall/heroes.vue
  website/server/controllers/api-v3/chat.js
  website/server/controllers/api-v3/hall.js
  website/server/libs/chat/mute.js
  website/server/models/user/schema.js
Labels: status: pr: with author: needs work

#10594 Prevent tour from displaying twice
  website/client/mixins/guide.js
Labels: status: pr: with author: needs work

#10582 Filter dailies by due/not due in group plan and challenge page
  website/client/components/tasks/column.vue
  website/client/components/tasks/taskModal.vue
Labels: status: pr: ready for review

#10600 Add error notification for deleted user
  website/client/components/chat/chatMessages.vue
  website/common/locales/en/messages.json
Labels: status: pr: ready for review

#10603 Fixing healing light not being castable when user full hp
  test/api/v3/integration/user/POST-user_class_cast_spellId.test.js
  test/common/ops/spells.js
  website/client/mixins/spells.js
  website/common/script/content/spells.js
Labels: status: pr: merged in develop; deploy pending

#10596 Added amoire food to user immediately
  website/client/store/actions/shops.js
Labels: status: pr: with author: needs work

#10598 Fixed concurrency issues with push devices
  test/api/v3/integration/user/POST-user_push_device.test.js
  website/server/controllers/api-v3/pushNotifications.js
Labels: status: pr: with author: needs work

#10577 combine cron's Resting in the Inn code with non-sleeping code - fixes #5232 etc
  test/api/unit/libs/cron.test.js
  website/server/libs/cron.js
Labels: status: pr: ready for review

#10599 Fixed mp rounding
  website/client/mixins/notifications.js
Labels: status: pr: with author: needs work

#10608 Analytics: More / improved tracking
  website/common/script/ops/buy/abstractBuyOperation.js
  website/common/script/ops/buy/buyArmoire.js
  website/common/script/ops/buy/buyGem.js
  website/common/script/ops/buy/buyHealthPotion.js
  website/common/script/ops/buy/buyQuest.js
  website/common/script/ops/buy/buyQuestGem.js
  website/common/script/ops/buy/buySpell.js
  website/common/script/ops/buy/purchase.js
  website/server/controllers/api-v3/groups.js
  website/server/controllers/api-v3/tasks.js
  website/server/libs/cron.js
Labels: status: pr: ready for review

#10589 Correct timing on updating Group Plan member quantities
  website/server/controllers/api-v3/groups.js
Labels: status: pr: ready for review

#10614 always reload completed todos
  website/client/components/header/menu.vue
  website/client/components/tasks/column.vue
  website/client/store/actions/tasks.js
Labels: status: pr: ready for review

#10604 Added smartbanner code to suggest iphone/android apps for mobile users - fixes #9901
  package-lock.json
  package.json
  website/client/app.vue
  website/client/index.html
  website/client/main.js
Labels: status: pr: tested and approved; merge pending

#10617 Fixing misspelling and inconsistent punctuation in the api doc
  website/server/controllers/api-v3/challenges.js
  website/server/controllers/api-v3/user.js
Labels: status: pr: merged in develop; deploy pending

#10613 Created category item component
  website/client/components/shops/market/categoryItem.vue
  website/client/components/shops/market/categoryRow.vue
  website/client/components/shops/market/index.vue
Labels: status: pr: ready for review

#10636 prevent Quest progress message in Party chat when user is Resting in the Inn
  test/api/unit/models/group.test.js
  website/server/models/group.js
Labels: status: pr: merged in develop; deploy pending

#10651 Creating default encryption test to improve coverage
  test/api/unit/libs/password.test.js
Labels: status: pr: merged in develop; deploy pending

#10649 Add android FAQ answers to content call
  website/common/script/content/faq.js
Labels: status: pr: merged in develop; deploy pending

#10644 New inbox client
  test/api/v3/integration/inbox/GET-inbox_messages.test.js
  test/api/v3/integration/members/POST-send_private_message.test.js
  test/api/v3/integration/user/DELETE-user_messages.test.js
  test/api/v4/inbox/DELETE-inbox_messages_messageId.test.js
  website/client/components/chat/chatCard.vue
  website/client/components/chat/chatMessages.vue
  website/client/components/groups/group.vue
  website/client/components/userMenu/inbox.vue
  website/common/errors/apiErrorMessages.js
  website/server/controllers/api-v3/inbox.js
  website/server/controllers/api-v4/inbox.js
  website/server/libs/inbox/index.js
  website/server/libs/routes.js
  website/server/models/user/methods.js
Labels: status: pr: tested and approved; merge pending

#10624 Added Contributor Titles to Names on Hover (fixes #10611)
  website/client/components/chat/chatCard.vue
  website/common/script/libs/achievements.js
Labels: status: pr: merged in develop; deploy pending

#10610 Update member API doc (fixes #[8087])
  website/server/controllers/api-v3/members.js
Labels: status: pr: tested and approved; merge pending
