Repository HabitRPG/habitica, pull requests merged in 2018-03, with the labels that each got.

#9848 Keys kennel fixes
  test/common/ops/releaseBoth.js
  test/common/ops/releaseMounts.js
  test/common/ops/releasePets.js
  website/client/components/inventory/stable/index.vue
  website/client/components/shops/buyModal.vue
  website/client/components/shops/market/index.vue
  website/client/components/shops/market/keysToKennel.vue
  website/client/store/actions/common.js
  website/client/store/actions/shops.js
  website/common/locales/en/pets.json
  website/common/script/count.js
  website/common/script/ops/releaseBoth.js
  website/common/script/ops/releaseMounts.js
  website/common/script/ops/releasePets.js
Labels: status: pr: merged in develop; deploy pending

#10047 Don't include seasonal class gear in classless category
  website/common/script/libs/shops.js
Labels: status: pr: merged in develop; deploy pending

#10084 Set warrior as default for the choose class pop-up
  website/client/components/achievements/chooseClass.vue
Labels: status: pr: tested and approved; merge pending

#10111 fix: Quest collected items displayed multiple times.
  website/client/components/groups/questSidebarSection.vue
Labels: status: pr: tested and approved; merge pending

#10067 Stop market background from covering featured items sign
  website/client/components/shops/market/index.vue
Labels: status: pr: tested and approved; merge pending

#10085 Update user pinned items on purchasing gear
  test/common/ops/buy/buyGear.js
  website/client/store/actions/shops.js
  website/common/script/ops/buy/buyGear.js
Labels: status: pr: tested and approved; merge pending

#9870 Mongoose 5
  gulp/gulp-console.js
  package-lock.json
  package.json
  website/server/libs/setupMongoose.js
  website/server/models/challenge.js
  website/server/models/group.js
Labels: status: pr: tested and approved; merge pending

#10108 Fixing items sort by number in the market.
  website/client/components/shops/market/index.vue
Labels: status: pr: tested and approved; merge pending

#9991 Flag comment
  website/client/components/chat/reportFlagModal.vue
  website/client/store/actions/chat.js
  website/common/locales/en/groups.json
  website/server/libs/chatReporting/groupChatReporter.js
  website/server/libs/slack.js
Labels: status: pr: with author: needs work

#9835 checkout of the Inn - banner
  website/client/app.vue
  website/client/components/groups/tavern.vue
  website/client/store/actions/user.js
  website/common/locales/en/groups.json
Labels: status: pr: tested and approved; merge pending

#10099 raise coverage for user api calls
  test/api/v3/integration/user/GET-user_inAppRewards.test.js
  test/api/v3/integration/user/GET-user_toggle-pinned-item.test.js
  test/api/v3/integration/user/POST-user_class_cast_spellId.test.js
  test/api/v3/integration/user/PUT-user.test.js
Labels: status: pr: tested and approved; merge pending

#10143 fixes #10116 (this.quickAddText is null when adding a To-Do)
  website/client/components/tasks/column.vue
Labels: status: pr: tested and approved; merge pending

#10144 correct position of pets in the profile overview - fixes #10104
  website/client/assets/scss/animals.scss
  website/client/assets/scss/index.scss
  website/client/components/inventory/stable/index.vue
  website/client/components/userMenu/profile.vue
Labels: status: pr: merged in develop; deploy pending

#10145 prevent lint indent warning on multi-line reduce function
  website/common/script/fns/randomDrop.js
Labels: status: pr: merged in develop; deploy pending

#10010 Purchase API Refactoring: Market Gear
  test/common/ops/buy/buyMarketGear.js
  website/common/script/libs/errors.js
  website/common/script/ops/buy/abstractBuyOperation.js
  website/common/script/ops/buy/buy.js
  website/common/script/ops/buy/buyGear.js
  website/common/script/ops/buy/buyMarketGear.js
Labels: status: pr: ready for review

#9270 Allow Un-subscribed Users to Claim Mystery Items
  website/client/components/inventory/items/index.vue
Labels: status: pr: merged in develop; deploy pending

#9707 Fix password reset when querying for emails with upcase characters (fixes #9059)
  migrations/20171211_sanitize_emails.js
  test/api/v3/integration/user/auth/POST-register_local.test.js
  test/api/v3/integration/user/auth/PUT-user_update_email.test.js
  website/server/controllers/api-v3/auth.js
Labels: status: pr: merged in develop; deploy pending

#10034 Added margin to buttons on Settings-page
  website/client/components/settings/site.vue
Labels: status: pr: merged in develop; deploy pending

#10040 add stats.class to userStyles chat cache #10015
  website/server/models/group.js
Labels: status: pr: merged in develop; deploy pending

#10081 Add Completion Text to Older Quests #10066
  website/common/locales/en/questsContent.json
  website/common/script/content/quests.js
Labels: status: pr: merged in develop; deploy pending

#10103 Add space in profile modal to make it consistent with other text
  website/client/components/userMenu/profile.vue
Labels: status: pr: tested and approved; merge pending

#10122 fix: you are already in group message - fixes #10119
  test/api/v3/integration/groups/POST-groups_groupId_join.test.js
  website/common/locales/en/groups.json
  website/server/controllers/api-v3/groups.js
Labels: status: pr: merged in develop; deploy pending

#10128 Hide "Delete Completed" To-Dos button on Challenge or Group Task Board - fixes #9935
  website/client/components/tasks/column.vue
Labels: status: pr: tested and approved; merge pending

#10133 Stats over 3 digits overlap (fixes #10033)
  website/client/components/userMenu/profile.vue
  website/client/filters/floorWholeNumber.js
  website/client/filters/registerGlobals.js
Labels: status: pr: merged in develop; deploy pending

#10114 fix: Fixing xml data export 500 error.
  test/api/v3/integration/dataexport/GET-export_userdata.xml.test.js
  website/server/models/user/schema.js
Labels: status: pr: tested and approved; merge pending

#10095 Fixes start date updating the repeat on day for dailies repeated monthly
  website/client/components/tasks/taskModal.vue
Labels: status: pr: merged in develop; deploy pending

#10092 Escaping regex characters from user input before searching for groups.
  test/api/v3/integration/groups/GET-groups.test.js
  website/server/controllers/api-v3/groups.js
Labels: status: pr: merged in develop; deploy pending

#10091 Update the API to prevent the user from leaving a group if they are the only member and have a quest active.
  test/api/v3/integration/groups/POST-groups_groupId_join.test.js
  website/client/store/actions/guilds.js
  website/common/locales/en/messages.json
  website/server/controllers/api-v3/groups.js
Labels: status: pr: merged in develop; deploy pending

#10079 Sort challenges by habitica_official category instead of official flag
  test/api/v3/integration/challenges/GET-challenges_group_groupid.test.js
  test/api/v3/integration/challenges/GET-challenges_user.test.js
  website/server/controllers/api-v3/challenges.js
Labels: status: pr: merged in develop; deploy pending

#10107 Update Staff list in the tavern to make staff names clickable to pull up staff profiles.
  website/client/components/groups/tavern.vue
Labels: status: pr: merged in develop; deploy pending

#10053 Task page - task filters v2
  package-lock.json
  package.json
  test/client/unit/specs/components/tasks/column.js
  test/client/unit/specs/libs/store/helpers/filterTasks.js
  test/client/unit/specs/libs/store/helpers/orderTasks.js
  test/client/unit/specs/store/getters/tasks/getTasks.js
  website/client/components/tasks/column.vue
  website/client/libs/store/helpers/filterTasks.js
  website/client/libs/store/helpers/orderTasks.js
  website/client/store/getters/tasks.js
  website/client/store/getters/user.js
Labels: status: pr: with author: needs work

#10136 Added popover stats to costume equipment on profile stats - fixes #9280
  website/client/components/userMenu/profile.vue
Labels: status: pr: tested and approved; merge pending

#10167 Stringified mem report
  website/server/server.js
Labels: status: pr: with author: needs work

#10150 Added paging
  test/api/v3/integration/challenges/GET-challenges_user.test.js
  website/client/components/challenges/findChallenges.vue
  website/client/components/challenges/sidebar.vue
  website/client/store/actions/challenges.js
  website/server/controllers/api-v3/challenges.js
Labels: status: pr: with author: needs work

#10078 Prettify background overview
  website/client/components/creatorIntro.vue
  website/client/components/inventory/equipment/index.vue
  website/client/components/inventory/stable/index.vue
  website/client/components/shops/market/index.vue
  website/client/components/shops/quests/index.vue
  website/client/components/shops/seasonal/index.vue
  website/client/components/shops/timeTravelers/index.vue
  website/client/components/tasks/taskModal.vue
  website/client/components/ui/toggleSwitch.vue
Labels: status: pr: tested and approved; merge pending

#10163 consistent sizes and spacing in action buttons - fixes #9880
  website/client/components/userMenu/profile.vue
Labels: status: pr: tested and approved; merge pending

#10161 Wrap attribute cell value text
  website/client/components/inventory/equipment/attributesGrid.vue
Labels: status: pr: tested and approved; merge pending

#10126 Fix/mana bar unselected class - fix: #10026
  test/client/unit/specs/store/getters/members/hasClass.js
  website/client/components/achievements/levelUp.vue
  website/client/components/header/notificationsDropdown.vue
  website/client/components/notifications.vue
  website/client/components/settings/site.vue
  website/client/components/userMenu/profile.vue
  website/client/components/userMenu/stats.vue
  website/client/store/getters/members.js
Labels: status: pr: tested and approved; merge pending

#10120 fix: fix quest shop to not use string addition when buying quests
  test/common/ops/buy/buyQuest.js
  test/common/ops/buy/purchase.js
  website/client/components/shops/quests/buyQuestModal.vue
  website/common/locales/en/npc.json
  website/common/script/ops/buy/buyQuest.js
  website/common/script/ops/buy/purchase.js
Labels: status: pr: merged in develop; deploy pending

#10089 Quest completion modal acknowledge on close
  website/client/components/achievements/questCompleted.vue
Labels: status: pr: tested and approved; merge pending

#10086 Give MasterClasser Acheivement on completion of any of the series quests, not just the final.
  test/api/v3/unit/models/group.test.js
  website/server/models/group.js
Labels: status: pr: tested and approved; merge pending

#10082 Adding the ability for admins to revoke/reinstate chat privileges and block/unblock users from the profile page.
  website/client/components/userMenu/profile.vue
Labels: status: pr: tested and approved; merge pending

#10175 fixes #10173 - Task page search bar only searches task titles, not No…
  test/client/unit/specs/components/tasks/column.js
  website/client/components/tasks/column.vue
Labels: status: pr: tested and approved; merge pending

#10177 Move notification snackbars when resting bar is shown
  website/client/app.vue
  website/client/components/snackbars/notifications.vue
Labels: status: pr: tested and approved; merge pending

#10180 Use margin offsets for group plan header
  website/client/components/groups/groupPlan.vue
Labels: status: pr: tested and approved; merge pending

#10182 Focus title input of task modal when shown
  website/client/components/tasks/taskModal.vue
Labels: status: pr: tested and approved; merge pending

#10191 Make modal overlay transparent, not solid purple (partial fix for #10184)
  website/client/app.vue
Labels: status: pr: tested and approved; merge pending

#10197 Fix: Featured Quests label under decoration (fixes #10195)
  website/client/assets/scss/banner.scss
Labels: status: pr: tested and approved; merge pending

#9749 improves rounding for boss hp and player pending damage - partial fix for #8368
  website/client/components/groups/questSidebarSection.vue
  website/client/components/groups/tavern.vue
  website/client/filters/floor.js
  website/common/locales/en/quests.json
Labels: status: pr: tested and approved; merge pending

#10152 Purchase API Refactoring: Health Potion
  package-lock.json
  test/common/ops/buy/buyHealthPotion.js
  website/common/script/ops/buy/buy.js
  website/common/script/ops/buy/buyHealthPotion.js
Labels: status: pr: merged in develop; deploy pending

#10153 Purchase API Refactoring: Armoire
  test/common/ops/buy/buyArmoire.js
  website/common/script/ops/buy/buy.js
  website/common/script/ops/buy/buyArmoire.js
Labels: status: pr: ready for review

#10176 (fixes #9978) Remove Leader dropdown from groupFormModal
  website/client/components/groups/groupFormModal.vue
Labels: status: pr: merged in develop; deploy pending

#10181 Remove Like action from inbox chat messages
  website/client/components/chat/chatCard.vue
Labels: status: pr: ready for review

#10185 split profile.vue and profileStats.vue
  website/client/components/userMenu/profile.vue
  website/client/components/userMenu/profileStats.vue
Labels: status: pr: ready for review

#10194 prevent a muted user from inviting any player to a guild or party
  test/api/v3/integration/groups/POST-groups_invite.test.js
  website/common/locales/en/groups.json
  website/server/controllers/api-v3/groups.js
Labels: status: pr: ready for review, type: notify helpers

#10121 No Ethereal Surge on Mages
  test/api/v3/integration/user/POST-user_class_cast_spellId.test.js
  website/client/components/snackbars/notification.vue
  website/client/mixins/spells.js
  website/common/locales/en/spells.json
  website/common/script/content/spells.js
Labels: status: pr: ready for review

#10199 antidote display and functionality
  package-lock.json
  website/client/app.vue
  website/client/components/shops/buyModal.vue
  website/client/components/tasks/column.vue
  website/common/locales/en/tasks.json
  website/common/script/content/spells.js
  website/common/script/ops/buy/buyMarketGear.js
Labels: status: pr: ready for review

#10205 prevent a muted user from creating a public guild (API change)
  test/api/v3/integration/groups/POST-groups.test.js
  website/client/components/header/menu.vue
  website/common/locales/en/groups.json
  website/server/controllers/api-v3/groups.js
Labels: status: pr: ready for review, type: notify helpers

#10204 supply the correct type and path for featured Magic Hatching Potions - fixes #10135
  website/common/script/content/shop-featuredItems.js
Labels: status: pr: ready for review

#10200 Force menu links to have white color on :hover
  website/client/components/header/menu.vue
Labels: status: pr: ready for review
