Repository HabitRPG/habitica, pull requests merged in 2019-10, with the labels that each got.

#11399 Repair negative quest scrolls on (gem)purchase
  test/common/ops/buy/buyQuestGems.js
  test/common/ops/buy/buyQuestGold.js
  website/common/script/ops/buy/buy.js
  website/common/script/ops/buy/buyQuestGem.js
  website/common/script/ops/buy/buyQuestGold.js
Labels: status: pr: tested and approved; merge pending

#11403 Hall Fixes
  test/api/unit/libs/items/utils.test.js
  website/server/libs/items/utils.js
Labels: status: pr: ready for review

#11405 fix(chat): change class name because of active route
  website/client/components/chat/chatCard.vue
Labels: status: pr: ready for review

#11397 Fix dark-on-dark in quest modal tooltip (fixes #11117)
  website/client/components/shops/quests/questInfo.vue
Labels: status: pr: ready for review

#11353 Fix: Antidotes to Avatar Transformation Items should be added to Rewards by API
  test/api/v3/integration/user/GET-user_toggle-pinned-item.test.js
  test/common/libs/getDebuffPotionItems.test.js
  test/common/libs/setDebuffPotionItems.test.js
  website/client/components/tasks/column.vue
  website/common/locales/en/npc.json
  website/common/script/constants.js
  website/common/script/content/spells.js
  website/common/script/index.js
  website/common/script/libs/getDebuffPotionItems.js
  website/common/script/libs/getItemInfo.js
  website/common/script/libs/setDebuffPotionItems.js
  website/common/script/ops/pinnedGearUtils.js
  website/server/libs/cron.js
  website/server/libs/spells.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#11352 [Stlye] fix yesterdaily modal
  package-lock.json
  website/client/app.vue
  website/client/components/inventory/stable/index.vue
  website/client/components/yesterdailyModal.vue
Labels: status: pr: being tested on delta, status: pr: ready for review

#11332 Add more achievements to notifications list
  test/api/unit/models/user.test.js
  test/api/v3/integration/groups/POST-groups_groupId_join.test.js
  website/client/components/groups/group.vue
  website/client/components/notifications.vue
  website/common/locales/en/achievements.json
  website/server/controllers/api-v3/groups.js
  website/server/models/user/hooks.js
  website/server/models/userNotification.js
Labels: status: pr: ready for review

#11447 Enable Github Actions in place of Travis
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
Labels: status: pr: ready for review

#11452 Remove Vagrant
  VAGRANT.md
  Vagrantfile.example
  vagrant_scripts/install_gcc.sh
  vagrant_scripts/install_mongo.sh
  vagrant_scripts/install_node.sh
  vagrant_scripts/install_sprite_dependencies.sh
  vagrant_scripts/install_test_dependencies.sh
  vagrant_scripts/vagrant.sh
Labels: status: pr: ready for review

#11480 Intro.js Fixes and better client side logging
  website/client/src/components/creatorIntro.vue
  website/client/src/components/notifications.vue
  website/client/src/components/settings/usernameForm.vue
  website/client/src/libs/logging.js
  website/client/src/mixins/guide.js
Labels: status: pr: ready for review

#11474 Minimum password length + Static Pages fixes
  test/api/v3/integration/user/auth/POST-register_local.test.js
  test/api/v3/integration/user/auth/PUT-user_update_password.test.js
  website/client/src/assets/scss/button.scss
  website/client/src/assets/scss/form.scss
  website/client/src/components/auth/authForm.vue
  website/client/src/components/auth/registerLoginReset.vue
  website/client/src/components/static/home.vue
  website/client/src/components/static/staticWrapper.vue
  website/common/locales/en/front.json
  website/common/script/constants.js
  website/common/script/index.js
  website/server/controllers/api-v3/auth.js
  website/server/libs/auth/index.js
Labels: status: pr: being tested on delta, status: pr: ready for review
