Repository HabitRPG/habitica, pull requests merged in 2019-09, with the labels that each got.

#11321 hide "clear completed todos" while no entries are listed
  website/client/components/tasks/column.vue
Labels: status: pr: tested and approved; merge pending

#11342 Enable challenges to be closed by "End Challenge" button fix#11339
  website/client/components/members/memberSearchDropdown.vue
  website/client/mixins/challengeMemberSearch.js
Labels: status: pr: merged in develop; deploy pending

#11351 Fix clickable area on customize options while editing avatar.
  website/client/components/creatorIntro.vue
Labels: status: pr: tested and approved; merge pending

#11348 Fix: unauthorized sorting of group tasks
  website/client/components/tasks/column.vue
Labels: status: pr: tested and approved; merge pending

#11345 Fix: reset streak for habits after rebirth
  test/common/ops/rebirth.js
  website/common/script/ops/rebirth.js
Labels: status: pr: tested and approved; merge pending

#11349 Fix: Edit/deleting tasks in a challenge appears possible for people who are not admin/the creator
  website/client/components/challenges/challengeDetail.vue
  website/client/components/group-plans/taskInformation.vue
  website/client/components/tasks/column.vue
  website/client/components/tasks/task.vue
Labels: status: pr: tested and approved; merge pending

#11327 fix: decrease image height so footer is clickable
  website/client/assets/images/auth/seamless_mountains_demo.png
  website/client/components/static/staticWrapper.vue
Labels: status: pr: tested and approved; merge pending

#11324 This change prevents checklists from being toggled when casting skills or spells.
  website/client/components/tasks/task.vue
Labels: status: pr: merged in develop; deploy pending

#11330 Conversation-API: Add last message
  test/api/v4/inbox/GET-inbox-conversations.test.js
  website/server/controllers/api-v4/inbox.js
  website/server/libs/inbox/index.js
Labels: status: pr: ready for review

#11317 Fixes 2019-08-15
  website/client/components/shops/quests/questDialogDrops.vue
  website/client/components/shops/quests/questInfo.vue
  website/common/locales/en/questsContent.json
Labels: status: pr: ready for review

#11313 Pet Hatching Item Overbuy Warning
  website/client/components/shops/buyModal.vue
  website/common/locales/en/character.json
Labels: status: pr: merged in develop; deploy pending

#11338 User Icon > Edit Avatar option always links to a correct page.
  website/client/components/header/userDropdown.vue
Labels: status: pr: with author: needs work

#11361 add details to README.md for encouraging coders, describing community, etc - fixes #11328
  README.md
Labels: status: pr: ready for review

#11354 Upgrade Stripe
  package-lock.json
  package.json
  test/api/unit/libs/payments/stripe/edit-subscription.test.js
  website/server/libs/payments/stripe.js
Labels: status: pr: ready for review

#10482 Purchase API Refactoring: Mounts [Hourglass]
  test/common/ops/buy/hourglassPurchase.js
  website/common/script/ops/buy/abstractBuyOperation.js
  website/common/script/ops/buy/buy.js
  website/common/script/ops/buy/buyMount.js
Labels: status: pr: ready for review

#11301 fix(styles): improve hover effect
  website/client/components/memberDetails.vue
Labels: status: pr: being tested on delta, status: pr: ready for review

#11357 Refactoring & Feature: edit/delete controls of tasks
  test/client/unit/specs/store/getters/tasks/canDelete.js
  test/client/unit/specs/store/getters/tasks/canEdit.js
  website/client/components/challenges/challengeDetail.vue
  website/client/components/group-plans/taskInformation.vue
  website/client/components/tasks/column.vue
  website/client/components/tasks/task.vue
  website/client/store/getters/tasks.js
Labels: status: pr: ready for review

#11366 Passport upgrade
  package-lock.json
  package.json
Labels: status: pr: being tested on delta, status: pr: ready for review

#11368 load user info per conversation.id
  website/server/libs/inbox/index.js
Labels: status: pr: ready for review

#11358 HelmetJS Security Headers
  package-lock.json
  package.json
  website/server/middlewares/index.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#11241 Style fixes: Onboarding
  website/client/assets/creator/arrow.png
  website/client/assets/creator/arrow@2x.png
  website/client/assets/creator/arrow@3x.png
  website/client/assets/creator/prev.png
  website/client/assets/creator/prev@2x.png
  website/client/assets/creator/prev@3x.png
  website/client/assets/scss/colors.scss
  website/client/assets/scss/task.scss
  website/client/assets/svg/arrow_left.svg
  website/client/assets/svg/arrow_right.svg
  website/client/components/avatarModal/body-settings.vue
  website/client/components/avatarModal/customize-options.vue
  website/client/components/avatarModal/extra-settings.vue
  website/client/components/avatarModal/hair-settings.vue
  website/client/components/avatarModal/skin-settings.vue
  website/client/components/avatarModal/sub-menu.vue
  website/client/components/creatorIntro.vue
  website/client/components/tasks/column.vue
  website/client/components/tasks/task.vue
  website/client/mixins/avatarEditUtilities.js
  website/client/mixins/subPage.js
  website/client/mixins/userState.js
  website/client/store/getters/tasks.js
  website/common/locales/en/defaultTasks.json
  website/common/locales/en/generic.json
  website/common/script/content/index.js
  website/common/script/content/tasks.js
  website/server/models/task.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#11347 Teams Updates 201908
  test/api/v3/integration/groups/POST-group_remove_manager.test.js
  test/api/v3/integration/tasks/groups/GET-approvals_group_id.test.js
  test/api/v3/integration/tasks/groups/POST-tasks_group_id_assign_user_id.test.js
  test/api/v3/integration/tasks/groups/PUT-group_task_id.test.js
  test/client/unit/specs/store/getters/tasks/getTaskClasses.js
  website/client/assets/scss/button.scss
  website/client/assets/scss/task.scss
  website/client/components/group-plans/taskInformation.vue
  website/client/components/groups/group.vue
  website/client/components/header/menu.vue
  website/client/components/header/notifications/groupTaskClaimed.vue
  website/client/components/header/notificationsDropdown.vue
  website/client/components/tasks/approvalFooter.vue
  website/client/components/tasks/approvalHeader.vue
  website/client/components/tasks/task.vue
  website/client/store/getters/tasks.js
  website/common/locales/en/groups.json
  website/common/script/ops/scoreTask.js
  website/server/controllers/api-v3/tasks.js
  website/server/controllers/api-v3/tasks/groups.js
  website/server/libs/cron.js
  website/server/middlewares/auth.js
  website/server/models/group.js
  website/server/models/task.js
  website/server/models/user/schema.js
  website/server/models/userNotification.js
Labels: status: pr: merged in develop; deploy pending

#11378 Improve wording for push notifications
  website/common/locales/en/quests.json
  website/common/locales/en/settings.json
  website/server/controllers/api-v3/quests.js
  website/server/libs/inbox/index.js
  website/server/libs/pushNotifications.js
  website/server/models/group.js
Labels: status: pr: tested and approved; merge pending

#11374 load user info per conversation.id - 2nd try
  website/server/libs/inbox/index.js
Labels: status: pr: tested and approved; merge pending

#11384 Fix Purchase Background Modal on "Edit Avatar"
  website/client/components/creatorIntro.vue
  website/client/components/header/menu.vue
Labels: status: pr: ready for review

#11319 Add push notification for party activity
  website/common/locales/en/groups.json
  website/server/controllers/api-v3/chat.js
  website/server/libs/chat.js
  website/server/libs/inbox/index.js
  website/server/models/group.js
  website/server/models/user/schema.js
Labels: status: pr: with author: needs work
