Repository HabitRPG/habitica, pull requests merged in 2019-12, with the labels that each got.

#11494 Storybook Example
  website/client/.eslintrc.js
  website/client/README.md
  website/client/config/storybook/addons.js
  website/client/config/storybook/config.js
  website/client/package-lock.json
  website/client/package.json
  website/client/scripts/npm-postinstall.js
  website/client/src/components/achievements/streak.vue
  website/client/src/components/challenges/challengeDetail.vue
  website/client/src/components/ui/countBadge.stories.js
  website/server/middlewares/static.js
Labels: status: pr: ready for review

#11502 Prevent duplicate challenge tasks
  migrations/challenges/sync-all-challenges.js
  test/api/unit/models/challenge.test.js
  website/server/controllers/api-v3/challenges.js
  website/server/models/challenge.js
Labels: status: pr: tested and approved; merge pending, type: notify helpers

#11618 fix(challengeItem.vue): guild name hidden caused by the fixed height
  website/client/src/components/challenges/challengeItem.vue
Labels: status: pr: tested and approved; merge pending

#11595 Modified the sort for name to be case-insensitive, fixes #11547
  website/client/src/components/groups/membersModal.vue
Labels: status: pr: tested and approved; merge pending

#11594 APIDoc update for Tasks: fixes #10943
  website/server/controllers/api-v3/tasks.js
Labels: status: pr: merged in develop; deploy pending

#11588 Render profile tab content when profile page is loaded via url. Fixes #11525
  website/client/src/components/userMenu/profile.vue
  website/client/src/components/userMenu/profilePage.vue
Labels: status: pr: tested and approved; merge pending

#11506 Minimum password length + Static Pages fixes (was #11474)
  test/api/v3/integration/user/auth/POST-auth_reset-password-set-new-one.js
  test/api/v3/integration/user/auth/POST-register_local.test.js
  test/api/v3/integration/user/auth/PUT-user_update_password.test.js
  website/client/src/assets/scss/button.scss
  website/client/src/assets/scss/form.scss
  website/client/src/components/auth/authForm.vue
  website/client/src/components/auth/registerLoginReset.vue
  website/client/src/components/static/home.vue
  website/client/src/components/static/staticWrapper.vue
  website/common/locales/en/front.json
  website/common/script/constants.js
  website/common/script/index.js
  website/server/controllers/api-v3/auth.js
  website/server/libs/auth/index.js
Labels: status: pr: merged in develop; deploy pending

#11635 Updates notifications screen to a more consistent UI
  website/client/src/components/settings/notifications.vue
  website/common/locales/en/settings.json
Labels: status: pr: ready for review

#11614 Fixed disappearing email form bug by forcing a refresh after submission, Fixes #11565
  website/client/src/components/settings/site.vue
Labels: status: pr: ready for review

#11644 Fix Typos
  migrations/s3-upload.js
  test/api/unit/libs/analyticsService.test.js
  test/api/unit/libs/payments/payments.test.js
  test/api/v3/integration/challenges/POST-challenges.test.js
  test/api/v3/integration/groups/GET-groups_id.test.js
  test/api/v3/integration/groups/POST-groups_groupId_leave.js
  test/api/v3/integration/payments/amazon/POST-payments_amazon_checkout.test.js
  test/api/v3/integration/tasks/DELETE-tasks_id.test.js
  test/api/v3/integration/tasks/GET-tasks_id.test.js
  test/api/v3/integration/tasks/challenges/DELETE-tasks_id_challenge_challengeId.test.js
  test/api/v3/integration/user/auth/PUT-user_update_email.test.js
  test/common/libs/getDebuffPotionItems.test.js
  test/common/ops/unlock.js
  website/client/src/components/achievements/death.vue
  website/client/src/components/achievements/streak.vue
  website/client/src/components/auth/registerLoginReset.vue
  website/client/src/components/chat/chatMessages.vue
  website/client/src/components/creatorIntro.vue
  website/client/src/components/groups/membersModal.vue
  website/client/src/components/inventory/equipment/index.vue
  website/client/src/libs/logging.js
  website/client/src/mixins/spells.js
  website/client/tests/unit/components/avatar.spec.js
  website/common/locales/en_GB/gear.json
  website/common/script/cron.js
  website/common/script/ops/pinnedGearUtils.js
  website/server/controllers/api-v3/content.js
  website/server/controllers/api-v3/groups.js
  website/server/controllers/api-v3/hall.js
  website/server/controllers/api-v3/members.js
  website/server/controllers/api-v3/user.js
  website/server/controllers/top-level/dataexport.js
  website/server/libs/auth/index.js
  website/server/libs/i18n.js
  website/server/libs/taskManager.js
  website/server/middlewares/errorHandler.js
  website/server/models/challenge.js
  website/server/models/group.js
  website/server/models/user/methods.js
Labels: status: pr: ready for review

#11620 fix challenge layout
  website/client/src/components/challenges/challengeItem.vue
  website/client/src/components/challenges/findChallenges.vue
  website/client/src/components/challenges/myChallenges.vue
Labels: status: pr: being tested on delta, status: pr: ready for review, type: notify helpers
