Repository HabitRPG/habitica, pull requests merged in 2019-04, with the labels that each got.

#10832 WIP: Improve User model performances
  test/api/unit/libs/items/utils.test.js
  test/common/ops/buy/buy.js
  test/common/ops/buy/buyMarketGear.js
  test/helpers/common.helper.js
  website/common/script/content/loginIncentives.js
  website/common/script/fns/randomDrop.js
  website/common/script/fns/resetGear.js
  website/common/script/fns/ultimateGear.js
  website/common/script/fns/updateStats.js
  website/common/script/libs/statsComputed.js
  website/common/script/ops/buy/buyArmoire.js
  website/common/script/ops/buy/buyMysterySet.js
  website/common/script/ops/buy/buyQuest.js
  website/common/script/ops/buy/buyQuestGem.js
  website/common/script/ops/buy/hourglassPurchase.js
  website/common/script/ops/buy/purchase.js
  website/common/script/ops/changeClass.js
  website/common/script/ops/equip.js
  website/common/script/ops/feed.js
  website/common/script/ops/hatch.js
  website/common/script/ops/openMysteryItem.js
  website/common/script/ops/pinnedGearUtils.js
  website/common/script/ops/releaseBoth.js
  website/common/script/ops/releaseMounts.js
  website/common/script/ops/releasePets.js
  website/common/script/ops/revive.js
  website/common/script/ops/sell.js
  website/common/script/ops/unlock.js
  website/server/controllers/api-v3/auth.js
  website/server/controllers/api-v3/debug.js
  website/server/controllers/api-v3/groups.js
  website/server/controllers/api-v3/hall.js
  website/server/libs/items/utils.js
  website/server/libs/payments/groupPayments.js
  website/server/libs/payments/subscriptions.js
  website/server/models/coupon.js
  website/server/models/user/hooks.js
  website/server/models/user/schema.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#11081 Add min-width to PM for wrapping fixes #11060
  website/client/components/chat/chatMessages.vue
Labels: status: pr: ready for review

#11108 Updates classlocked gear item description
  website/common/locales/en/gear.json
Labels: status: pr: ready for review

#11065 Performance: My Challenges
  website/client/assets/scss/categories.scss
  website/client/assets/svg/official.svg
  website/client/components/challenges/challengeItem.vue
  website/client/components/challenges/findChallenges.vue
  website/client/components/challenges/myChallenges.vue
  website/client/components/userLink.vue
  website/client/mixins/challengeUtilities.js
  website/server/controllers/api-v3/challenges.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#11106 Add message of cancelled quest in party chat
  test/api/v3/integration/quests/POST-groups_groupid_quests_cancel.test.js
  website/server/controllers/api-v3/quests.js
Labels: status: pr: ready for review

#11107 Group Plans quick wins
  website/client/assets/scss/create-task.scss
  website/client/components/group-plans/index.vue
  website/client/components/group-plans/taskInformation.vue
  website/client/components/header/menu.vue
  website/client/components/header/notifications/groupTaskApproval.vue
  website/client/components/tasks/approvalFooter.vue
  website/client/components/tasks/approvalModal.vue
  website/client/components/tasks/column.vue
  website/client/components/tasks/task.vue
  website/client/components/tasks/user.vue
  website/client/mixins/sync.js
  website/common/locales/en/groups.json
  website/server/models/group.js
Labels: status: pr: ready for review

#11104 Spells Performances
  website/server/libs/spells.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#11112 Challenges: infinite scroll
  website/client/assets/scss/tiers.scss
  website/client/components/challenges/findChallenges.vue
  website/client/components/challenges/myChallenges.vue
  website/client/components/userLink.vue
  website/client/mixins/styleHelper.js
Labels: status: pr: ready for review

#11110 Inbox: Add API to list conversations
  test/api/v3/integration/inbox/GET-inbox_messages.test.js
  test/api/v4/inbox/GET-inbox-conversations.test.js
  website/server/controllers/api-v3/inbox.js
  website/server/controllers/api-v4/inbox.js
  website/server/libs/inbox/index.js
Labels: status: pr: ready for review

#11124 Fix tag text overlapping
  website/client/components/tasks/taskModal.vue
  website/client/components/tasks/user.vue
Labels: status: pr: merged in develop; deploy pending

#11123 Separate tags of different types
  website/client/components/tasks/tagsPopup.vue
Labels: status: pr: ready for review

#11136 Remove reward button for non-leader/non-admin
  website/client/components/challenges/challengeDetail.vue
  website/client/components/challenges/challengeMemberProgressModal.vue
Labels: status: pr: ready for review

#11135 Fix seasonal equipment
  website/client/components/shops/buyModal.vue
  website/client/components/shops/shopItem.vue
Labels: status: pr: merged in develop; deploy pending

#11125 Reload after rebirth
  website/client/components/achievements/rebirth.vue
  website/client/components/notifications.vue
  website/client/components/shops/buyModal.vue
Labels: status: pr: ready for review
