Repository HabitRPG/habitica, pull requests merged in 2019-01, with the labels that each got.

#10925 apidocs should say how to provide comment when flagging #10916 #10923
  website/server/controllers/api-v3/chat.js
Labels: status: pr: ready for review

#10937 confirm new password setting using enter key - fixes #10669
  website/client/components/auth/registerLoginReset.vue
Labels: status: pr: tested and approved; merge pending

#10956 Add username to challenge csv export (Fixes #10955)
  test/api/v3/integration/challenges/GET-challenges_challengeId_export_csv.test.js
  website/server/controllers/api-v3/challenges.js
Labels: status: pr: merged in develop; deploy pending

#10953 Repair negative quest scrolls on purchase
  website/common/script/ops/buy/buyQuest.js
Labels: status: pr: ready for review

#10936 Staff sweetness duplicated two handed description
  website/common/locales/bg/gear.json
  website/common/locales/cs/gear.json
  website/common/locales/da/gear.json
  website/common/locales/de/gear.json
  website/common/locales/en/gear.json
  website/common/locales/en@pirate/gear.json
  website/common/locales/en_GB/gear.json
  website/common/locales/es/gear.json
  website/common/locales/es_419/gear.json
  website/common/locales/fr/gear.json
  website/common/locales/he/gear.json
  website/common/locales/id/gear.json
  website/common/locales/it/gear.json
  website/common/locales/nl/gear.json
  website/common/locales/pl/gear.json
  website/common/locales/pt/gear.json
  website/common/locales/pt_BR/gear.json
  website/common/locales/ro/gear.json
  website/common/locales/sk/gear.json
  website/common/locales/sr/gear.json
  website/common/locales/sv/gear.json
  website/common/locales/tr/gear.json
  website/common/locales/uk/gear.json
  website/common/locales/zh/gear.json
Labels: status: pr: ready for review

#10946 Make profile modal nav tabs better responsive
  website/client/components/userMenu/profile.vue
Labels: status: pr: ready for review
