Repository HabitRPG/habitica, pull requests merged in 2019-07, with the labels that each got.

#11249 Minor fixes for apidocs and comments
  test/helpers/api-integration/v3/object-generators.js
  test/helpers/api-integration/v4/object-generators.js
  website/server/controllers/api-v3/challenges.js
  website/server/controllers/api-v3/user.js
Labels: status: pr: ready for review

#11219 Fixed small typo in API docs
  website/server/controllers/api-v3/auth.js
Labels: status: pr: ready for review

#11211 Fix plural spellings in NowDo Nudibranch quest
  website/common/locales/en/questsContent.json
Labels: status: pr: ready for review

#11214 Update "Add Task" button to diamond
  website/client/assets/scss/colors.scss
  website/client/assets/scss/create-task.scss
  website/client/components/tasks/user.vue
Labels: status: pr: ready for review

#10658 Allow admins to edit challenge tasks - fixes #8149
  test/api/v3/integration/tasks/challenges/POST-tasks_challenge_id.test.js
  website/server/controllers/api-v3/tasks.js
Labels: status: pr: ready for review, type: notify helpers

#11187 Fixed styling bug on stats profile page.
  website/client/assets/scss/popover.scss
  website/client/components/userMenu/profile.vue
  website/client/components/userMenu/profileStats.vue
Labels: status: pr: ready for review

#11230 Fix task dropdown menu overflow
  website/client/app.vue
  website/client/components/appFooter.vue
Labels: status: pr: ready for review

#11237 Removed unnecessary "Equipment" sub-heading in Market.
  website/client/components/shops/market/filter.vue
  website/client/components/shops/market/index.vue
Labels: status: pr: ready for review

#11254 Fixed removing tasks from challenges
  test/client/unit/specs/components/challenges/challengeDetail.js
  website/client/components/challenges/challengeDetail.vue
Labels: status: pr: ready for review

#11251 Ask for confirmation when buying quests
  website/client/components/shops/buyModal.vue
  website/client/components/shops/quests/buyQuestModal.vue
  website/client/mixins/buy.js
  website/common/locales/en/character.json
Labels: status: pr: ready for review

#11247 changed order of attributes in equipment views
  website/common/script/constants.js
Labels: status: pr: ready for review

#11248 improve appearance and wording in Hall's Reward User form for admins
  website/client/components/hall/heroes.vue
  website/common/locales/en/contrib.json
Labels: status: pr: ready for review

#11235 Enable keyboard shortcuts for autocomplete @username selection in chat
  website/client/components/chat/autoComplete.vue
  website/client/components/groups/chat.vue
Labels: status: pr: ready for review

#11258 Performance/inbox paging
  test/api/v3/integration/inbox/GET-inbox_messages.test.js
  test/api/v4/inbox/DELETE-inbox_messages_messageId.test.js
  test/api/v4/inbox/GET-inbox-conversations.test.js
  test/api/v4/members/POST-flag_private_message.test.js
  website/client/components/chat/chatCard.vue
  website/client/components/chat/chatMessages.vue
  website/client/components/userMenu/inbox.vue
  website/common/locales/en/generic.json
  website/server/controllers/api-v3/members.js
  website/server/controllers/api-v4/inbox.js
  website/server/libs/inbox/index.js
  website/server/models/message.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#11261 New colors updates
  website/client/assets/scss/colors.scss
  website/client/assets/scss/create-task.scss
  website/client/assets/scss/task.scss
Labels: status: pr: being tested on delta, status: pr: ready for review

#11239 add shadow-muting chat hiding feature (automatic flagging of public posts from shadow-muted players) - fixes 10851
  test/api/v3/integration/chat/POST-chat.test.js
  test/api/v3/integration/hall/PUT-hall_heores_heroId.test.js
  website/client/components/chat/chatCard.vue
  website/client/components/hall/heroes.vue
  website/client/components/userMenu/profile.vue
  website/common/script/constants.js
  website/common/script/index.js
  website/server/controllers/api-v3/chat.js
  website/server/controllers/api-v3/hall.js
  website/server/libs/slack.js
  website/server/models/group.js
  website/server/models/message.js
  website/server/models/user/schema.js
Labels: status: pr: merged in develop; deploy pending
