Repository HabitRPG/habitica, pull requests merged in 2019-11, with the labels that each got.

#11408 Fix: Preventing adding duplicated task ID to taskOrder fix for #11385
  website/server/libs/taskManager.js
Labels: status: pr: merged in develop; deploy pending

#11478 Use username in challenge member dropdown
  test/api/v3/integration/challenges/GET-challenges_challengeId_members.test.js
  website/client/src/components/members/memberSearchDropdown.vue
  website/server/controllers/api-v3/members.js
Labels: status: pr: merged in develop; deploy pending

#11459 add group by for hatchable sort
  website/client/src/components/inventory/stable/index.vue
Labels: status: pr: merged in develop; deploy pending

#11454 Docs: Fixing small typos
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status: pr: merged in develop; deploy pending

#11453 Show 0 in the gem prize box if gem prize is null
  website/client/src/components/challenges/challengeDetail.vue
  website/client/src/components/challenges/challengeItem.vue
Labels: status: pr: merged in develop; deploy pending

#11416 moved the free hairstyles to the top of the modal
  website/client/src/components/avatarModal/hair-settings.vue
Labels: status: pr: tested and approved; merge pending

#11412 Set specific subpage that is requested when profile is shown
  website/client/src/components/userMenu/profile.vue
Labels: status: pr: tested and approved; merge pending

#11409 [FIX] Challenge Creation/Edit Screen Should Not Close Except By X Button
  website/client/src/components/challenges/challengeModal.vue
Labels: status: pr: merged in develop; deploy pending

#11481 Fix market dropdownmenu default text
  website/client/src/components/ui/filterDropdown.vue
Labels: status: pr: tested and approved; merge pending

#11540 Achievements Fixes
  website/client/src/components/notifications.vue
  website/client/src/components/snackbars/notification.vue
Labels: status: pr: merged in develop; deploy pending

#11460 11457 fix(task): remove z-index
  website/client/src/components/tasks/task.vue
Labels: status: pr: ready for review

#11455 Hook up label to input for dontShowAgain checkbox
  website/client/src/components/achievements/streak.vue
Labels: status: pr: ready for review

#11479 Allow update webhook label with an empty string
  test/api/v3/integration/webhook/PUT-user_update_webhook.test.js
  website/server/controllers/api-v3/webhook.js
Labels: status: pr: ready for review

#11493 fix padding on various pages
  website/client/src/components/groups/group.vue
  website/client/src/components/groups/tavern.vue
  website/client/src/components/tasks/user.vue
Labels: status: pr: ready for review

#11505 Fixes #11297 (user ID is b762e018-642b-4b78-a735-354a52c0a905)
  website/common/script/libs/isFreeRebirth.js
Labels: status: pr: ready for review

#11538 Make hatching modal height adjust automatically to dialog text length (fixes #10232)
  website/client/src/components/inventory/stable/hatchingModal.vue
Labels: status: pr: ready for review

#11521 Redirect user to 'Discover Challenges' page on loading an inaccessible challenge. Fixes #11420
  website/client/src/components/challenges/challengeDetail.vue
Labels: status: pr: ready for review

#11513 updated tier styles so that they maintain their color on hover and click
  website/client/src/assets/scss/tiers.scss
Labels: status: pr: ready for review

#11418 Refactoring & Fix: editing group and challenges from user dashboard
  website/client/src/components/challenges/challengeDetail.vue
  website/client/src/components/group-plans/taskInformation.vue
  website/client/src/components/tasks/column.vue
  website/client/src/components/tasks/task.vue
  website/client/src/store/getters/tasks.js
  website/client/tests/unit/store/getters/tasks/canDelete.spec.js
  website/client/tests/unit/store/getters/tasks/canEdit.spec.js
Labels: status: pr: ready for review

#11567 Use new indexes in GDPR script
  scripts/gdpr-delete-users.js
Labels: status: pr: merged in develop; deploy pending

#11562 Better promise handling for bulk emailing
  migrations/users/bulk-email.js
  website/server/libs/email.js
Labels: status: pr: ready for review

#11539 Avatar Edit Modal: addtional none options
  website/client/src/components/avatarModal/extra-settings.vue
Labels: status: pr: ready for review

#11564 Force reward value to 0 when empty field
  website/client/src/components/tasks/taskModal.vue
Labels: status: pr: ready for review

#11546 Update rebirth purchase modal text to reference group plans (fixes #8834)
  website/common/locales/en/rebirth.json
Labels: status: pr: ready for review

#11542 update members list and count when joining or leaving challenge
  website/client/src/components/challenges/challengeDetail.vue
  website/client/src/components/challenges/leaveChallengeModal.vue
Labels: status: pr: ready for review

#11519 Award mystery items at cron
  test/api/unit/libs/cron.test.js
  test/api/unit/libs/payments/payments.test.js
  website/common/locales/en/generic.json
  website/common/script/content/mystery-sets.js
  website/common/script/content/time-travelers.js
  website/server/libs/cron.js
  website/server/libs/payments/subscriptions.js
Labels: status: pr: ready for review

#11518 Fixing build issues with Dockerfile-Dev, fixes #11498
  .dockerignore
  Dockerfile-Dev
Labels: status: pr: merged in develop; deploy pending

#11507 Improvements and fixes for push notifications
  package-lock.json
  package.json
  test/api/unit/models/group.test.js
  test/api/v3/integration/members/POST-send_private_message.test.js
  website/server/libs/chat.js
  website/server/libs/inbox/index.js
  website/server/models/group.js
  website/server/models/message.js
Labels: status: pr: ready for review

#11548 remain on party invites tab after removing invite - fixes #11523
  website/client/src/components/groups/membersModal.vue
Labels: status: pr: ready for review

#11591 Fix edit challenge twice bug
  website/client/src/components/challenges/challengeModal.vue
Labels: status: pr: ready for review
