Repository HabitRPG/habitica, pull requests merged in 2019-08, with the labels that each got.

#11312 Remove coveralls (but not coverage)
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: status: pr: ready for review

#11307 Always send push notifications in recipients language
  website/server/controllers/api-v3/quests.js
  website/server/libs/inbox/index.js
  website/server/libs/invites/index.js
  website/server/models/challenge.js
  website/server/models/group.js
Labels: status: pr: tested and approved; merge pending

#11285 Change 404 page contact link to Bug Guild fixes #11284
  website/client/components/404.vue
Labels: status: pr: tested and approved; merge pending

#11252 Add audio theme demo button
  website/client/components/settings/site.vue
  website/client/libs/sounds.js
  website/common/locales/en/generic.json
Labels: status: pr: tested and approved; merge pending

#11250 Only includes backticks if they haven't been already included. Fixes …
  website/server/libs/chat/group-chat.js
Labels: status: pr: tested and approved; merge pending

#11306 Add translated gear name to open-mystery-item call
  test/api/v3/integration/user/POST-user_open_mystery_item.test.js
  test/common/ops/openMysteryItem.js
  website/common/script/ops/openMysteryItem.js
Labels: status: pr: with author: needs work

#11281 Make usernames clickable in Hall of Heroes Fixes #11014
  website/client/components/hall/heroes.vue
Labels: status: pr: ready for review

#11149 Node 12
  .nvmrc
  .travis.yml
  Dockerfile
  Dockerfile-Dev
  package-lock.json
  package.json
  test/client/.babelrc
  webpack/webpack.base.conf.js
  website/server/models/task.js
Labels: status: pr: merged in develop; deploy pending
