Repository HabitRPG/habitica, pull requests merged in 2019-05, with the labels that each got.

#11147 fix loading owned messages
  website/server/controllers/api-v3/challenges.js
Labels: status: pr: ready for review

#11169 change "Load Tools" profile icon that mods and staff use from pencil to crown
  website/client/components/userMenu/profile.vue
Labels: status: pr: ready for review

#11150 Remove markdown elements from PM
  website/client/components/userMenu/inbox.vue
Labels: status: pr: being tested on delta, status: pr: ready for review

#11183 hides item count in quest sidebar section for non-participants - Fixes #11168
  website/client/components/groups/questSidebarSection.vue
Labels: status: pr: ready for review

#11167 Task notes now disappear when they are deleted from the main task. Fix #11152
  website/client/directives/markdown.js
Labels: status: pr: ready for review

#11165 Docker setup for development
  Dockerfile-Dev
  docker-compose.dev.yml
Labels: status: pr: ready for review

#11170 Party Chat Translations (Continuation of #10019)
  test/api/unit/middlewares/auth.test.js
  test/api/unit/models/group.test.js
  test/api/v3/integration/quests/POST-groups_groupid_quests_abort.test.js
  test/api/v3/integration/quests/POST-groups_groupid_quests_cancel.test.js
  test/helpers/api-unit.helper.js
  test/helpers/translate.js
  website/common/locales/en/character.json
  website/common/locales/en/quests.json
  website/server/controllers/api-v3/challenges.js
  website/server/controllers/api-v3/chat.js
  website/server/controllers/api-v3/groups.js
  website/server/controllers/api-v3/quests.js
  website/server/controllers/api-v3/tasks.js
  website/server/controllers/api-v3/tasks/groups.js
  website/server/libs/chat/group-chat.js
  website/server/libs/spells.js
  website/server/middlewares/auth.js
  website/server/models/group.js
  website/server/models/message.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#11178 adjust error messages for muted and banned users, and system flagging error
  test/api/v3/integration/groups/POST-groups.test.js
  test/api/v3/integration/groups/POST-groups_invite.test.js
  website/client/components/userMenu/inbox.vue
  website/common/locales/en/front.json
  website/common/locales/en/groups.json
  website/common/locales/en/messages.json
  website/server/controllers/api-v3/groups.js
Labels: status: pr: merged in develop; deploy pending

#10865 Add text alternatives for navbar items
  website/client/components/header/menu.vue
  website/client/components/header/notificationsDropdown.vue
  website/client/components/header/userDropdown.vue
  website/client/components/ui/customMenuDropdown.vue
Labels: status: pr: being tested on delta, status: pr: ready for review

#11196 Remove default color in Instagram icon
  website/client/assets/svg/instagram.svg
Labels: status: pr: merged in develop; deploy pending

#11158 Add chevron buttons to sub-items in the menu
  website/client/assets/svg/chevron-down.svg
  website/client/components/header/menu.vue
Labels: status: pr: being tested on delta, status: pr: ready for review
