Repository HabitRPG/habitica, pull requests merged in 2019-03, with the labels that each got.

#11032 Ensure profile page gets synced (fixes #11026)
  website/client/components/userMenu/profile.vue
Labels: status: pr: tested and approved; merge pending

#10995 quest info tooltip - resize label to content
  website/client/components/shops/quests/questInfo.vue
Labels: status: pr: ready for review

#11022 Footer Design / Instagram Link
  website/client/components/appFooter.vue
  website/common/locales/en/front.json
Labels: status: pr: ready for review

#11023 refactor filters to work like in guilds/challenges
  website/client/components/inventory/equipment/index.vue
  website/client/components/inventory/items/index.vue
  website/client/components/inventory/stable/index.vue
Labels: status: pr: ready for review

#11036 fixes Tasks UI
  website/client/components/tasks/column.vue
  website/client/components/tasks/task.vue
  website/client/components/tasks/user.vue
  website/common/locales/en/generic.json
Labels: status: pr: ready for review

#11039 Keep mystery items synced with server (fixes #11029)
  website/client/components/inventory/items/index.vue
  website/client/store/actions/user.js
Labels: status: pr: ready for review

#11041 Fix mismatch between pet and star badge
  website/client/components/inventory/stable/index.vue
Labels: status: pr: ready for review

#11013 fix header design
  website/client/components/memberDetails.vue
  website/client/components/ui/statsbar.vue
  website/client/components/userMenu/profile.vue
Labels: status: pr: ready for review

#11046 fix: shop ui
  website/client/assets/svg/difficulty-star-empty.svg
  website/client/assets/svg/difficulty-star-half.svg
  website/client/assets/svg/difficulty-star.svg
  website/client/components/shops/market/equipmentSection.vue
  website/client/components/shops/market/index.vue
  website/client/components/shops/quests/index.vue
  website/client/components/shops/quests/questInfo.vue
  website/client/components/shops/seasonal/index.vue
  website/client/components/shops/timeTravelers/index.vue
  website/client/components/ui/countBadge.vue
Labels: status: pr: ready for review

#11056 fix tavern/chat ui
  website/client/components/groups/chat.vue
  website/client/components/groups/communityGuidelines.vue
  website/client/components/groups/group.vue
  website/client/components/groups/publicGuildItem.vue
Labels: status: pr: ready for review

#11070 extending equipment modal hack to address #11015
  website/client/components/inventory/equipment/equipGearModal.vue
Labels: status: pr: tested and approved; merge pending

#11068 allow moderators/staff to always see Report button for a flagged message
  website/client/components/chat/chatCard.vue
Labels: section: Guilds, section: Tavern Chat, status: pr: tested and approved; merge pending

#11061 Second empty head option was removed from edit avatar - hair - style
  website/client/components/creatorIntro.vue
Labels: status: pr: tested and approved; merge pending

#11053 Center allocatable stat points
  website/client/components/userMenu/profileStats.vue
Labels: status: pr: tested and approved; merge pending

#11044 Fix sellModal data caching
  website/client/components/shops/market/sellModal.vue
Labels: status: pr: tested and approved; merge pending

#10978 catch promise rejection when user submits a message to group. fixes #10970
  website/client/components/groups/chat.vue
Labels: status: pr: tested and approved; merge pending

#10988 Set registered platform on analytics only once
  website/server/libs/analyticsService.js
Labels: status: pr: merged in develop; deploy pending

#11069 Fixes #11047 Hall search case insensitive
  test/api/v3/integration/hall/GET-hall_heroes_heroId.test.js
  test/helpers/api-integration/v3/object-generators.js
  website/server/controllers/api-v3/hall.js
Labels: status: pr: ready for review

#11064 Added a highlight on today's date in To-Dos cal
  website/client/assets/scss/datepicker.scss
  website/client/assets/scss/index.scss
  website/client/components/tasks/taskModal.vue
Labels: status: pr: merged in develop; deploy pending

#11078 Fixes #11062 Display information message when social authentication account uses password to login
  test/api/v3/integration/user/auth/POST-login-local.test.js
  test/helpers/api-integration/api-classes.js
  test/helpers/mongo.js
  website/common/locales/en/front.json
  website/server/controllers/api-v3/auth.js
Labels: status: pr: ready for review

#10819 Add <button> and focus styles for keyboard users
  website/client/assets/scss/task.scss
  website/client/components/header/menu.vue
  website/client/components/shops/shopItem.vue
  website/client/components/snackbars/notification.vue
  website/client/components/tasks/task.vue
  website/client/components/ui/customMenuDropdown.vue
Labels: status: pr: ready for review

#11031 Multiple checks for pinnedItems
  test/common/libs/inAppRewards.js
  test/common/ops/pinnedGearUtils.js
  website/client/components/ui/drawer.vue
  website/client/store/actions/shops.js
  website/common/script/libs/inAppRewards.js
  website/common/script/libs/shops.js
  website/common/script/ops/pinnedGearUtils.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#11077 performance: private messages - API
  test/api/v3/integration/inbox/GET-inbox_messages.test.js
  website/server/controllers/api-v3/inbox.js
  website/server/controllers/api-v3/user.js
  website/server/controllers/top-level/dataexport.js
  website/server/libs/inbox/index.js
  website/server/models/user/methods.js
Labels: status: pr: ready for review
