Repository HabitRPG/habitica, pull requests merged in 2020-08, with the labels that each got.

#12422 Fix multiple purchases with Amazon Pay
  website/client/src/components/payments/amazonButton.vue
  website/client/src/components/payments/amazonModal.vue
  website/client/src/mixins/payments.js
Labels: status: pr: ready for review

#12404 Casting Chilling Frost and Stealth skill again will not be processed and return an error instead. Fixes #12361.
  test/api/v3/integration/user/POST-user_class_cast_spellId.test.js
  test/common/ops/spells.js
  website/client/src/components/tasks/spells.vue
  website/common/locales/en/spells.json
  website/common/script/content/spells.js
  website/server/libs/spells.js
Labels: status: pr: ready for review

#12358 update group members after accepting the quest (without page reload)
  website/client/src/components/groups/questSidebarSection.vue
Labels: status: pr: ready for review

#12446 fix(quest shop): add an index to stars v-for loop
  website/client/src/components/shops/quests/questInfo.vue
Labels: status: pr: merged in develop; deploy pending

#12418 UI: redesign DatePicker
  package-lock.json
  website/client/config/storybook/config.js
  website/client/package-lock.json
  website/client/package.json
  website/client/src/assets/scss/datepicker.scss
  website/client/src/assets/scss/index.scss
  website/client/src/components/tasks/taskModal.vue
  website/client/src/components/ui/datepicker.stories.js
  website/client/src/components/ui/datepicker.vue
  website/common/locales/en/tasks.json
Labels: status: pr: being tested on delta, status: pr: ready for review

#12443 Two Teams fixes
  website/client/src/components/tasks/approvalFooter.vue
  website/client/src/components/tasks/modal-controls/selectMulti.vue
  website/client/src/components/tasks/taskModal.vue
  website/server/controllers/api-v3/tasks/groups.js
Labels: status: pr: tested and approved; merge pending

#12423 Modals: remove stack
  website/client/src/app.vue
  website/client/src/components/achievements/firstDrops.vue
  website/client/src/components/challenges/challengeModal.vue
  website/client/src/components/challenges/closeChallengeModal.vue
  website/client/src/components/payments/buyGemsModal.vue
  website/client/src/components/payments/selectUserModal.vue
  website/client/src/components/payments/sendGemsModal.vue
  website/client/src/components/payments/successModal.vue
  website/client/src/pages/private-messages.vue
Labels: status: pr: being tested on delta, status: pr: ready for review

#12440 Added bannedWordsAllowed attribute to Group attributes (Partial fix for #12405)
  website/server/models/group.js
Labels: status: pr: ready for review

#12438 Remove Tavern from API v3 list of guilds when 'guild' or 'publicGuilds' type parameter get added. (Fixes #12407)
  test/api/v3/integration/groups/GET-groups.test.js
  website/server/models/group.js
Labels: status: pr: ready for review

#12484 Update iOS FAQ
  website/common/locales/en/faq.json
Labels: status: pr: ready for review

#12439 Scheduling summary line for team Dailies and To Do's
  website/client/src/components/tasks/taskModal.vue
Labels: status: pr: merged in develop; deploy pending

#12488 fix some lint warnings
  website/client/src/components/achievements/chooseClass.vue
  website/client/src/components/appFooter.vue
  website/client/src/components/auth/authForm.vue
  website/client/src/components/auth/registerLoginReset.vue
  website/client/src/components/challenges/challengeModal.vue
  website/client/src/components/challenges/closeChallengeModal.vue
  website/client/src/components/chat/chatCard.vue
  website/client/src/components/groups/group.vue
  website/client/src/components/groups/groupFormModal.vue
  website/client/src/components/groups/membersModal.vue
  website/client/src/components/groups/publicGuildItem.vue
  website/client/src/components/groups/questDetailsModal.vue
  website/client/src/components/groups/questSidebarSection.vue
  website/client/src/components/header/index.vue
  website/client/src/components/header/notifications/groupTaskApproval.vue
  website/client/src/components/header/notifications/guildInvitation.vue
  website/client/src/components/header/notifications/partyInvitation.vue
  website/client/src/components/messages/conversationItem.vue
  website/client/src/components/messages/messageCard.vue
  website/client/src/components/messages/messageList.vue
  website/client/src/components/payments/amazonButton.vue
  website/client/src/components/payments/amazonModal.vue
  website/client/src/components/settings/site.vue
  website/client/src/components/shops/buyModal.vue
  website/client/src/components/shops/market/keysToKennel.vue
  website/client/src/components/tasks/approvalFooter.vue
  website/client/src/components/tasks/approvalModal.vue
  website/client/src/components/tasks/brokenTaskModal.vue
  website/client/src/components/tasks/clearCompletedTodos.vue
  website/client/src/components/tasks/task.vue
  website/client/src/components/tasks/taskModal.vue
  website/client/src/components/ui/datepicker.vue
  website/client/src/mixins/avatarEditUtilities.js
  website/client/src/mixins/buy.js
  website/client/src/mixins/payments.js
  website/client/src/pages/private-messages.vue
  website/client/src/store/actions/guilds.js
Labels: status: pr: ready for review

#12486 issue(11266) - Restyle level-up modal with sparkles
  website/client/config/storybook/config.js
  website/client/src/assets/scss/modal.scss
  website/client/src/assets/svg/sparkles-left.svg
  website/client/src/assets/svg/star-group.svg
  website/client/src/components/achievements/levelUp.vue
  website/client/src/components/inventory/stable/hatchedPetDialog.vue
  website/client/src/components/notifications.vue
  website/client/src/components/tasks/taskModal.vue
  website/client/tests/unit/components/achievements/levelUp.spec.js
  website/common/locales/en/achievements.json
Labels: status: pr: merged in develop; deploy pending

#12480 datepicker: add clear button
  website/client/src/components/tasks/taskModal.vue
  website/client/src/components/ui/datepicker.vue
Labels: status: pr: being tested on delta, status: pr: ready for review
