Repository HabitRPG/habitica, pull requests merged in 2020-04, with the labels that each got.

#12037 Automatically Logout Banned Users
  test/api/unit/libs/language.test.js
  test/api/unit/middlewares/analytics.test.js
  test/api/unit/middlewares/cronMiddleware.js
  test/api/unit/middlewares/language.test.js
  website/client/src/app.vue
  website/client/src/store/actions/auth.js
  website/server/controllers/top-level/auth.js
  website/server/libs/i18n.js
  website/server/libs/language.js
  website/server/middlewares/auth.js
  website/server/middlewares/language.js
Labels: status: pr: ready for review, status: pr: tested and approved; merge pending

#12038 Misc Webhooks Fixes
  migrations/archive/2020/20200402_webhooks_add_protocol.js
  migrations/archive/2020/20200402_webhooks_reenable.js
  package-lock.json
  package.json
  test/api/unit/libs/email.test.js
  test/api/unit/libs/webhooks.test.js
  website/server/libs/email.js
  website/server/libs/webhook.js
  website/server/models/webhook.js
Labels: status: pr: ready for review, status: pr: tested and approved; merge pending

#12045 Removed an unnecessary word in quest completion text
  website/common/locales/en/questsContent.json
Labels: status: pr: ready for review

#12016 stop 'pts' from overflowing to next line
  website/client/src/components/userMenu/profileStats.vue
Labels: status: pr: ready for review

#11793 Sign in with Apple
  .gitignore
  .nodemonignore
  config.json.example
  package-lock.json
  package.json
  test/api/unit/libs/email.test.js
  test/api/v3/integration/user/DELETE-user.test.js
  test/api/v3/integration/user/auth/DELETE-user_auth_social_network.test.js
  test/api/v3/integration/user/auth/GET-user_auth_apple.test.js
  test/api/v3/integration/user/auth/POST-register_local.test.js
  test/api/v3/integration/user/auth/POST-user_auth_social.test.js
  test/api/v4/user/auth/POST-register_local.test.js
  website/client/src/assets/svg/apple.svg
  website/client/src/assets/svg/apple_black.svg
  website/client/src/components/auth/authForm.vue
  website/client/src/components/auth/registerLoginReset.vue
  website/client/src/components/settings/site.vue
  website/client/src/components/static/appleRedirect.vue
  website/client/src/components/static/home.vue
  website/client/src/libs/auth.js
  website/client/src/router/index.js
  website/client/src/store/actions/auth.js
  website/client/vue.config.js
  website/common/script/constants.js
  website/server/controllers/api-v3/auth.js
  website/server/libs/auth/apple.js
  website/server/libs/auth/social.js
  website/server/libs/auth/utils.js
  website/server/models/user/schema.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#12019 Push Notifications Improvements
  test/api/unit/libs/pushNotifications.js
  test/api/unit/libs/webhooks.test.js
  website/server/libs/pushNotifications.js
Labels: status: pr: merged in develop; deploy pending

#12068 Onboarding Guide UI Fixes
  website/client/src/assets/scss/icon.scss
  website/client/src/components/achievements/onboardingComplete.vue
  website/client/src/components/header/notifications/onboardingComplete.vue
  website/client/src/components/header/onboardingGuide.vue
  website/client/src/components/userMenu/profile.vue
  website/common/locales/en/achievements.json
Labels: status: pr: ready for review

#12063 Removed loading screen tips, fixes #11834
  website/client/src/app.vue
  website/common/locales/en/loadingScreenTips.json
Labels: status: pr: ready for review, type: notify helpers

#11905 API-v4 route added: 'api/v4/faq' fixes #11801
  gulp/gulp-content.js
  test/api/unit/libs/content.test.js
  test/api/unit/libs/localizeContentData.js
  test/api/v4/faq/GET-faq.test.js
  website/common/script/errors/apiErrorMessages.js
  website/server/controllers/api-v3/content.js
  website/server/controllers/api-v4/faq.js
  website/server/libs/content.js
Labels: status: pr: ready for review

#12092 Push Notifications Fixes - Part 2
  website/client/src/components/shops/quests/index.vue
  website/server/libs/chat.js
  website/server/libs/inbox/index.js
  website/server/libs/payments/gems.js
  website/server/libs/payments/subscriptions.js
  website/server/libs/pushNotifications.js
  website/server/models/challenge.js
  website/server/models/group.js
Labels: status: pr: ready for review

#12071 Fixes issue where usernames that are sandwiched with underscores are not properly formatted [fixes #12033]
  website/client/src/libs/highlightUsers.js
  website/client/tests/unit/libs/highlightUsers.spec.js
Labels: status: pr: ready for review

#12069 Don't link user in markdown code blocks - Fixes #[11504]
  test/api/unit/libs/highlightMentions.test.js
  website/server/controllers/api-v3/chat.js
  website/server/controllers/api-v3/members.js
  website/server/libs/highlightMentions.js
Labels: status: pr: ready for review

#12094 Delete merch page [fixes #12039]
  website/client/src/components/appFooter.vue
  website/client/src/components/static/merch.vue
  website/client/src/router/index.js
Labels: status: pr: ready for review

#12090 Handle simultaneous quest accept/reject
  test/api/v3/integration/quests/POST-groups_groupId_quests_accept.test.js
  website/server/controllers/api-v3/quests.js
  website/server/models/group.js
Labels: status: pr: ready for review

#12044 remove search from private-messages
  website/client/package.json
  website/client/src/components/messages/messageList.vue
  website/client/src/pages/private-messages.vue
  website/server/controllers/api-v4/inbox.js
  website/server/libs/inbox/conversation.methods.js
  website/server/libs/inbox/index.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#12108 Update year number on the footer component
  website/client/src/components/appFooter.vue
Labels: status: pr: ready for review

#11993 Fixing the equipment popover message when equipment is from a different class - Fixes #11988
  website/client/src/components/inventory/equipment/attributesPopover.vue
Labels: status: pr: ready for review

#12095 Allow changing name of party without adding description
  website/client/src/components/groups/groupFormModal.vue
Labels: status: pr: ready for review

#12106 Fixes #11119: Added check for wacky pet before feeding
  test/common/ops/feed.js
  website/common/script/ops/feed.js
Labels: status: pr: ready for review

#12098 Collection quests: make sure users cannot earn "excess" items
  test/api/unit/models/group.test.js
  website/server/models/group.js
Labels: status: pr: ready for review

#12034 cancelSubscription function is no longer called twice when user leaves group fixes #11664
  test/api/unit/libs/payments/stripe/calculate-termination-date.test.js
  test/api/unit/models/group.test.js
  test/api/v3/integration/groups/POST-groups_groupId_leave.test.js
  test/helpers/api-integration/v3/object-generators.js
  website/server/controllers/api-v3/groups.js
  website/server/libs/chat/group-chat.js
  website/server/libs/invites/index.js
  website/server/libs/payments/subscriptions.js
  website/server/libs/payments/util.js
  website/server/models/group.js
  website/server/models/user/methods.js
Labels: status: pr: merged in develop; deploy pending

#12116 Don't bill (subtract gems) multiple times for multiple unlock item set calls
  package.json
  test/api/v3/integration/user/POST-user_unlock.js
  test/common/ops/unlock.js
  website/client/package-lock.json
  website/client/src/components/messages/messageList.vue
  website/client/src/pages/private-messages.vue
  website/common/script/ops/unlock.js
Labels: status: pr: merged in develop; deploy pending

#12140 Issue 12138 - Fix chat support for regex chars in code blocks
  test/api/unit/libs/highlightMentions.test.js
  website/server/libs/highlightMentions.js
Labels: status: pr: ready for review

#12125 Fix tasks draggable on mobile
  website/client/src/components/tasks/column.vue
Labels: status: pr: ready for review

#12145 Update LICENSE
  LICENSE
Labels: status: pr: ready for review

#12115 Fix group Send Invites button
  website/client/src/components/groups/inviteModal.vue
Labels: status: pr: with author: needs work
