Repository HabitRPG/habitica, pull requests merged in 2020-01, with the labels that each got.

#11686 Prevent accidentally closing tasks in edit mode. #9262
  website/client/src/components/tasks/taskModal.vue
Labels: status: pr: ready for review, status: pr: tested and approved; merge pending

#11690 Disabled auto notification dismissal for received card on click fix for #11688
  website/client/src/components/header/notifications/cardReceived.vue
Labels: status: pr: ready for review, status: pr: tested and approved; merge pending

#11706 Set the default year for the background meny to 2020 Fix for #11703
  website/client/src/components/header/userDropdown.vue
Labels: status: pr: merged in develop; deploy pending

#11637 Trigger vue reactivity for user
  website/client/src/store/actions/shops.js
  website/common/script/content/loginIncentives.js
  website/common/script/fns/randomDrop.js
  website/common/script/fns/updateStats.js
  website/common/script/ops/buy/buyArmoire.js
  website/common/script/ops/buy/buyMount.js
  website/common/script/ops/buy/buyMysterySet.js
  website/common/script/ops/buy/buyQuestGem.js
  website/common/script/ops/buy/buyQuestGold.js
  website/common/script/ops/buy/hourglassPurchase.js
  website/common/script/ops/buy/purchase.js
  website/common/script/ops/changeClass.js
  website/common/script/ops/feed.js
  website/common/script/ops/hatch.js
  website/common/script/ops/openMysteryItem.js
  website/common/script/ops/pinnedGearUtils.js
  website/common/script/ops/revive.js
Labels: status: pr: merged in develop; deploy pending

#11665 show Reset Flag Count button to moderators regardless of post's report status
  website/client/src/components/chat/reportFlagModal.vue
Labels: status: pr: ready for review

#11707 Quest invitation webhook
  test/api/unit/libs/webhooks.test.js
  test/api/unit/models/webhook.test.js
  test/api/v3/integration/quests/POST-groups_groupId_quests_invite.test.js
  test/api/v3/integration/webhook/POST-user_add_webhook.test.js
  website/server/controllers/api-v3/quests.js
  website/server/controllers/api-v3/webhook.js
  website/server/models/webhook.js
Labels: status: pr: ready for review

#11683 Fix issues with local Docker development.
  Dockerfile-Dev
  docker-compose.dev.yml
  website/client/vue.config.js
Labels: status: pr: ready for review

#11663 fix bug in which editing challenge will not allow editing categories (fixes #11662)
  website/client/src/components/challenges/challengeModal.vue
Labels: status: pr: ready for review

#11636 Fix incorrect error when sending private messages to a player you have blocked (fixes #11612)
  test/api/v3/integration/members/POST-send_private_message.test.js
  test/api/v3/integration/members/POST-transfer_gems.test.js
  website/common/locales/en/groups.json
  website/server/models/user/methods.js
Labels: status: pr: ready for review

#11741 fix style textarea + added story for an overview
  website/client/src/components/ui/textarea.stories.js
  website/client/src/pages/private-messages.vue
Labels: status: pr: ready for review

#11549 Fix can not remove group tag
  test/api/unit/models/group.test.js
  website/server/models/group.js
Labels: status: pr: merged in develop; deploy pending

#11739 Correct some modal repops
  website/client/src/app.vue
  website/client/src/components/challenges/challengeModal.vue
  website/client/src/components/challenges/closeChallengeModal.vue
  website/client/src/components/payments/sendGemsModal.vue
Labels: status: pr: ready for review

#11791 clarify all "Invalid uuid" messages by making each unique
  website/server/libs/baseModel.js
  website/server/models/challenge.js
  website/server/models/group.js
  website/server/models/iapPurchaseReceipt.js
  website/server/models/subscriptionPlan.js
  website/server/models/tag.js
  website/server/models/task.js
  website/server/models/user/schema.js
  website/server/models/userNotification.js
Labels: status: pr: ready for review

#11647 Fix issues in NPCs should have NPC style on Display Name in chat, Hall. (fixes #11617)
  website/client/src/app.vue
  website/client/src/assets/scss/tiers.scss
  website/client/src/components/auth/registerLoginReset.vue
  website/client/src/components/settings/notifications.vue
  website/client/src/components/shops/quests/buyQuestModal.vue
  website/client/src/components/userLink.vue
Labels: status: pr: ready for review
