Repository HabitRPG/habitica, pull requests merged in 2020-05, with the labels that each got.

#12121 API: Adding secret.text to the user-schema
  test/api/v3/integration/hall/GET-hall_heroes.test.js
  test/api/v3/integration/hall/GET-hall_heroes_heroId.test.js
  test/api/v3/integration/hall/PUT-hall_heores_heroId.test.js
  test/api/v3/integration/members/GET-members_id.test.js
  test/api/v3/integration/user/GET-user.test.js
  test/api/v3/integration/user/GET-user_anonymized.test.js
  test/api/v3/integration/user/POST-user_reset.test.js
  test/api/v3/integration/user/PUT-user.test.js
  test/api/v4/user/GET-user.test.js
  test/api/v4/user/POST-user_reset.test.js
  test/api/v4/user/PUT-user.test.js
  website/server/controllers/api-v3/hall.js
  website/server/controllers/api-v3/user.js
  website/server/libs/user/index.js
  website/server/models/user/hooks.js
  website/server/models/user/methods.js
  website/server/models/user/schema.js
Labels: status: pr: ready for review

#12146 fix: return full inbox on user-v3-api
  test/api/v3/integration/user/GET-user.test.js
  test/api/v4/inbox/GET-inbox-conversations.test.js
  website/server/libs/inbox/index.js
  website/server/models/user/methods.js
Labels: status: pr: ready for review

#12150 update API's monthly Gem cap messages to use the friendly website version
  test/common/ops/buy/buyGem.js
  website/common/locales/en/subscriber.json
  website/common/script/ops/buy/buyGem.js
Labels: status: pr: ready for review

#12153 Added a full stop to shieldMystery201902Notes and shieldArmoireHorseshoeNotes.
  website/common/locales/en/gear.json
Labels: status: pr: ready for review

#12010 Changed private message" button to use <a href> to open Private Messa…
  website/client/src/components/userMenu/profile.vue
  website/client/src/pages/private-messages.vue
Labels: status: pr: ready for review

#12154 Vue component unit test isolation
  website/client/src/components/shops/quests/buyQuestModal.vue
  website/client/src/components/static/home.vue
  website/client/src/components/ui/pinBadge.vue
  website/client/src/libs/store/helpers/public.js
  website/client/src/libs/store/index.js
  website/client/tests/unit/components/home.spec.js
  website/client/tests/unit/libs/store.spec.js
  website/client/tests/unit/mixins/groupsUtilities.spec.js
  website/server/libs/email.js
  website/server/libs/invites/index.js
Labels: status: pr: ready for review

#12149 Dont throw away extra paypal months
  test/api/unit/libs/payments/stripe/calculateSubscriptionTerminationDate.test.js
  test/api/v3/integration/groups/POST-groups_groupId_leave.test.js
  website/server/libs/payments/calculateSubscriptionTerminationDate.js
  website/server/libs/payments/subscriptions.js
  website/server/libs/payments/util.js
Labels: status: pr: ready for review

#12072 To-Do cron task decay fixes
  test/api/unit/libs/cron.test.js
  website/common/script/ops/scoreTask.js
  website/server/libs/cron.js
Labels: status: pr: ready for review, type: notify helpers

#12030 Improve i18n caching
  .gitignore
  gulp/gulp-build.js
  gulp/gulp-cache.js
  gulpfile.js
  website/server/controllers/api-v3/i18n.js
  website/server/libs/i18n.js
Labels: status: pr: ready for review

#12176 FIX: scroll/loading guilds
  website/client/src/components/groups/discovery.vue
Labels: status: pr: being tested on delta, status: pr: ready for review

#12171 Fixed grammar, formatting and other errors in translatable strings
  website/common/locales/en/character.json
  website/common/locales/en/communityGuidelines.json
  website/common/locales/en/defaultTasks.json
  website/common/locales/en/gear.json
  website/common/locales/en/groups.json
  website/common/locales/en/quests.json
  website/common/locales/en/spells.json
  website/common/locales/en/tasks.json
Labels: status: pr: ready for review

#12174 Smartbanner TTL
  website/client/public/index.html
Labels: status: pr: ready for review

#12177 fix(chat) - Mention dot doesn't show if mention is preceded by weird …
  website/client/src/components/chat/chatCard.vue
  website/client/tests/unit/components/chat/chatCard.spec.js
  website/client/tests/unit/components/static/home.spec.js
Labels: status: pr: ready for review

#12100 Don't break up links with user profile link injections
  test/api/unit/libs/highlightMentions.test.js
  website/server/libs/highlightMentions.js
Labels: status: pr: ready for review

#12089 Issue 12033 - Use version of habitica-markdown that includes mentions
  package-lock.json
  package.json
  website/client/package-lock.json
  website/client/package.json
  website/client/src/components/chat/chatCard.vue
  website/client/src/components/messages/messageCard.vue
  website/client/src/libs/highlightUsers.js
  website/client/src/libs/renderWithMentions.js
  website/client/tests/unit/libs/renderWithMentions.spec.js
Labels: status: pr: ready for review

#12183 Make contributor achievement notification "sticky"
  website/client/src/components/notifications.vue
Labels: status: pr: ready for review

#12197 buyMysterySet records every item in Amplitude.
  test/common/ops/buy/buyMysterySet.js
  website/common/script/ops/buy/buyMysterySet.js
Labels: status: pr: ready for review

#12195 Bolding text inside a link in task title/notes. (#12178)
  website/client/src/components/tasks/task.vue
Labels: status: pr: ready for review

#12218 fix(chat) - Issue 12217 - Allow url-escapable characters in links.
  test/api/unit/libs/highlightMentions.test.js
  website/server/libs/highlightMentions.js
Labels: status: pr: ready for review

#12173 #11828: Show a boss damage notification for skills
  website/client/src/components/tasks/spells.vue
  website/client/src/mixins/spells.js
Labels: status: pr: ready for review

#12172 Fix Issue #12103: Wacky potions purchase warning
  website/client/src/components/shops/buyModal.vue
Labels: status: pr: ready for review

#12203 Add close button to profile modal
  website/client/src/components/userMenu/profile.vue
Labels: status: pr: ready for review

#12179 Client: remove unnecessary API calls + members fixes
  .eslintignore
  test/client/.babelrc
  test/client/unit/index.js
  test/client/unit/karma.conf.js
  website/client/src/app.vue
  website/client/src/components/achievements/chooseClass.vue
  website/client/src/components/achievements/newStuff.vue
  website/client/src/components/challenges/challengeDetail.vue
  website/client/src/components/chat/chatMessages.vue
  website/client/src/components/chat/copyAsTodoModal.vue
  website/client/src/components/chat/reportFlagModal.vue
  website/client/src/components/groups/group.vue
  website/client/src/components/groups/membersModal.vue
  website/client/src/components/groups/startQuestModal.vue
  website/client/src/components/header/index.vue
  website/client/src/components/header/notifications/base.vue
  website/client/src/components/header/notifications/worldBoss.vue
  website/client/src/components/inventory/stable/hatchedPetDialog.vue
  website/client/src/components/inventory/stable/mountRaisedModal.vue
  website/client/src/components/members/memberSearchDropdown.vue
  website/client/src/components/messages/messageList.vue
  website/client/src/components/notifications.vue
  website/client/src/components/payments/amazonModal.vue
  website/client/src/components/payments/cancelModalConfirm.vue
  website/client/src/components/payments/canceledModal.vue
  website/client/src/components/payments/successModal.vue
  website/client/src/components/shops/market/index.vue
  website/client/src/components/shops/market/sellModal.vue
  website/client/src/components/shops/quests/index.vue
  website/client/src/components/shops/seasonal/index.vue
  website/client/src/components/shops/timeTravelers/index.vue
  website/client/src/components/tasks/brokenTaskModal.vue
  website/client/src/components/tasks/column.vue
  website/client/src/components/tasks/taskModal.vue
  website/client/src/components/ui/customMenuDropdown.vue
  website/client/src/components/ui/loadingGryphon.vue
  website/client/src/components/userMenu/profileModal.vue
  website/client/src/libs/asyncResource.js
  website/client/src/libs/logging.js
  website/client/src/pages/private-messages.vue
  website/client/src/store/actions/chat.js
  website/client/src/store/actions/guilds.js
  website/client/src/store/actions/index.js
  website/client/src/store/actions/notifications.js
  website/client/src/store/actions/world-state.js
  website/client/src/store/actions/worldState.js
  website/client/src/store/getters/index.js
  website/client/src/store/getters/worldState.js
  website/client/src/store/index.js
  website/client/tests/unit/libs/asyncResource.spec.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#12250 remove references to codetriage.com
  .github/CONTRIBUTING.md
  README.md
Labels: priority: minor, status: pr: ready for review

#12228 Fix empty link bug and proper error logging in highlightMentions.js
  test/api/unit/libs/highlightMentions.test.js
  website/server/libs/highlightMentions.js
Labels: status: pr: ready for review

#12206 Only show attainable and owned special pets/mounts
  website/client/src/components/inventory/stable/index.vue
  website/common/script/content/stable.js
Labels: status: pr: ready for review
