Repository HabitRPG/habitica, pull requests merged in 2020-06, with the labels that each got.

#12249 New notification type for boss damage
  website/client/src/components/snackbars/notification.vue
  website/client/src/components/tasks/task.vue
  website/client/src/mixins/notifications.js
  website/client/src/mixins/spells.js
  website/common/locales/en/quests.json
Labels: status: pr: ready for review

#12205 Store original quantities, to avoid reordering in Inventory Items screen
  website/client/src/components/inventory/items/index.vue
Labels: status: pr: ready for review

#12257 Rewards Column UI Fixes
  website/client/src/components/tasks/column.vue
Labels: status: pr: being tested on delta, status: pr: ready for review

#12227 Blockquote styling (fixes #9476)
  website/client/src/assets/scss/markdown.scss
  website/client/src/components/chat/chatCard.vue
  website/client/src/components/messages/messageCard.vue
Labels: status: pr: ready for review

#12251 Enable resizing of message box (#11950)
  website/client/src/pages/private-messages.vue
Labels: status: pr: ready for review

#12278 Renaming a party shows you the placeholder text for renaming a guild #12273
  website/client/src/components/groups/groupFormModal.vue
  website/common/locales/en/groups.json
Labels: status: pr: ready for review

#12274 Tasks Redesign: Colors, Title, Notes, Habit Controls
  website/client/src/assets/scss/button.scss
  website/client/src/assets/scss/task.scss
  website/client/src/components/tasks/task.vue
  website/client/src/components/tasks/taskModal.vue
  website/client/src/store/getters/tasks.js
  website/common/locales/en/tasks.json
Labels: status: pr: ready for review

#12292 #9498: Hide Wolf-Veteran and LionCub-Ethereal
  website/common/script/content/stable.js
Labels: status: pr: ready for review

#12288 More Armoire content refactoring
  website/common/script/content/gear/sets/armoire.js
Labels: status: pr: ready for review

#12289 Remove party banner when below tablet size (fixes 10827)
  website/client/src/components/header/index.vue
  website/client/src/components/ui/statsbar.vue
Labels: status: pr: ready for review

#12290 To-Dos -> To Do's
  website/common/locales/en/defaultTasks.json
  website/common/locales/en/faq.json
  website/common/locales/en/front.json
  website/common/locales/en/gear.json
  website/common/locales/en/groups.json
  website/common/locales/en/limited.json
  website/common/locales/en/npc.json
  website/common/locales/en/overview.json
  website/common/locales/en/quests.json
  website/common/locales/en/questsContent.json
  website/common/locales/en/rebirth.json
  website/common/locales/en/settings.json
  website/common/locales/en/subscriber.json
  website/common/locales/en/tasks.json
  website/common/script/ops/scoreTask.js
  website/server/controllers/api-v3/tasks.js
  website/server/controllers/api-v3/user.js
  website/server/libs/cron.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#11906 Remove max-height for app-header
  website/client/src/components/header/index.vue
Labels: status: pr: ready for review

#12287 TaskModal: Checklist component extracted
  website/client/config/storybook/config.js
  website/client/src/assets/members/remove.svg
  website/client/src/assets/svg/block.svg
  website/client/src/assets/svg/chevron.svg
  website/client/src/assets/svg/grip.svg
  website/client/src/assets/svg/remove.svg
  website/client/src/components/groups/membersModal.vue
  website/client/src/components/messages/conversationItem.vue
  website/client/src/components/selectMembersModal.vue
  website/client/src/components/tasks/modal-controls/checklist.stories.js
  website/client/src/components/tasks/modal-controls/checklist.vue
  website/client/src/components/tasks/taskModal.vue
  website/client/src/components/ui/checkbox.vue
  website/client/src/components/userMenu/profile.vue
Labels: status: pr: being tested on gamma, status: pr: ready for review

#12313 Bugfix/show the correct negative icon in challenge habit
  website/client/src/components/tasks/task.vue
Labels: status: pr: ready for review

#12314 Groups: always show checklist-toggle
  website/client/src/components/tasks/task.vue
  website/server/controllers/api-v3/tasks.js
Labels: status: pr: being tested on gamma, status: pr: ready for review

#12331 MongoDB 4.2
  .github/workflows/test.yml
  migrations/groups/reconcile-group-plan-members.js
  website/server/libs/groupTasks.js
  website/server/models/group.js
Labels: status: pr: with author: needs work

#12339 Get Task Fixes
  test/api/v3/integration/tasks/GET-tasks_id.test.js
  website/server/controllers/api-v3/tasks.js
  website/server/controllers/api-v3/tasks/groups.js
Labels: status: pr: ready for review

#12337 added tests: if collapseChecklist is allowed and all others are still blocked
  test/api/v3/integration/tasks/groups/PUT-group_task_id.test.js
Labels: status: pr: merged in develop; deploy pending

#12340 docs(api): added info on how to use transformation items
  website/server/controllers/api-v3/user/spells.js
Labels: status: pr: ready for review

#12229 Make message links to deleted profiles display 404: (fixes 11020)
  package-lock.json
  website/client/src/components/chat/chatMessages.vue
  website/client/src/components/userMenu/profile.vue
Labels: status: pr: ready for review

#12332 tags names do not collapse when view width of the browser is changed, fixes #12253
  website/client/src/components/tasks/user.vue
Labels: status: pr: ready for review
