Repository HabitRPG/habitica, pull requests merged in 2020-11, with the labels that each got.

#12742 Preserve original subscription start date when creating team subscription
  website/server/libs/payments/groupPayments.js
Labels: status: pr: ready for review

#12732 Nested Spans Withing li tags
  website/client/package-lock.json
  website/client/src/components/settings/api.vue
Labels: status: pr: ready for review

#12757 Update Android FAQs
  website/common/locales/en/faq.json
Labels: status: pr: ready for review

#12743 Group title on route fix
  website/client/src/components/groups/group.vue
Labels: status: pr: ready for review

#12737 Fixes #12730 - Tag filter not always cleared correctly when deleting active tag
  website/client/src/components/tasks/user.vue
  website/client/src/router/index.js
Labels: status: pr: ready for review

#12758 update dropdowns to use the updated / styled components
  website/client/src/assets/scss/button.scss
  website/client/src/assets/scss/dropdown.scss
  website/client/src/components/inventory/equipment/index.vue
  website/client/src/components/shops/quests/index.vue
  website/client/src/components/shops/seasonal/index.vue
  website/client/src/components/shops/timeTravelers/index.vue
  website/client/src/components/ui/filterDropdown.vue
Labels: status: pr: being tested on delta, status: pr: ready for review

#12744 Update sidebar styles
  website/client/src/components/challenges/sidebar.vue
  website/client/src/components/groups/sidebar.vue
  website/client/src/components/shops/market/filter.vue
  website/client/src/components/shops/quests/index.vue
  website/client/src/components/shops/seasonal/index.vue
  website/client/src/components/shops/timeTravelers/index.vue
  website/client/src/components/ui/filterGroup.vue
Labels: status: pr: being tested on delta, status: pr: ready for review

#12762 Challenge Won Notification improvements
  test/api/v3/integration/challenges/POST-challenges_challengeId_winner_winnerId.test.js
  website/client/src/components/achievements/wonChallenge.vue
  website/client/src/components/inventory/equipment/index.vue
  website/client/src/components/inventory/equipment/unequipDropdown.vue
  website/client/src/components/inventory/items/index.vue
  website/client/src/components/inventory/stable/index.vue
  website/client/src/components/notifications.vue
  website/client/src/components/settings/api.vue
  website/client/src/components/shared/closeIcon.vue
  website/client/src/components/shared/inventoryDrawer.vue
  website/client/src/components/static/contact.vue
  website/client/src/components/ui/drawer.vue
  website/client/src/components/ui/equipBadge.vue
  website/client/src/components/ui/filterGroup.vue
  website/client/src/components/ui/filterSidebar.vue
  website/client/src/components/ui/itemRows.vue
  website/client/src/components/ui/showMoreButton.vue
  website/common/locales/en/challenge.json
  website/server/models/challenge.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#12761 make guilds not display group plans as title section
  website/client/src/components/group-plans/taskInformation.vue
  website/client/src/components/groups/group.vue
Labels: status: pr: ready for review

#12792 Mandatory pagination for GET /challenges/user
  test/api/v3/integration/challenges/GET-challenges_user.test.js
  website/server/controllers/api-v3/challenges.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#12790 Bugfix in ko/front.json
  website/common/locales/ko/front.json
Labels: status: pr: ready for review

#12791 Miscellaneous lint fixes: move watch & mounted properties; apply automatic fixes
  website/client/src/components/challenges/challengeDetail.vue
  website/client/src/components/challenges/sidebar.vue
  website/client/src/components/inventory/items/index.vue
  website/client/src/components/inventory/stable/index.vue
  website/client/src/components/shops/market/filter.vue
  website/client/src/components/shops/quests/index.vue
  website/client/src/components/shops/timeTravelers/index.vue
  website/client/src/components/tasks/user.vue
  website/client/src/components/ui/filterDropdown.vue
Labels: status: pr: ready for review

#12818 Upgrade APN module
  package-lock.json
  package.json
  test/api/unit/libs/pushNotifications.js
  website/server/libs/pushNotifications.js
Labels: status: pr: being tested on delta, status: pr: ready for review, status: pr: tested and approved; merge pending

#12814 Apply Dropdown Styles to various parts
  website/client/src/assets/scss/dropdown.scss
  website/client/src/components/challenges/challengeDetail.vue
  website/client/src/components/groups/membersModal.vue
  website/client/src/components/inventory/equipment/index.vue
  website/client/src/components/inventory/equipment/unequipDropdown.vue
Labels: status: pr: ready for review, status: pr: tested and approved; merge pending

#12715 Node 14
  .buildpacks
  .github/workflows/test.yml
  .nvmrc
  package.json
Labels: status: pr: merged in develop; deploy pending

#12817 Upgrade some deps: helmet, slack, amplitude and short-uuid
  package-lock.json
  package.json
  test/api/unit/libs/slack.js
  test/api/v3/integration/chat/POST-chat.flag.test.js
  test/api/v3/integration/chat/POST-chat.test.js
  website/server/libs/slack.js
  website/server/middlewares/index.js
Labels: status: pr: merged in develop; deploy pending

#12716 Feature/enhance get memebers for a challenge fixes #12481
  test/api/v3/integration/challenges/GET-challenges_challengeId_members.test.js
  test/api/v3/integration/challenges/GET-challenges_challengeId_members_memberId.test.js
  website/server/controllers/api-v3/members.js
  website/server/libs/challenges/handleGetMembersForChallenge.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#12820 use or clause for display name and username search
  website/server/controllers/api-v3/members.js
Labels: status: pr: ready for review, status: pr: tested and approved; merge pending

#12679 Removed duplicates I18N strings (related to issue #9210)
  website/common/locales/en/generic.json
  website/common/locales/en/npc.json
Labels: status: pr: ready for review, status: pr: tested and approved; merge pending
