Repository HabitRPG/habitica, pull requests merged in 2020-03, with the labels that each got.

#11916 Fix corrupt data
  test/api/unit/middlewares/response.js
  test/api/unit/models/pushDevice.test.js
  test/api/unit/models/tag.test.js
  test/api/unit/models/user.test.js
  test/api/unit/models/userNotification.test.js
  website/server/controllers/api-v3/notifications.js
  website/server/middlewares/response.js
  website/server/models/pushDevice.js
  website/server/models/tag.js
  website/server/models/user/hooks.js
  website/server/models/userNotification.js
Labels: status: pr: ready for review

#11887 Logs improvements
  package-lock.json
  package.json
  test/api/unit/libs/logger.js
  website/server/libs/logger.js
Labels: status: pr: ready for review

#11915 Ensure first-time purchases are synced
  website/common/script/ops/buy/purchase.js
Labels: status: pr: ready for review

#11886 Change where members info is retrieved in Group component: Fixes #11737
  website/client/src/components/challenges/challengeDetail.vue
  website/client/src/components/groups/group.vue
  website/client/src/components/header/notifications/g1g1.vue
  website/client/src/components/payments/selectUserModal.vue
  website/client/src/components/settings/subscription.vue
  website/client/src/components/settings/subscriptionOptions.vue
  website/client/src/components/shops/buyModal.vue
Labels: status: pr: ready for review

#11945 Fix username links resulting in truncated chat messages
  test/api/v3/integration/chat/POST-chat.test.js
  website/client/src/components/groups/chat.vue
  website/client/src/pages/private-messages.vue
  website/common/script/constants.js
  website/common/script/index.js
  website/server/controllers/api-v3/chat.js
  website/server/controllers/api-v3/members.js
  website/server/models/message.js
  website/server/models/user/methods.js
Labels: status: pr: merged in develop; deploy pending

#11766 Fixing layout issues for the private messages page
  website/client/src/assets/scss/form.scss
  website/client/src/components/header/userDropdown.vue
  website/client/src/components/messages/conversationItem.vue
  website/client/src/components/messages/messageList.vue
  website/client/src/components/settings/usernameForm.vue
  website/client/src/components/tasks/column.vue
  website/client/src/components/ui/textarea.stories.js
  website/client/src/components/userLink.vue
  website/client/src/libs/events.js
  website/client/src/mixins/sync.js
  website/client/src/pages/private-messages.vue
  website/client/src/store/actions/user.js
  website/common/locales/en/generic.json
  website/common/locales/en/groups.json
  website/server/controllers/api-v4/inbox.js
  website/server/libs/inbox/conversation.methods.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#11883 Adventure Guide Prep
  test/api/v3/integration/user/PUT-user.test.js
  test/api/v4/user/PUT-user.test.js
  test/common/fns/randomDrop.test.js
  test/common/fns/updateStats.test.js
  test/common/ops/rebirth.js
  website/client/src/components/achievements/dropsEnabled.vue
  website/client/src/components/achievements/firstDrops.vue
  website/client/src/components/notifications.vue
  website/client/src/components/tasks/task.vue
  website/client/src/components/userMenu/stats.vue
  website/client/src/store/index.js
  website/common/locales/en/achievements.json
  website/common/locales/en/content.json
  website/common/locales/en/faq.json
  website/common/locales/en/inventory.json
  website/common/locales/en/npc.json
  website/common/locales/en/overview.json
  website/common/locales/en/pets.json
  website/common/script/fns/firstDrops.js
  website/common/script/fns/randomDrop.js
  website/common/script/fns/updateStats.js
  website/common/script/libs/onboarding.js
  website/common/script/ops/buy/abstractBuyOperation.js
  website/common/script/ops/buy/buyMarketGear.js
  website/common/script/ops/feed.js
  website/common/script/ops/hatch.js
  website/common/script/ops/scoreTask.js
  website/server/controllers/api-v3/tasks.js
  website/server/libs/taskManager.js
  website/server/models/user/schema.js
  website/server/models/userNotification.js
Labels: status: pr: ready for review

#11953 Remove old username setting and update changeUsernameDisclaimer (fixes #10967)
  website/client/src/components/header/notifications/verifyUsername.vue
  website/common/locales/en/settings.json
Labels: status: pr: merged in develop; deploy pending

#11954 Fix collapse checklist tooltip placement
  website/client/src/components/tasks/task.vue
Labels: status: pr: ready for review

#11919 Fix asc/desc sort order when sorted by name
  website/client/src/components/groups/membersModal.vue
Labels: status: pr: ready for review

#11918 Special case for member profile name.
  website/client/src/components/header/index.vue
Labels: status: pr: ready for review

#11030 Ensure official challenges are listed first (fixes #11018)
  test/api/v3/integration/challenges/GET-challenges_group_groupid.test.js
  test/api/v3/integration/challenges/GET-challenges_user.test.js
  website/server/controllers/api-v3/challenges.js
  website/server/libs/challenges/index.js
Labels: status: pr: ready for review

#11903 Fix for search guilds result being inconsistent between "My Guilds" and "Discover Guilds"
  test/api/v3/integration/groups/GET-groups.test.js
  website/client/src/mixins/groupsUtilities.js
  website/client/tests/unit/components/groups/myGuilds.spec.js
  website/client/tests/unit/mixins/groupsUtilities.spec.js
  website/server/controllers/api-v3/groups.js
Labels: status: pr: ready for review

#11912 Fix for party members missing from header after viewing private messages / inbox / PMs
  website/client/src/components/header/index.vue
Labels: status: pr: ready for review

#11966 Disable Failing Webhooks
  test/api/unit/libs/webhooks.test.js
  test/api/v3/integration/webhook/POST-user_add_webhook.test.js
  test/api/v3/integration/webhook/PUT-user_update_webhook.test.js
  website/server/controllers/api-v3/webhook.js
  website/server/controllers/top-level/dataexport.js
  website/server/libs/email.js
  website/server/libs/webhook.js
  website/server/models/webhook.js
Labels: status: pr: merged in develop; deploy pending

#11994 edit foundNewItemsExplanation string to say Pet Food, not food
  website/common/locales/en/achievements.json
Labels: status: pr: ready for review

#11917 Fixes Japanese conversion bugs on Safari and Chrome
  website/client/src/components/tasks/taskModal.vue
Labels: status: pr: being tested on delta, status: pr: ready for review

#11992 Refresh the "de-register" social media buttons in the settings
  website/client/src/components/settings/site.vue
Labels: status: pr: ready for review

#11870 Reward with negative cost can no longer be created, fixes #11855
  migrations/migration-runner.js
  migrations/tasks/rewards-flip-negative-costs.js
  test/api/v3/integration/tasks/POST-tasks_user.test.js
  test/api/v3/integration/tasks/PUT-tasks_id.test.js
  website/common/script/ops/scoreTask.js
  website/server/controllers/api-v3/tasks.js
  website/server/models/task.js
Labels: status: pr: ready for review

#12015 IP Blocking
  config.json.example
  test/api/unit/libs/errors.test.js
  test/api/unit/middlewares/ipBlocker.test.js
  website/common/script/errors/apiErrorMessages.js
  website/common/script/libs/errors.js
  website/server/libs/errors.js
  website/server/middlewares/index.js
  website/server/middlewares/ipBlocker.js
Labels: status: pr: ready for review

#12020 Content API Cache improvements
  .nodemonignore
  gulp/gulp-build.js
  gulp/gulp-content.js
  gulpfile.js
  test/api/unit/libs/content.test.js
  website/server/controllers/api-v3/content.js
  website/server/libs/content.js
Labels: status: pr: ready for review

#12031 Fixes for data exports
  website/server/controllers/top-level/dataexport.js
Labels: status: pr: ready for review

#12013 Fixes "Hide Basic Achievements" button formatting in Achievements Modal when section is expanded | fixes #12012
  website/client/src/components/userMenu/profile.vue
Labels: status: pr: ready for review

#11989 Updated hatching tooltip language in all English instances.
  website/common/locales/en/pets.json
Labels: status: pr: with author: needs work
