Repository HabitRPG/habitica, pull requests merged in 2020-10, with the labels that each got.

#12035 Admin Panel to replace admin features in Hall of Heroes
  test/api/unit/libs/items/utils.test.js
  test/api/v3/integration/debug/POST-debug_make-admin.test.js
  test/api/v3/integration/hall/GET-hall_heroes_heroId.test.js
  test/api/v3/integration/hall/GET-hall_heroes_party_groupId.test.js
  test/api/v3/integration/hall/PUT-hall_heores_heroId.test.js
  website/client/src/components/admin-panel/filters/formatDate.js
  website/client/src/components/admin-panel/index.vue
  website/client/src/components/admin-panel/mixins/getItemDescription.js
  website/client/src/components/admin-panel/mixins/saveHero.js
  website/client/src/components/admin-panel/user-support/avatarAndDrops.vue
  website/client/src/components/admin-panel/user-support/basicDetails.vue
  website/client/src/components/admin-panel/user-support/contributorDetails.vue
  website/client/src/components/admin-panel/user-support/cronAndAuth.vue
  website/client/src/components/admin-panel/user-support/index.vue
  website/client/src/components/admin-panel/user-support/itemsOwned.vue
  website/client/src/components/admin-panel/user-support/partyAndQuest.vue
  website/client/src/components/admin-panel/user-support/privilegesAndGems.vue
  website/client/src/components/hall/heroes.vue
  website/client/src/components/header/menu.vue
  website/client/src/components/shops/buyModal.vue
  website/client/src/components/shops/shopItem.vue
  website/client/src/components/tasks/column.vue
  website/client/src/components/tasks/task.vue
  website/client/src/components/userMenu/profile.vue
  website/client/src/pages/private-messages.vue
  website/client/src/router/index.js
  website/client/src/store/actions/hall.js
  website/common/script/errors/apiErrorMessages.js
  website/server/controllers/api-v3/hall.js
  website/server/libs/items/utils.js
  website/server/models/user/schema.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#12612 Fix vue test stacktraces
  website/client/src/components/avatar.vue
  website/client/tests/unit/components/avatar.spec.js
  website/client/tests/unit/components/chat/chatCard.spec.js
  website/client/tests/unit/components/home.spec.js
  website/client/tests/unit/components/notifications.spec.js
  website/client/tests/unit/components/tasks/column.spec.js
  website/client/tests/unit/components/tasks/user.spec.js
Labels: status: pr: ready for review

#12584 Add aria-label to header
  website/client/src/components/members/classBadge.vue
Labels: status: pr: ready for review

#12632 fixed "login" button bug
  website/client/src/components/static/header.vue
Labels: status: pr: ready for review

#12609 fix(task) - 11139 use start-from hours in due date calculation
  website/client/src/components/tasks/task.vue
  website/client/tests/unit/components/tasks/task.spec.js
Labels: status: pr: ready for review

#12628 Removed (duplicated) unused I18N strings from the `content.json` files (related to issue #9957)
  website/common/locales/en/content.json
Labels: status: pr: ready for review

#12657 Upgrade mongoose and fix tests
  package-lock.json
  package.json
  test/api/unit/libs/payments/payments.test.js
Labels: status: pr: ready for review

#12637 Fix overflow in guild member text and keyboard inaccessible member/bank lists fixes #11067
  website/client/src/components/groups/group.vue
Labels: status: pr: ready for review

#10739 Implement Bailey CMS API
  test/api/unit/middlewares/ensureAccessRight.test.js
  test/api/unit/models/newsPost.js
  test/api/unit/models/user.test.js
  test/api/v3/integration/news/GET-news.test.js
  test/api/v3/integration/news/POST-news_tell_me_later.test.js
  test/api/v3/integration/user/PUT-user.test.js
  test/api/v4/news/DELETE-news.test.js
  test/api/v4/news/GET-news.test.js
  test/api/v4/news/GET-news_id.test.js
  test/api/v4/news/POST-news.test.js
  test/api/v4/news/POST-news_read.test.js
  test/api/v4/news/PUT-news_newsId.test.js
  website/client/src/assets/scss/modal.scss
  website/client/src/components/achievements/newStuff.vue
  website/client/src/components/news/modal.vue
  website/client/src/components/news/newsContent.vue
  website/client/src/components/notifications.vue
  website/client/src/components/static/newStuff.vue
  website/client/src/store/actions/index.js
  website/client/src/store/actions/news.js
  website/client/src/store/actions/user.js
  website/common/locales/en/messages.json
  website/common/script/errors/apiErrorMessages.js
  website/server/controllers/api-v3/news.js
  website/server/controllers/api-v4/news.js
  website/server/libs/user/index.js
  website/server/middlewares/appRoutes.js
  website/server/middlewares/ensureAccessRight.js
  website/server/models/newsPost.js
  website/server/models/user/hooks.js
  website/server/models/user/methods.js
  website/server/models/user/schema.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#12651 Drop Cap Modal
  test/api/unit/middlewares/cronMiddleware.js
  test/common/fns/randomDrop.test.js
  website/client/src/assets/images/swords.png
  website/client/src/assets/images/swords@2x.png
  website/client/src/assets/images/swords@3x.png
  website/client/src/assets/scss/dropdown.scss
  website/client/src/assets/scss/modal.scss
  website/client/src/components/achievements/dropCapReached.vue
  website/client/src/components/categories/categoryTags.vue
  website/client/src/components/header/messageCount.vue
  website/client/src/components/header/notifications/base.vue
  website/client/src/components/header/notifications/dropCapReached.vue
  website/client/src/components/header/notificationsDropdown.vue
  website/client/src/components/header/userDropdown.vue
  website/client/src/components/members/classBadge.vue
  website/client/src/components/notifications.vue
  website/client/src/components/shops/buyModal.vue
  website/client/src/components/shops/shopItem.vue
  website/client/src/components/tasks/column.vue
  website/client/src/components/tasks/task.vue
  website/common/script/fns/randomDrop.js
  website/server/libs/taskManager.js
  website/server/middlewares/cron.js
  website/server/models/userNotification.js
Labels: status: pr: merged in develop; deploy pending

#12604 Removed unused I18N strings from the `front.json` files (related to issue #9957)
  website/common/locales/bg/front.json
  website/common/locales/bn/front.json
  website/common/locales/cs/front.json
  website/common/locales/da/front.json
  website/common/locales/de/front.json
  website/common/locales/en/front.json
  website/common/locales/en@lolcat/front.json
  website/common/locales/en@pirate/front.json
  website/common/locales/en_GB/front.json
  website/common/locales/es/front.json
  website/common/locales/es_419/front.json
  website/common/locales/fr/front.json
  website/common/locales/he/front.json
  website/common/locales/hi/front.json
  website/common/locales/hu/front.json
  website/common/locales/id/front.json
  website/common/locales/it/front.json
  website/common/locales/ja/front.json
  website/common/locales/ko/front.json
  website/common/locales/ms/front.json
  website/common/locales/nb_NO/front.json
  website/common/locales/nl/front.json
  website/common/locales/pl/front.json
  website/common/locales/pt/front.json
  website/common/locales/pt_BR/front.json
  website/common/locales/ro/front.json
  website/common/locales/ru/front.json
  website/common/locales/sk/front.json
  website/common/locales/sr/front.json
  website/common/locales/sv/front.json
  website/common/locales/tr/front.json
  website/common/locales/uk/front.json
  website/common/locales/vi/front.json
  website/common/locales/zh/front.json
  website/common/locales/zh_TW/front.json
Labels: status: pr: being tested on delta, status: pr: ready for review

#12659 fix "push to bottom" for user tasks in API
  test/api/v3/integration/tasks/POST-tasks_move_taskId_to_position.test.js
  website/server/controllers/api-v3/tasks.js
  website/server/controllers/api-v3/tasks/groups.js
  website/server/controllers/api-v3/user.js
Labels: status: pr: ready for review

#12693 new users: do not show bailey news on second login
  test/api/unit/models/user.test.js
  website/server/models/user/hooks.js
Labels: status: pr: merged in develop; deploy pending

#11948 Inventory: fixes / layout
  test/api/v4/user/POST-user_unequip.test.js
  test/common/ops/unequip.js
  website/client/config/storybook/config.js
  website/client/src/assets/scss/badge.scss
  website/client/src/assets/scss/button.scss
  website/client/src/assets/scss/drawer.scss
  website/client/src/assets/scss/dropdown.scss
  website/client/src/assets/scss/form.scss
  website/client/src/assets/scss/item.scss
  website/client/src/assets/scss/page.scss
  website/client/src/assets/scss/typography.scss
  website/client/src/assets/svg/equip.svg
  website/client/src/assets/svg/unequip.svg
  website/client/src/components/inventory/equipment/attributesGrid.vue
  website/client/src/components/inventory/equipment/equipGearModal.vue
  website/client/src/components/inventory/equipment/index.vue
  website/client/src/components/inventory/equipment/unequipDropdown.vue
  website/client/src/components/inventory/items/index.vue
  website/client/src/components/inventory/stable/hatchingModal.vue
  website/client/src/components/inventory/stable/index.vue
  website/client/src/components/payments/buttons/list.vue
  website/client/src/components/secondaryMenu.vue
  website/client/src/components/shared/closeIcon.vue
  website/client/src/components/shared/inventoryDrawer.vue
  website/client/src/components/tasks/modal-controls/selectDifficulty.vue
  website/client/src/components/tasks/modal-controls/selectTranslatedArray.vue
  website/client/src/components/tasks/user.vue
  website/client/src/components/ui/buttons.stories.js
  website/client/src/components/ui/checkbox.vue
  website/client/src/components/ui/drawer.vue
  website/client/src/components/ui/equipBadge.vue
  website/client/src/components/ui/filterGroup.vue
  website/client/src/components/ui/filterSidebar.vue
  website/client/src/components/ui/itemRows.vue
  website/client/src/components/ui/selectList.vue
  website/client/src/components/ui/showMoreButton.vue
  website/client/src/components/ui/toggleSwitch.stories.js
  website/client/src/components/ui/toggleSwitch.vue
  website/client/src/components/userMenu/profile.vue
  website/client/src/store/actions/user.js
  website/client/tests/unit/components/ui/drawer.spec.js
  website/common/locales/en/challenge.json
  website/common/locales/en/inventory.json
  website/common/locales/en/messages.json
  website/common/script/index.js
  website/common/script/ops/index.js
  website/common/script/ops/unequip.js
  website/server/controllers/api-v4/user.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#12695 Prevent the removal of a quest owner from a group, take 2
  test/api/v3/integration/groups/POST-groups_id_removeMember.test.js
  website/common/locales/en/groups.json
  website/server/controllers/api-v3/groups.js
Labels: status: pr: ready for review

#12627 Fixes Issue #12421 - Change page title based on the site section being viewed
  website/client/src/components/auth/registerLoginReset.vue
  website/client/src/components/challenges/challengeDetail.vue
  website/client/src/components/challenges/findChallenges.vue
  website/client/src/components/challenges/myChallenges.vue
  website/client/src/components/group-plans/taskInformation.vue
  website/client/src/components/groups/discovery.vue
  website/client/src/components/groups/group.vue
  website/client/src/components/groups/groupPlan.vue
  website/client/src/components/groups/myGuilds.vue
  website/client/src/components/groups/tavern.vue
  website/client/src/components/inventory/equipment/index.vue
  website/client/src/components/inventory/items/index.vue
  website/client/src/components/inventory/stable/index.vue
  website/client/src/components/settings/api.vue
  website/client/src/components/settings/dataExport.vue
  website/client/src/components/settings/notifications.vue
  website/client/src/components/settings/promoCode.vue
  website/client/src/components/settings/site.vue
  website/client/src/components/settings/subscription.vue
  website/client/src/components/shops/market/index.vue
  website/client/src/components/shops/quests/index.vue
  website/client/src/components/shops/seasonal/index.vue
  website/client/src/components/shops/timeTravelers/index.vue
  website/client/src/components/static/contact.vue
  website/client/src/components/static/faq.vue
  website/client/src/components/static/features.vue
  website/client/src/components/static/groupPlans.vue
  website/client/src/components/static/home.vue
  website/client/src/components/static/pressKit.vue
  website/client/src/components/tasks/user.vue
  website/client/src/components/userMenu/profile.vue
  website/client/src/pages/private-messages.vue
  website/client/src/router/index.js
  website/client/src/store/actions/common.js
  website/common/locales/en/front.json
  website/common/locales/en/groups.json
Labels: status: pr: merged in develop; deploy pending

#12444 fix(banned words): fix partial matching of words containing diacritic…
  test/api/unit/libs/stringUtils.test.js
  website/server/libs/stringUtils.js
Labels: status: pr: ready for review

#12656 Fix keyboard inaccessible accordion in guild/party page fixes #12653
  website/client/src/components/sidebarButton.vue
  website/client/src/components/sidebarSection.vue
  website/client/tests/unit/components/sidebarSection.spec.js
Labels: status: pr: ready for review

#12676 Loggly-only user support events
  website/server/controllers/api-v3/challenges.js
  website/server/controllers/api-v3/quests.js
  website/server/controllers/top-level/payments/paypal.js
  website/server/controllers/top-level/payments/stripe.js
  website/server/libs/analyticsService.js
  website/server/libs/cron.js
Labels: status: pr: ready for review

#12735 Analytics: track generic events through the server
  test/api/v3/integration/analytics/POST-analytics_track_eventName.test.js
  test/helpers/api-integration/requester.js
  website/client/src/components/achievements/dropCapReached.vue
  website/client/src/components/header/notifications/dropCapReached.vue
  website/client/src/components/header/userDropdown.vue
  website/client/src/libs/analytics.js
  website/client/src/store/actions/analytics.js
  website/client/src/store/actions/index.js
  website/client/vue.config.js
  website/server/controllers/api-v3/challenges.js
  website/server/controllers/api-v3/quests.js
  website/server/controllers/top-level/analytics.js
  website/server/controllers/top-level/payments/paypal.js
  website/server/controllers/top-level/payments/stripe.js
  website/server/libs/analyticsService.js
  website/server/libs/cron.js
Labels: status: pr: merged in develop; deploy pending

#12700 Fix Tasks styles
  website/client/src/assets/scss/markdown.scss
  website/client/src/assets/scss/typography.scss
  website/client/src/components/tasks/task.vue
Labels: status: pr: being tested on delta, status: pr: ready for review
