Repository HabitRPG/habitica, pull requests merged in 2020-02, with the labels that each got.

#11708 stop dropdown menu getting stuck on hover - fixes #11615
  website/client/src/assets/scss/dropdown.scss
  website/client/src/components/header/menu.vue
Labels: status: pr: ready for review

#11763 contributor tier color/icon appear in guild/challenge member/participant list Fix for #11736
  website/client/src/components/memberDetails.vue
Labels: status: pr: ready for review

#11797 NPC style should apply to tier $800 only
  website/client/src/components/chat/autoComplete.vue
  website/client/src/components/userLabel.vue
  website/client/src/components/userLink.vue
Labels: status: pr: tested and approved; merge pending

#11795 Prevent server from cancelling still active subs
  test/api/unit/libs/payments/google.test.js
  website/server/libs/payments/google.js
Labels: status: pr: ready for review

#11823 Subscription Page Overhaul
  website/client/src/assets/images/g1g1-notif.png
  website/client/src/assets/images/g1g1-send.png
  website/client/src/assets/images/subscriber-food.png
  website/client/src/assets/scss/typography.scss
  website/client/src/assets/svg/apple-pay-logo.svg
  website/client/src/assets/svg/calendar-purple.svg
  website/client/src/assets/svg/close-teal.svg
  website/client/src/assets/svg/gift-purple.svg
  website/client/src/assets/svg/google-pay-logo.svg
  website/client/src/assets/svg/group.svg
  website/client/src/assets/svg/habitica-logo-purple.svg
  website/client/src/assets/svg/paypal-logo.svg
  website/client/src/assets/svg/subscriber-gems.svg
  website/client/src/assets/svg/subscriber-hourglasses.svg
  website/client/src/components/header/menu.vue
  website/client/src/components/header/notifications/g1g1.vue
  website/client/src/components/header/notificationsDropdown.vue
  website/client/src/components/header/userDropdown.vue
  website/client/src/components/payments/buyGemsModal.vue
  website/client/src/components/payments/selectUserModal.vue
  website/client/src/components/payments/successModal.vue
  website/client/src/components/settings/subscription.vue
  website/client/src/components/settings/subscriptionOptions.vue
  website/client/src/mixins/payments.js
  website/client/src/store/actions/members.js
  website/client/src/store/index.js
  website/common/locales/en/groups.json
  website/common/locales/en/npc.json
  website/common/locales/en/settings.json
  website/common/locales/en/subscriber.json
  website/server/models/userNotification.js
Labels: status: pr: merged in develop; deploy pending

#11859 Fixing some typos, etc. in the API doc
  website/server/controllers/api-v3/auth.js
  website/server/controllers/api-v3/coupon.js
  website/server/controllers/api-v3/members.js
  website/server/controllers/api-v3/tasks.js
  website/server/controllers/api-v3/tasks/groups.js
  website/server/controllers/api-v3/user.js
  website/server/controllers/api-v3/user/stats.js
Labels: status: pr: ready for review

#11856 Update user count and write text consistently. fixes #11790
  website/client/src/components/static/home.vue
  website/common/locales/en/front.json
Labels: status: pr: ready for review

#11867 Remove drawer padding adjustment, fixes #11863
  website/client/src/components/ui/drawer.vue
Labels: status: pr: ready for review

#11798 Show "no owner" when challenge leader cannot be found fixes #11768
  website/client/src/components/challenges/challengeDetail.vue
  website/client/src/components/challenges/challengeItem.vue
  website/client/src/store/getters/tasks.js
Labels: status: pr: ready for review

#11857 fix for three dots menu getting covered up by footer issue: #11227
  website/client/src/components/appFooter.vue
Labels: status: pr: ready for review

#11866 Closing droppable menu after clicking an item fixes #11833
  website/client/src/components/header/menu.vue
Labels: status: pr: ready for review

#11826 [Fix #11824] Show member Display Name if Username is blank
  website/client/src/components/members/memberSearchDropdown.vue
Labels: status: pr: with author: needs work

#11769 Challenge exception-handling / clientside prize validation
  website/client/src/components/challenges/challengeModal.vue
Labels: status: pr: merged in develop; deploy pending

#11862 Resolves #11861 — Makes "quest already started" error descriptive
  test/api/v3/integration/quests/POST-groups_groupId_quests_accept.test.js
  test/api/v3/integration/quests/POST-groups_groupId_quests_force-start.test.js
  test/api/v3/integration/quests/POST-groups_groupid_quests_reject.test.js
  website/common/locales/en/quests.json
  website/server/controllers/api-v3/quests.js
Labels: status: pr: ready for review

#11792 Improve G1G1 process
  website/client/src/assets/images/g1g1-notif.png
  website/client/src/assets/images/g1g1-send.png
  website/client/src/components/header/notifications/g1g1.vue
  website/client/src/components/payments/selectUserModal.vue
  website/client/src/components/payments/successModal.vue
Labels: status: pr: ready for review

#11832 improvements to apidocs comments
  website/server/controllers/api-v3/auth.js
  website/server/controllers/api-v3/challenges.js
  website/server/controllers/api-v3/cron.js
  website/server/controllers/api-v3/hall.js
  website/server/controllers/api-v3/members.js
  website/server/controllers/api-v3/news.js
  website/server/controllers/api-v3/tags.js
  website/server/controllers/api-v3/tasks.js
  website/server/controllers/api-v3/tasks/groups.js
  website/server/controllers/api-v3/user.js
  website/server/controllers/api-v3/user/spells.js
  website/server/controllers/api-v3/user/stats.js
  website/server/controllers/api-v4/inbox.js
  website/server/controllers/api-v4/members.js
  website/server/controllers/top-level/dataexport.js
  website/server/controllers/top-level/email.js
Labels: status: pr: ready for review

#11884 Enchanted Armoire immediately updates XP stat in header (fixes #11827)
  website/client/src/store/actions/shops.js
  website/common/script/ops/buy/buyArmoire.js
Labels: status: pr: ready for review, type: notify helpers

#11889 Allow group links on challenge details to be opened in a new tab
  website/client/src/components/groupLink.vue
Labels: status: pr: ready for review
