Repository HabitRPG/habitica, pull requests merged in 2020-12, with the labels that each got.

#12776 Fixed Skill Layout
  website/client/src/components/challenges/challengeDetail.vue
  website/client/src/components/groups/membersModal.vue
  website/client/src/components/tasks/spells.vue
  website/common/locales/en/npc.json
Labels: status: pr: being tested on delta, status: pr: ready for review

#12838 Corrected recipient email address in reported PM Slack notification - fixes #12256
  package-lock.json
  website/client/package-lock.json
  website/server/libs/chatReporting/inboxChatReporter.js
  website/server/libs/slack.js
Labels: status: pr: ready for review

#12840 Fixed footer layout
  website/client/src/components/appFooter.vue
Labels: status: pr: ready for review

#12785 Stripe: upgrade module and API, switch to Checkout
  config.json.example
  package-lock.json
  package.json
  test/api/unit/libs/payments/amazon/checkout.test.js
  test/api/unit/libs/payments/apple.test.js
  test/api/unit/libs/payments/gems.test.js
  test/api/unit/libs/payments/google.test.js
  test/api/unit/libs/payments/group-plans/group-payments-create.test.js
  test/api/unit/libs/payments/paypal/checkout.test.js
  test/api/unit/libs/payments/stripe/cancel-subscription.test.js
  test/api/unit/libs/payments/stripe/checkout-subscription.test.js
  test/api/unit/libs/payments/stripe/checkout.test.js
  test/api/unit/libs/payments/stripe/edit-subscription.test.js
  test/api/unit/libs/payments/stripe/oneTimePayments.test.js
  test/api/unit/libs/payments/stripe/subscriptions.test.js
  test/api/unit/libs/payments/stripe/upgrade-group-plan.test.js
  test/api/unit/libs/payments/stripe/webhooks.test.js
  test/api/v3/integration/payments/stripe/POST-payments_stripe_checkout-session.test.js
  test/api/v3/integration/payments/stripe/POST-payments_stripe_checkout.test.js
  test/api/v3/integration/payments/stripe/POST-payments_stripe_subscribe_edit.test.js
  test/api/v3/integration/payments/stripe/POST-payments_stripe_webhooks.test.js
  website/client/src/components/group-plans/billing.vue
  website/client/src/components/group-plans/createGroupModalPages.vue
  website/client/src/components/groups/groupPlan.vue
  website/client/src/components/payments/buyGemsModal.vue
  website/client/src/components/payments/sendGemsModal.vue
  website/client/src/components/settings/subscription.vue
  website/client/src/components/settings/subscriptionOptions.vue
  website/client/src/libs/payments.js
  website/client/src/mixins/payments.js
  website/client/src/router/handleRedirect.js
  website/client/src/router/index.js
  website/common/locales/en/groups.json
  website/common/locales/en/npc.json
  website/common/locales/en/subscriber.json
  website/common/script/constants.js
  website/common/script/index.js
  website/server/controllers/api-v3/groups.js
  website/server/controllers/top-level/payments/stripe.js
  website/server/libs/cron.js
  website/server/libs/payments/amazon.js
  website/server/libs/payments/apple.js
  website/server/libs/payments/gems.js
  website/server/libs/payments/google.js
  website/server/libs/payments/paypal.js
  website/server/libs/payments/stripe.js
  website/server/libs/payments/stripe/api.js
  website/server/libs/payments/stripe/checkout.js
  website/server/libs/payments/stripe/index.js
  website/server/libs/payments/stripe/oneTimePayments.js
  website/server/libs/payments/stripe/subscriptions.js
  website/server/libs/payments/stripe/webhooks.js
  website/server/middlewares/index.js
Labels: status: pr: with author: needs work

#12883 Fixes mention link in a private message
  website/client/src/pages/private-messages.vue
Labels: status: pr: ready for review

#12779 Change $type of date for todos
  migrations/archive/2020/20201111_api_date.js
  test/api/v3/integration/tasks/POST-tasks_user.test.js
  website/server/controllers/api-v3/tasks.js
  website/server/models/task.js
Labels: status: pr: ready for review, status: pr: tested and approved; merge pending
