Repository HabitRPG/habitica, pull requests merged in 2020-07, with the labels that each got.

#12342 Fix bug where updated webhook options failed to save (fixes #12336)
  test/api/v3/integration/webhook/PUT-user_update_webhook.test.js
  website/server/controllers/api-v3/webhook.js
Labels: status: pr: ready for review

#12308 WIP. Changed the way how memberCount is incremented or decremented. Fixes #12275
  website/server/controllers/api-v3/groups.js
  website/server/models/group.js
Labels: status: pr: ready for review

#12369 Fix: new pm - canReceive
  website/client/src/pages/private-messages.vue
Labels: status: pr: ready for review

#12385 fix filter reset on pinning items
  website/client/src/components/shops/quests/index.vue
  website/client/src/components/shops/timeTravelers/index.vue
Labels: status: pr: ready for review

#12356 WIP. Accepting a redundant party invite will not remove the user from the party and let the user still be a part of it. Fixes #12291.
  test/api/v3/integration/groups/POST-groups_groupId_join.test.js
  website/server/controllers/api-v3/groups.js
Labels: status: pr: ready for review

#12384 Add Bulk Feed via query parameter
  test/api/v3/integration/user/POST-user_feed_pet_food.test.js
  test/common/ops/feed.js
  website/common/locales/en/pets.json
  website/common/script/ops/feed.js
  website/server/controllers/api-v3/user.js
Labels: status: pr: ready for review

#12335 MongoDB Transactions
  .github/workflows/test.yml
  .gitignore
  config.json.example
  gulp/gulp-build.js
  gulp/gulp-console.js
  gulp/gulp-tests.js
  package-lock.json
  package.json
  test/api/unit/libs/mongodb.js
  website/server/libs/mongodb.js
  website/server/libs/setupMongoose.js
Labels: status: pr: with author: needs work

#12395 Profile Page: redesign gear label
  website/client/src/components/userMenu/profileStats.vue
Labels: status: pr: being tested on gamma, status: pr: ready for review

#12117 API v3 Rate Limiter
  config.json.example
  package-lock.json
  package.json
  test/api/unit/middlewares/ipBlocker.test.js
  test/api/unit/middlewares/rateLimiter.test.js
  test/api/unit/middlewares/redirects.js
  website/common/script/errors/apiErrorMessages.js
  website/common/script/libs/errors.js
  website/server/libs/errors.js
  website/server/libs/setupExpress.js
  website/server/middlewares/appRoutes.js
  website/server/middlewares/index.js
  website/server/middlewares/ipBlocker.js
  website/server/middlewares/rateLimiter.js
  website/server/middlewares/redirects.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#12380 PR to fix: Disallow line breaks in display names
  test/api/v3/integration/user/PUT-user.test.js
  test/api/v4/user/auth/POST-user_verify_display_name.test.js
  website/common/locales/en/settings.json
  website/server/libs/user/index.js
  website/server/libs/user/validation.js
Labels: status: pr: ready for review

#12400 Members API: add limit query parameter to fetch up to 60 members with 1 call
  test/api/v3/integration/challenges/GET-challenges_challengeId_members.test.js
  test/api/v3/integration/groups/GET-groups_groupId_invites.test.js
  test/api/v3/integration/groups/GET-groups_groupId_members.test.js
  website/server/controllers/api-v3/members.js
Labels: status: pr: ready for review

#12207 Move from deprecated moment#zone to moment#utcOffset
  package-lock.json
  package.json
  test/api/unit/libs/cron.test.js
  test/api/unit/libs/preening.test.js
  test/api/unit/models/user.test.js
  test/api/v3/integration/tasks/GET-tasks_user.test.js
  test/common/fns/getUtcOffset.test.js
  test/common/libs/cron.test.js
  test/common/libs/taskDefaults.test.js
  test/common/shouldDo.test.js
  test/helpers/globals.helper.js
  website/client/src/app.vue
  website/client/src/components/settings/site.vue
  website/client/src/libs/auth.js
  website/client/src/store/index.js
  website/common/script/cron.js
  website/common/script/fns/getUtcOffset.js
  website/common/script/index.js
  website/common/script/libs/taskDefaults.js
  website/common/script/ops/scoreTask.js
  website/server/controllers/top-level/dataexport.js
  website/server/libs/cron.js
  website/server/libs/preening.js
  website/server/middlewares/cron.js
  website/server/models/user/methods.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#12406 Fix height of badges in multiline achievements
  website/client/src/components/userMenu/profile.vue
Labels: status: pr: ready for review

#12416 Remove unnecessary modal scrollbar
  website/client/src/app.vue
Labels: status: pr: ready for review

#12413 removing wrong info on updating challenge leader from apidoc
  website/server/controllers/api-v3/challenges.js
Labels: status: pr: ready for review

#12399 Updating daysOfMonths array when the startDate of a monthly is updated in the API - Fixes #12041
  test/api/v3/integration/tasks/PUT-tasks_id.test.js
  website/server/controllers/api-v3/tasks.js
Labels: status: pr: ready for review

#12420 fix(task list): update todo due date on every save
  website/client/src/components/tasks/task.vue
Labels: status: pr: ready for review

#12415 Paypal IPN Upgrade
  package-lock.json
  package.json
  website/server/controllers/top-level/payments/paypal.js
  website/server/libs/payments/paypal.js
Labels: status: pr: ready for review
