Repository HabitRPG/habitica, pull requests merged in 2020-09, with the labels that each got.

#12497 Change spellRogueStealthMaxedOut and spellAlreadyCast to a clearer wo…
  website/client/src/components/ui/datepicker.vue
  website/common/locales/en/spells.json
Labels: status: pr: ready for review

#12527 Filter challenge by owned
  test/api/v3/integration/challenges/GET-challenges_user.test.js
  website/server/controllers/api-v3/challenges.js
Labels: status: pr: ready for review

#12522 Correctly filter tasks in challenges and remove filters where unhelpful
  website/client/src/components/tasks/column.vue
  website/client/src/libs/store/helpers/filterTasks.js
  website/client/src/store/actions/tasks.js
  website/client/src/store/getters/tasks.js
Labels: status: pr: ready for review

#12341 Bugfix challenge tags to normal tags after a challenge has ended/deleted
  migrations/users/tag-challenge-field-string2bool.js
  test/api/v3/integration/challenges/POST-challenges_challengeId_winner_winnerId.test.js
  website/client/tests/unit/components/tasks/user.spec.js
  website/server/models/tag.js
Labels: status: pr: merged in develop; deploy pending

#12496 Frontend support and adjustments of current banned words blocking code to support new implementation (Fixes #12405)
  test/api/v3/integration/chat/POST-chat.test.js
  test/api/v3/integration/groups/PUT-groups.test.js
  website/client/src/components/groups/groupFormModal.vue
  website/common/locales/en/groups.json
  website/server/controllers/api-v3/chat.js
  website/server/controllers/api-v3/groups.js
  website/server/libs/guildsAllowingBannedWords.js
Labels: status: pr: tested and approved; merge pending

#12554 Fixed Privacy Policy anchor tag target attribute
  website/client/src/components/appFooter.vue
Labels: status: pr: ready for review

#12594 fix(chat) - issue 12586 - can't put links without titles in message b…
  test/api/unit/libs/highlightMentions.test.js
  website/server/libs/highlightMentions.js
Labels: status: pr: ready for review

#12363 Issue 11450 Adding keyboard accessibility to task board controls and purchases
  website/client/src/assets/scss/task.scss
  website/client/src/components/shops/buyModal.vue
  website/client/src/components/shops/shopItem.vue
  website/client/src/components/tasks/column.vue
  website/client/src/components/tasks/task.vue
Labels: status: pr: merged in develop; deploy pending

#12592 fix(export) - Issue 12482 - Fix messages in xml export.
  gulp/gulp-tests.js
  test/api/unit/libs/xmlMarshaller.test.js
  test/api/v3/integration/GET-dataexport.test.js
  website/server/controllers/top-level/dataexport.js
  website/server/libs/xmlMarshaller.js
  website/server/models/user/schema.js
Labels: status: pr: ready for review

#12559 Removed unused I18N strings from the `pets.json` files (related to issue #9957)
  website/common/locales/bg/pets.json
  website/common/locales/bn/pets.json
  website/common/locales/ca/pets.json
  website/common/locales/cs/pets.json
  website/common/locales/da/pets.json
  website/common/locales/de/pets.json
  website/common/locales/en/pets.json
  website/common/locales/en@pirate/pets.json
  website/common/locales/en_GB/pets.json
  website/common/locales/es/pets.json
  website/common/locales/es_419/pets.json
  website/common/locales/fil/pets.json
  website/common/locales/fr/pets.json
  website/common/locales/he/pets.json
  website/common/locales/hu/pets.json
  website/common/locales/id/pets.json
  website/common/locales/it/pets.json
  website/common/locales/ja/pets.json
  website/common/locales/ko/pets.json
  website/common/locales/la/pets.json
  website/common/locales/ms/pets.json
  website/common/locales/nb_NO/pets.json
  website/common/locales/nl/pets.json
  website/common/locales/pl/pets.json
  website/common/locales/pt/pets.json
  website/common/locales/pt_BR/pets.json
  website/common/locales/ro/pets.json
  website/common/locales/ru/pets.json
  website/common/locales/sk/pets.json
  website/common/locales/sr/pets.json
  website/common/locales/sv/pets.json
  website/common/locales/ta/pets.json
  website/common/locales/tr/pets.json
  website/common/locales/uk/pets.json
  website/common/locales/vi/pets.json
  website/common/locales/zh/pets.json
  website/common/locales/zh_TW/pets.json
Labels: status: pr: being tested on delta, status: pr: ready for review
