Repository HabitRPG/habitica, pull requests merged in 2021-04, with the labels that each got.

#13135 Clientside: Block low lvl for high lvl spells - Fixes #12904
  website/client/src/mixins/spells.js
  website/common/locales/en/character.json
  website/common/locales/en/spells.json
Labels: status: pr: with author: needs work

#13111 Send questInvited webhook to the quest inviter too
  test/api/v3/integration/quests/POST-groups_groupId_quests_invite.test.js
  website/server/controllers/api-v3/quests.js
Labels: status: pr: ready for review

#12987 #12781 Add a unified component for small modals
  website/client/src/assets/scss/mixins.scss
  website/client/src/components/achievements/dropCapReached.vue
  website/client/src/components/achievements/levelUp.vue
  website/client/src/components/achievements/wonChallenge.vue
  website/client/src/components/payments/successModal.vue
  website/client/src/components/ui/modal/smallModal.vue
  website/client/src/components/ui/modal/starred.vue
  website/client/src/components/ui/modal/your-rewards.vue
  website/client/tests/unit/components/achievements/levelUp.spec.js
  website/client/tests/unit/components/payments/successModal.spec.js
  website/client/tests/unit/components/ui/modal/smallModal.spec.js
Labels: status: pr: ready for review

#12968 12922 - Use absolute user URLs on production
  test/api/unit/libs/highlightMentions.test.js
  website/server/libs/highlightMentions.js
Labels: status: pr: ready for review

#13180 Various Chat Fixes - Fixes #12377
  website/client/src/components/chat/autoComplete.vue
  website/client/src/components/groups/chat.vue
Labels: status: pr: with author: needs work

#12860 Fixed issue RYA shows incorrect Dailies on two days after time zone change from Daylight Savings ending fixes #12765
  website/client/src/components/notifications.vue
Labels: status: pr: tested and approved; merge pending

#12445 Add checks for profanity to profile updates
  test/api/v3/integration/user/PUT-user.test.js
  test/api/v3/integration/user/auth/PUT-user_update_username.test.js
  test/api/v4/user/auth/POST-user_verify_display_name.test.js
  test/api/v4/user/auth/POST-user_verify_username.test.js
  website/common/locales/en/settings.json
  website/server/controllers/api-v3/auth.js
  website/server/libs/stringUtils.js
  website/server/libs/user/index.js
  website/server/libs/user/validation.js
Labels: status: pr: with author: needs work

#12204 Drag challenge tasks
  test/api/unit/libs/taskManager.js
  test/api/v3/integration/tasks/DELETE-tasks_id.test.js
  test/api/v3/integration/tasks/POST-tasks_unlink-all_challengeId.test.js
  test/api/v3/integration/tasks/POST-tasks_unlink-one_taskId.test.js
  test/api/v3/integration/tasks/challenges/GET_tasks_challenge.id.test.js
  test/api/v3/integration/tasks/groups/GET-tasks_group_id.test.js
  website/client/src/components/challenges/challengeDetail.vue
  website/client/src/components/group-plans/taskInformation.vue
  website/client/src/components/tasks/column.vue
  website/server/controllers/api-v3/challenges.js
  website/server/controllers/api-v3/tasks.js
  website/server/controllers/api-v3/tasks/groups.js
  website/server/controllers/api-v4/tasks.js
  website/server/libs/tasks/index.js
  website/server/libs/tasks/utils.js
  website/server/models/challenge.js
  website/server/models/group.js
Labels: status: pr: ready for review, type: notify helpers
