Repository HabitRPG/habitica, pull requests merged in 2021-01, with the labels that each got.

#12917 Remove forum link
  website/client/src/components/appFooter.vue
  website/client/src/components/groups/tavern.vue
  website/common/locales/bg/front.json
  website/common/locales/bn/front.json
  website/common/locales/cs/front.json
  website/common/locales/da/front.json
  website/common/locales/de/front.json
  website/common/locales/en/front.json
  website/common/locales/en@lolcat/front.json
  website/common/locales/en@pirate/front.json
  website/common/locales/en_GB/front.json
  website/common/locales/es/front.json
  website/common/locales/es_419/front.json
  website/common/locales/fr/front.json
  website/common/locales/he/front.json
  website/common/locales/hi/front.json
  website/common/locales/hu/front.json
  website/common/locales/id/front.json
  website/common/locales/it/front.json
  website/common/locales/ja/front.json
  website/common/locales/nl/front.json
  website/common/locales/pl/front.json
  website/common/locales/pt/front.json
  website/common/locales/pt_BR/front.json
  website/common/locales/ro/front.json
  website/common/locales/ru/front.json
  website/common/locales/sk/front.json
  website/common/locales/sr/front.json
  website/common/locales/sv/front.json
  website/common/locales/tr/front.json
  website/common/locales/uk/front.json
  website/common/locales/vi/front.json
  website/common/locales/zh/front.json
  website/common/locales/zh_TW/front.json
Labels: status: pr: ready for review

#12901 remove mention of Back Corner from Community Guidelines
  website/client/src/assets/images/community-guidelines/backCorner.png
  website/client/src/components/static/communityGuidelines.vue
  website/common/locales/en/communityGuidelines.json
Labels: status: pr: ready for review

#12882 Stripe Upgrade Cleanup
  test/api/unit/libs/payments/group-plans/group-payments-create.test.js
  test/api/unit/libs/payments/stripe/checkout.test.js
  test/api/unit/libs/payments/stripe/subscriptions.test.js
  test/api/unit/libs/payments/stripe/webhooks.test.js
  website/server/libs/payments/stripe/api.js
Labels: status: pr: ready for review

#12858 Update achievements.json
  website/common/locales/en/achievements.json
Labels: status: pr: ready for review

#12923 remove PER bonus for Brilliant Bloom (summer 2019 mage weapon)
  website/common/script/content/gear/sets/special/index.js
Labels: status: pr: tested and approved; merge pending

#12939 Add string blockYourself
  website/common/locales/en/groups.json
Labels: status: pr: ready for review

#12696 Make start date and day of month aware of timezones (fixes #12555)
  test/api/v3/integration/tasks/POST-tasks_user.test.js
  test/api/v3/integration/tasks/PUT-tasks_id.test.js
  test/api/v3/integration/tasks/challenges/POST-tasks_challenge_id.test.js
  test/api/v3/integration/tasks/challenges/PUT-tasks_challenge_challengeId.test.js
  test/api/v3/integration/tasks/groups/POST-tasks_group_id.test.js
  website/server/controllers/api-v3/tasks.js
  website/server/libs/taskManager.js
  website/server/models/task.js
Labels: status: pr: being tested on delta, status: pr: ready for review

#12935 Hotfix: moving pinned items
  test/api/v3/integration/user/POST-move-pinned-item.js
  website/common/script/index.js
  website/server/controllers/api-v3/user.js
Labels: status: pr: ready for review
