Repository HabitRPG/habitica, pull requests merged in 2021-09, with the labels that each got.

#13465 Fix Storybook Installation and production build CI
  .github/workflows/test.yml
  website/client/config/storybook/README.md
  website/client/package-lock.json
  website/client/package.json
  website/client/scripts/npm-postinstall.js
Labels: status: pr: ready for review

#13476 Improve the checklists in the apidocs
  website/server/controllers/api-v3/tasks.js
Labels: status: pr: tested and approved; merge pending

#13449 Fixes aborted Quest should appear in Quest Inventory without manual sync · Issue #13289
  website/client/src/components/groups/questActions.mixin.js
Labels: status: pr: ready for review

#13327 Fix: Quest Rewards
  website/client/src/components/shops/quests/buyQuestModal.vue
  website/client/src/components/shops/quests/quest-dialog.stories.js
  website/client/src/components/shops/quests/quest-helper.mixin.js
  website/client/src/components/shops/quests/questRewards.vue
Labels: status: pr: with author: needs work

#13414 Dark mode input fix (fixes #13312)
  website/client/src/components/challenges/challengeModal.vue
  website/client/src/components/shops/buyModal.vue
  website/client/src/components/shops/quests/buyQuestModal.vue
  website/client/src/pages/private-messages.vue
Labels: status: pr: with author: needs work

#13311 Correct issues shown for guilds and parties when accessing through notifications, Fixes #13256
  website/client/src/components/challenges/groupChallenges.vue
Labels: status: pr: ready for review

#13494 Improve Z-Indexes for Notifications / Menus / Toolbar
  website/client/src/assets/scss/create-task.scss
  website/client/src/components/snackbars/notifications.vue
  website/client/src/components/z-index-overview.md
Labels: status: pr: ready for review, status: pr: being tested on delta

#13493 3x3 grid corrections for several backgrounds
  website/raw_sprites/spritesmith/backgrounds/background_harvest_fields.png
  website/raw_sprites/spritesmith/backgrounds/background_harvest_moon.png
  website/raw_sprites/spritesmith/backgrounds/background_rainforest.png
  website/raw_sprites/spritesmith/backgrounds/background_rolling_hills.png
  website/raw_sprites/spritesmith/backgrounds/background_school_of_fish.png
Labels: status: pr: ready for review

#13495 remove timer for quests in inventory (fixes #13224)
  website/client/src/components/inventory/items/index.vue
  website/client/src/components/shops/quests/questInfo.vue
Labels: status: pr: tested and approved; merge pending

#13507 remove sample forms from apidoc
  .gitignore
  apidoc/apidoc.json
  apidoc/header.md
  gulp/gulp-apidoc.js
Labels: status: pr: tested and approved; merge pending
