Repository HabitRPG/habitica, pull requests merged in 2022-04, with the labels that each got.

#13910 Redesign: "Day Start Adjustment"
  website/client/src/components/settings/dayStartAdjustment.vue
  website/client/src/components/settings/site.vue
  website/common/locales/en/settings.json
Labels: status: pr: ready for review, status: pr: being tested on delta

#13932 Change update to updateOne in gdpr-users-delete.js
  scripts/gdpr-delete-users.js
Labels: status: pr: merged in develop; deploy pending

#13818 Update: Quest Refactoring
  website/common/script/content/constants/index.js
  website/common/script/content/quests.js
  website/common/script/content/quests/generic.js
  website/common/script/content/quests/masterclasser.js
  website/common/script/content/quests/pets.js
  website/common/script/content/quests/potions.js
  website/common/script/content/quests/seasonal.js
  website/common/script/content/quests/series.js
  website/common/script/content/quests/timeTravel.js
  website/common/script/content/quests/world.js
Labels: status: pr: ready for review

#13930 Removes the Year Sub Menu for Unlocked Background (Fixes Issue #13373)
  website/client/src/components/creatorIntro.vue
Labels: status: issue: on hold - needs design

#13730 update user and group in a transaction when creating a group. fixes #12124
  test/api/v3/integration/groups/GET-groups.test.js
  test/api/v3/integration/groups/POST-groups.test.js
  website/server/controllers/api-v3/groups.js
Labels: status: pr: with author: needs work
